### ISSUE TITLE
APIにprefixを付ける、返り値をVoicevoxResultCodeで統一する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#125]
## 内容

API用headerをincludeしたときに宣言済みの名前を汚してしまうので、`voicevox_` prefixを付ける形で統一したいです。
また、ついでに返り値を`VoicevoxResultCode`で統一することで、last_error_messageをなくしたいです。

これら２つの破壊的変更を適用するのがこのissueの目的です。

### Pros 良くなる点

使いやすくなる。

### Cons 悪くなる点

APIが変わる破壊的変更なので案内が必要。

## その他

- https://github.com/VOICEVOX/voicevox_core/pull/124#discussion_r866176379

での議論結果のまとめをissue化しました。

**Comment by Hiroshiba** [comment]
エラーはついでにstderrに流すようにすると良いかも

- https://github.com/VOICEVOX/voicevox_core/issues/95

**Comment by qwerty2501** [comment]
破壊的変更というくくりで 配信中に話してたinitializeの引数をstruct化もしたほうがよいかもです
イメージとしてはこんな感じ
```c++
typedef struct {
   // option の引数をフィールドに入れる
} VoicevoxInitializeOption;

VoicevoxInitializeOption voicevox_default_initialize_option();

VoicevoxResultCode voicevox_initialize(VoicevoxInitializeOption option);
```

**Comment by qwerty2501** [comment]
これは完了扱いでよさそうなのでCloseします
