### ISSUE TITLE
埋め込みファイルの数が多いとARMHFでビルドエラーが出る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#132]
## 不具合の内容

埋め込みファイルの数が多いとarmhfビルドがエラーになります。

### 現象・ログ

実際のビルドログはこちらです https://github.com/Hiroshiba/voicevox_core/runs/6438083012?check_suite_focus=true

一部抜粋してみます。

```bash
Run cmake --build . --config Release

...

/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: BFD (GNU Binutils for Ubuntu) 2.30 assertion fail ../../bfd/elf32-arm.c:9509
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: BFD (GNU Binutils for Ubuntu) 2.30 assertion fail ../../bfd/elf32-arm.c:9509
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: BFD (GNU Binutils for Ubuntu) 2.30 assertion fail ../../bfd/elf32-arm.c:9509
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: BFD (GNU Binutils for Ubuntu) 2.30 assertion fail ../../bfd/elf32-arm.c:9509
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: BFD (GNU Binutils for Ubuntu) 2.30 assertion fail ../../bfd/elf32-arm.c:9509
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: BFD (GNU Binutils for Ubuntu) 2.30 assertion fail ../../bfd/elf32-arm.c:9509
/usr/lib/gcc-cross/arm-linux-gnueabihf/8/../../../../arm-linux-gnueabihf/bin/ld: BFD (GNU Binutils for Ubuntu) 2.30 assertion fail ../../bfd/elf32-arm.c:9509
collect2: error: ld returned 1 exit status
make[2]: *** [core/libcore.so] Error 1
make[1]: *** [core/CMakeFiles/core.dir/all] Error 2
make: *** [all] Error 2
core/CMakeFiles/core.dir/build.make:829: recipe for target 'core/libcore.so' failed
CMakeFiles/Makefile2:115: recipe for target 'core/CMakeFiles/core.dir/all' failed
Makefile:135: recipe for target 'all' failed
Error: Process completed with exit code 2.
```

### 再現手順

ブランチは[こちら](https://github.com/Hiroshiba/voicevox_core/tree/%E5%9F%8B%E3%82%81%E8%BE%BC%E3%81%BF%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E6%95%B0%E3%81%8C%E5%A4%9A%E3%81%84%E3%81%A8ARMHF%E3%81%A7%E3%83%93%E3%83%AB%E3%83%89%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E5%87%BA%E3%82%8B%E3%81%8B%E3%82%82)です

* DECODEなどのモデルを大量にembedする
  * こんな感じです https://github.com/Hiroshiba/voicevox_core/commit/d6a7dd831ed96f46a47501d94013ea3909f8946b
* ビルドする
* エラーが出る

### 期待動作

エラーが出ずにビルドできる

## OSの種類/ディストリ/バージョン

linux armhf

## その他

* モデル埋め込みのプルリクエスト
  * https://github.com/VOICEVOX/voicevox_core/pull/99
* armhf周りのプルリクエスト
  * https://github.com/VOICEVOX/voicevox_core/pull/41

新しいキャラクター追加のためにモデルを足したところエラーに遭遇しました。
解決が難しそうであれば、いったんarmhfをビルドから外したいと思います。

**Comment by Hiroshiba** [comment]
@Oyaki122 さん、もしなにかわかる点あれば･･･！

それと[こちらのissue](https://github.com/VOICEVOX/voicevox_core/issues/67)で大変お世話になった @Lapis256 さんも、もしわかる点あればぜひ･･･！

**Comment by Hiroshiba** [comment]
製品版のもち子さんが増えるタイミングでarmhf版がビルドできなくなるので、こちらの問題が解決するまで製品版のarmhfはいったん配布しない形式となりそうです。

**Comment by Hiroshiba** [comment]
[0.12.3](https://github.com/VOICEVOX/voicevox_core/releases/tag/0.12.3)のビルドから提供を停止しました。

**Comment by aoirint** [comment]
埋め込みの実装はよくわかっていないですが、binutilsのソースコードを見に行ってみました。

対応するエラー（Assetion Error）を出している行 (`bfd/elf32-arm.c:L9509`): https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=bfd/elf32-arm.c;h=0b250cea270bcbf9e823c29ab0ad7a0de498ce76;hb=8db5daf9efe8a6174d3b10ac7bba8c178836e9ce#l9509

```c
/* Calculate the displacement between the PLT slot and the
   entry in the GOT.  The eight-byte offset accounts for the
   value produced by adding to pc in the first instruction
   of the PLT stub.  */
got_displacement = got_address - (plt_address + 8);

...

if (!elf32_arm_use_long_plt_entry)
  {
    BFD_ASSERT ((got_displacement & 0xf0000000) == 0);

...
```

`elf32_arm_use_long_plt_entry`というフラグが立っていればassertionを回避できそう？

このフラグを有効化する関数`bfd_elf32_arm_use_long_plt(void)`を呼び出しているのは、`ld/emultempl/armelf.em:L773`で、

- https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=ld/emultempl/armelf.em;h=35908236adb26a601666f3149edbbb22ed924348;hb=8db5daf9efe8a6174d3b10ac7bba8c178836e9ce#l773

たどるとldに`--long-plt`というオプションを渡せればよさそう？

- `ld/emultempl/armelf.em:L649`: https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=ld/emultempl/armelf.em;h=35908236adb26a601666f3149edbbb22ed924348;hb=8db5daf9efe8a6174d3b10ac7bba8c178836e9ce#l649

CMakeLists.txtの指定でgccに`-Xlinker --long-plt`が渡るようにしてビルドしてみたところ、再現手順のブランチと同じ変更 https://github.com/Hiroshiba/voicevox_core/commit/d6a7dd831ed96f46a47501d94013ea3909f8946b をして https://github.com/aoirint/voicevox_core/commit/6d4640e9de7b0a3a9a8464be18047e73977df01d ビルドは通りました。

- https://github.com/aoirint/voicevox_core/runs/7065415817

**Comment by Hiroshiba** [comment]
おー！！！

実装も見てみました！
`--long-plt`の別の影響が少し不安ですが、影響があってもARMHFだけなので、良さそうな気がしました！！

**Comment by Hiroshiba** [comment]
↑のPRでビルドできるようになったのでcloseします！ありがとうございました！！
