### ISSUE TITLE
GPU（CUDA・DirectML）版コアが期待通りに動いていない可能性がある

### ISSUE THREAD

**Issue by PickledChair** [VOICEVOX/voicevox_core#143]
## 不具合の内容

Twitter における報告（現象・ログを参照）から、DirectML 版コアで `yukarin_sa` が期待したように動いていない可能性が考えられました。推論結果として異常な数値が返ってくるようです。

### 現象・ログ

当該現象が報告されたツイート： https://twitter.com/maki07061210/status/1531507875234861056

以下、引用です：

> GPU版に限り、イントネーションのバーが
> 限界突破しており
>
> 冥鳴ひまりが下方向にイントネーションが振れております
>
> 青山流星は上方向にイントネーションが振れております。
>
> CPU版では特にありませんでした

### 再現手順

https://github.com/VOICEVOX/voicevox/releases/tag/0.12.0 で配布されているプレビュー版の VOICEVOX（DirectML 版）を起動し、冥鳴ひまり・青山流星の音声合成を試みる。

### 期待動作

GPU (CUDA, DirectML) 版コアでも CPU 版とほぼ同じ推論結果を得られる。

---

## OSの種類/ディストリ/バージョン

*   Windows (10? 11?)

Linux の GPU 版でも同様の問題が発生するかどうかは、今のところ不明です。

---

## その他

Discord におけるやりとりで、以下のような追加情報が得られています。

### 1. CUDA 版も挙動がおかしいかもしれない

関連は不明ですが、CUDA 版の挙動が CPU 版と異なるという現象は、以前からあったかもしれないことが指摘されていました。CUDA 版も同様の問題を抱えている可能性があります：

> なんかそういえばCUDA使ってたときyukarin_saだけもGPUとCPUで挙動違うみたいなのあった気がする。
> その辺りが実はメモリ参照とかがぶっ壊れてて、DIrectML版だと運が良くてこうなったりするのかな。。。

### 2. 全ての `Ort::Session` インスタンスに対して GPU オプションが設定されるような変更があった

以前のコアでは、`yukarin_sa` は CPU で動かすようになっていたはず、という指摘がありました：

> あれ、でも今も昔もyukarin_saはCPUで動かすようになってませんでしたっけ
> あ、モデル複数読み込みを実装した時に崩壊したっぽい...?
> もしかしたら、yukarin_saはDirectMLが壊れてるようにCUDAも壊れてる可能性はありそうではある...?

確認したところ、バージョン 0.11 以前では実際に、decode モデルに対応する `Ort::Session`インスタンスだけに `OrtCUDAProviderOptions` が設定されていました：

https://github.com/VOICEVOX/voicevox_core/blob/afa32e56a0ebc41178dcd6c27ddd862cb6eab47d/core/src/core.cpp#L119-L127

それに対してバージョン 0.12 現在は、`Status` の初期化時に GPU のオプションが設定され、以降全ての `Ort::Session` インスタンスに対してこのオプションが適用されています：

https://github.com/VOICEVOX/voicevox_core/blob/d62a44b87048ba487ee4313e23b2adb59687189c/core/src/core.cpp#L90-L98

今後、元の実装に近づけることも提案されました。これで問題が解決される可能性があります：

> 今やるなら、common_session_optionsとdecode_session_optionsを用意する感じになりそう...?

**Comment by Hiroshiba** [comment]
丁寧なissue作成ありがとうございます！！
報告いただいた方に実際のイントネーションのデータをいただけたのでこちらに記載します。

CPU版
<details>

```json
{
  "appVersion": "0.12.0",
  "audioKeys": ["8bd36e9f-ff47-53a3-bda2-2743486dd5ea"],
  "audioItems": {
    "8bd36e9f-ff47-53a3-bda2-2743486dd5ea": {
      "text": "こんにちは",
      "styleId": 14,
      "query": {
        "accentPhrases": [
          {
            "moras": [
              {
                "text": "コ",
                "consonant": "k",
                "consonantLength": 0.0754309743642807,
                "vowel": "o",
                "vowelLength": 0.07409141957759857,
                "pitch": 5.552915096282959
              },
              {
                "text": "ン",
                "vowel": "N",
                "vowelLength": 0.1026434376835823,
                "pitch": 5.556232929229736
              },
              {
                "text": "ニ",
                "consonant": "n",
                "consonantLength": 0.04291911795735359,
                "vowel": "i",
                "vowelLength": 0.05864773318171501,
                "pitch": 5.536922454833984
              },
              {
                "text": "チ",
                "consonant": "ch",
                "consonantLength": 0.10804294049739838,
                "vowel": "i",
                "vowelLength": 0.04639147222042084,
                "pitch": 5.486067771911621
              },
              {
                "text": "ワ",
                "consonant": "w",
                "consonantLength": 0.06472866982221603,
                "vowel": "a",
                "vowelLength": 0.1401432454586029,
                "pitch": 5.48008394241333
              }
            ],
            "accent": 5,
            "isInterrogative": false
          }
        ],
        "speedScale": 1,
        "pitchScale": 0,
        "intonationScale": 1,
        "volumeScale": 1,
        "prePhonemeLength": 0.1,
        "postPhonemeLength": 0.1,
        "outputSamplingRate": 24000,
        "outputStereo": false,
        "kana": ""
      }
    }
  }
}
```

</details>

GPU版

<details>

```json
{
  "appVersion": "0.12.0",
  "audioKeys": ["1a492d3c-383c-2318-433d-4338c884066f"],
  "audioItems": {
    "1a492d3c-383c-2318-433d-4338c884066f": {
      "text": "こんにちは",
      "styleId": 14,
      "query": {
        "accentPhrases": [
          {
            "moras": [
              {
                "text": "コ",
                "consonant": "k",
                "consonantLength": 0.0754309743642807,
                "vowel": "o",
                "vowelLength": 0.07409140467643738,
                "pitch": 2.4398934841156006
              },
              {
                "text": "ン",
                "vowel": "N",
                "vowelLength": 0.1026434674859047,
                "pitch": 2.9955005645751953
              },
              {
                "text": "ニ",
                "consonant": "n",
                "consonantLength": 0.04291912168264389,
                "vowel": "i",
                "vowelLength": 0.058647748082876205,
                "pitch": 2.0904135704040527
              },
              {
                "text": "チ",
                "consonant": "ch",
                "consonantLength": 0.10804295539855957,
                "vowel": "i",
                "vowelLength": 0.04639146476984024,
                "pitch": 1.3038713932037354
              },
              {
                "text": "ワ",
                "consonant": "w",
                "consonantLength": 0.06472864747047424,
                "vowel": "a",
                "vowelLength": 0.1401432901620865,
                "pitch": 1.440786600112915
              }
            ],
            "accent": 5,
            "isInterrogative": false
          }
        ],
        "speedScale": 1,
        "pitchScale": 0,
        "intonationScale": 1,
        "volumeScale": 1,
        "prePhonemeLength": 0.1,
        "postPhonemeLength": 0.1,
        "outputSamplingRate": 24000,
        "outputStereo": false,
        "kana": ""
      }
    }
  }
}
```

</details>

**Comment by Hiroshiba** [comment]
こちら、よくよく考えたらCUDA版であれDirectML版であれ、GPUを使う場合は期待どおりに動かない可能性があり、優先度が高いと思われます。
実装でき次第すぐリリースしたいと思います。

**Comment by Yosshi999** [comment]
https://github.com/microsoft/onnxruntime/issues/9582
ORT_DISABLE_ALLを指定して（どこに？）最適化を切ることでCPUとの差異が消えたというissueがありますね

**Comment by Hiroshiba** [comment]
なるほどーーーーーー！！！
実際最適化を切るとどれくらいパフォーマンス落ちるか検証してみたいですね･･･！！

**Comment by Hiroshiba** [comment]
報告を多く頂いているので、可能であればhotfixにしたいと考えています。

GTX1000番台で発生するのかもしれません･･･。
https://twitter.com/HackYugioh/status/1531683972752629760
https://twitter.com/Lutz_Kyun/status/1531676638131326976
https://twitter.com/rizsuna/status/1531682563827200000

**Comment by Hiroshiba** [comment]
いろいろ検討した結果、どうやらGPUモードでイントネーション推論することによりラグが発生して不具合が生じることもあるので、イントネーションと長さの推論はCPUで行うのが良さそうに思いました！

- https://github.com/VOICEVOX/voicevox/issues/828

こちら、修正でき次第hotfixリリースをしたいと思います。

**Comment by Hiroshiba** [comment]
↑の修正を加え、製品版の0.12.2にて採用されました。
少なくともCUDA版で生じていた問題は解決されているようですが、DirectML版でも問題が解決しているかどうかはちょっと不明です。

またいずれDirectML版を案内する際に問題が生じたらissueを再オープンすることにして、こちらのissueは解決したと言うことにしたいと思います。
ありがとうございました！！

**Comment by jasonzhang761213** [comment]
こちらも、こんにちは　だけ、GPUのDLLを使っている場合（GPU、CPUかかわらず）、ダンプしちゃいました。
CPU　コアの場合、問題なくTTSできます

**Comment by jasonzhang761213** [comment]
補足ですが、僕のGPUもGTX１０５０
