### ISSUE TITLE
音声の前の無音を少し長くするワークアラウンドをエンジンからコアに移す

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#17]
https://github.com/Hiroshiba/voicevox_engine/pull/128

**Comment by qwerty2501** [comment]
https://github.com/VOICEVOX/voicevox_engine/issues/132 込でできないかやってみます

**Comment by Hiroshiba** [comment]
おお！！　お願いします！

**Comment by qwerty2501** [comment]
少し考えたのですが、coreに移すということはC++側のコードにworkaroundを移すということですよね。
しかしC++側でcoreのAPIを変えずにこのworkaroundを実装するには余計なallocate処理とcopy処理を実行せねばならず、パフォーマンスに影響を与えます。
特にoutputデータのcopyには音声データそのものをコピーするのでかなり大きなコストになりそうです。
engine側にこのworkaroundを実装していた場合はこのコストは発生しないのでcoreにこの実装を移すのはやめたほうがよいのではないでしょうか？

**Comment by Hiroshiba** [comment]
なるほどです。
allocateとcopyが不要な方法は無さそうでしょうか…？👀

**Comment by qwerty2501** [comment]
そうですね。
無音区間分余分にサンプリングする必要があるのでその分多くのメモリが必要になりますが、このライブラリのユーザーはoutputにはlengthに対応する分のメモリ量しか割り当てないため内部で新しくより大きなメモリを割り当てた領域をoutput_tensorに割り当てなければなりません。引数のoutputに割り当てられるメモリ量は完全にライブラリユーザー依存のためこれを避けることは無理でしょう。
内部でメモリを確保するということは与えられたoutputに対してコピーして返してやる必要があるのでこれも避けられないです。

**Comment by Hiroshiba** [comment]
なるほどです、コードを読んで理解できました！
呼ぶ側で出力用のメモリを確保する形式なので、おっしゃる通りコピーが必要だと思います。

迂回策としては、エラーメッセージ取得APIのように計算結果を取得するAPIを生やすとかでしょうか。
API変わるので出来る限り避けたくはありますが…。

もしくは、メモリ確保&コピーしてもそこまで時間かからなかったりするのであれば、実装しちゃってもいいかもと感じました。
とりあえず時間測定してみてから判断にして、それまではとりあえずエンジン側に実装するというのはいかがでしょう。

**Comment by qwerty2501** [comment]
> 迂回策としては、エラーメッセージ取得APIのように計算結果を取得するAPIを生やすとかでしょうか。
API変わるので出来る限り避けたくはありますが…。

outputだけなら解決できますがf0(恐らくphonemesも？)についてはこれをしてもコピーしてやる必要はあります。f0はoutputほどサイズは大きくはないでしょうが。
またこれしかもうないというのであればわかりますが、workaroundのためにAPI定義を変えるのはあまり良くないと思います。
ただworkaroundとは別でoutputの必要な長さを取得する関数はあっても良さそうです。

> もしくは、メモリ確保&コピーしてもそこまで時間かからなかったりするのであれば、実装しちゃってもいいかもと感じました。
とりあえず時間測定してみてから判断にして、それまではとりあえずエンジン側に実装するというのはいかがでしょう。

最近のメモリは高速なので富豪的にいくのはありかもしれません。
とりあえずC++で1MBぐらいのデータをコピーする際のベンチマークでもとってみますか。

**Comment by qwerty2501** [comment]
こんな感じのベンチマークをとってみました
```cpp
#include "cstring"
#include <benchmark/benchmark.h>
#include <vector>

// Define another benchmark
static void BM_AllocateAndMemoryCopy(benchmark::State &state) {
  constexpr auto mem_size = 1024 * 1024;
  auto output = std::vector<float>(mem_size);
  for (auto _ : state) {
    const auto inner_memory = std::vector<float>(mem_size);
    std::memcpy(output.data(), inner_memory.data(),
                sizeof(float) * inner_memory.size());
  }
}

BENCHMARK(BM_AllocateAndMemoryCopy)->Unit(benchmark::kSecond);

BENCHMARK_MAIN();
```
結果
```bash
> ./mybenchmark
2022-01-03T00:31:47+09:00
Running ./mybenchmark
Run on (16 X 3200 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x8)
  L1 Instruction 64 KiB (x8)
  L2 Unified 512 KiB (x8)
  L3 Unified 8192 KiB (x2)
Load Average: 0.27, 0.40, 0.44
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-------------------------------------------------------------------
Benchmark                         Time             CPU   Iterations
-------------------------------------------------------------------
BM_AllocateAndMemoryCopy      0.004 s         0.004 s           315
```

余裕ですね

**Comment by y-chan** [comment]
wav自体も1MBを超えることはまずなく(ちょっと長文でもせいぜい500kB程度)、これ以上に時間が短く済むと思います。
CPUやメモリコピーの遅さ、メモリの消費量を過度に気にする必要はないと思うので、この程度のコピーぐらいは許容できるのではないかなと思います。
コア側に実装するので何ら問題ないのではと考えます。

**Comment by Hiroshiba** [comment]
おお、なるほどです！！
ぱっと計算してみましたが、10秒の音声でも`floatの4B * 24000(Hz) * 10(s) / 1024 / 1024 = 0.92MB`でした。
生成時間のが圧倒的に長いのでワークアラウンドをC++に実装する方針でひとまず良さそうに感じました。

> ただworkaroundとは別でoutputの必要な長さを取得する関数はあっても良さそうです

確かに･･･少なくともドキュメントはほしいですね･･･

**Comment by Oyaki122** [comment]
コア側での実装は終了したためcloseします
エンジンでの機能削除はこのissueへ: VOICEVOX/voicevox_engine#281
