### ISSUE TITLE
python向けのパッケージを作成するかどうか・形態どうするか

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#209]
## 内容

コアはC言語での動作を想定しており、コア側で作ったAudioQueryやwavのメモリ解放することを、使う側が意識する必要があります。
仮にエンジン側にあるコア周りの処理を全部コア側に移す場合、この辺りのメモリ意識が煩雑になります。

もしコア側にメモリ管理をしなくていいpythonパッケージがあれば、エンジン側は楽になり、pythonユーザーからもありがたがられるはずです。
ここでは、そのpythonラッパーを作るか、作る場合どういうファイル・リポジトリ構成にするかを議論したいです。

### Pros 良くなる点

エンジン側が楽になる
pythonユーザーが喜ぶ

### Cons 悪くなる点

そのパッケージを管理する必要がある

### 実現方法

まず要不要を考える必要があります。
続いてリポジトリを分けるかどうか、ファイル構成はどうするかが議論の対象になると思います。

将来的には多言語向けのコアラッパーを展開する可能性もあるので、その辺りも考慮して決めていきたいです。

**Comment by Hiroshiba** [comment]
個人的には、将来的には多言語向けのコアラッパーを展開するために、一旦お試しも兼ねてpython版パッケージを作るのがいいかなと思いました。
お試し用途なのでこのリポジトリでサクッと試すのがいいのかなと。
ファイル構成は、たぶんrootにsetup.pyを置くのは確定で、あとはwrapper/python辺りのディレクトリを作ってそこにクラス作る･･･とかを考えてみました。

**Comment by qwerty2501** [comment]
> ファイル構成は、たぶんrootにsetup.pyを置くのは確定

ディレクトリ切っておくとあとでリポジトリ移動させるときに楽かなと思ったんですが、pythonではそういうものって感じですかね？

**Comment by Hiroshiba** [comment]
一応サブディレクトリも切れるっぽいです！
https://stackoverflow.com/questions/13566200/how-can-i-install-from-a-git-subdirectory-with-pip

> git+https://git.repo/some_repo.git#egg=version_subpkg&subdirectory=repo

pythonだけならサブディレクトリでも良いかも。

**Comment by qryxip** [comment]
Discordでも書いたのですが、[PyO3](https://pyo3.rs)を使ってvoicevox_coreをラップしてみました。

Rustの`struct Internal`から、Pythonからはこのように見えるGC管理下の`class VoicevoxCore`を作ることができます。ただしPythonとしてのAPIを記述するためのボイラープレートは必要です。

```python
class VoicevoxCore:
    def __init__(
        self, use_gpu: bool, cpu_num_threads: int, load_all_models: bool
    ) -> None:
        pass
    def __repr__(self) -> str:
        pass
    def load_model(self, speaker_id: int) -> None:
        pass
    def is_model_loaded(self, speaker_id: int) -> bool:
        pass
    @property
    def metas(self) -> str:
        pass
    @property
    def supported_devices(self) -> str:
        pass
    def load_openjtalk_dict(self, dict_path: str) -> None:
        pass
    def tts(self, text: str, speaker_id: int) -> bytes:
        pass
    def tts_from_kana(self, text: str, speaker_id: int) -> bytes:
        pass
```

またコマンド一発でwhl化することもできます。whlはこのような構造です。onnxruntimeのDLLをここに詰め込むこともできると思います。

```console
Archive:  ../../target/wheels/voicevox_core_py-0.0.0-cp38-abi3-linux_x86_64.whl
Zip file size: 63117704 bytes, number of entries: 7
-rw-r--r--  4.6 unx       60 b- defN 22-Aug-13 13:32 voicevox_core_py-0.0.0.dist-info/METADATA
-rw-r--r--  4.6 unx       98 b- defN 22-Aug-13 13:32 voicevox_core_py-0.0.0.dist-info/WHEEL
-rw-r--r--  4.6 unx      135 b- defN 22-Aug-13 13:32 voicevox_core/__init__.py
-rw-r--r--  4.6 unx      679 b- defN 22-Aug-13 13:32 voicevox_core/__init__.pyi
-rw-r--r--  4.6 unx        0 b- defN 22-Aug-13 13:32 voicevox_core/py.typed
-rwxr-xr-x  4.6 unx 99215024 b- defN 22-Aug-13 13:32 voicevox_core/voicevox_core.abi3.so
-rw-r--r--  4.6 unx      566 b- defN 22-Aug-13 13:32 voicevox_core_py-0.0.0.dist-info/RECORD
7 files, 99216562 bytes uncompressed, 63116698 bytes compressed:  36.4%
```

core.dllをラップする方針と比べたときのPros/Consとしては、以下のような感じだと思います。

## Pros

- オブジェクトをPythonのGCに乗せることができます。エンジン側でRAIIを考える必要はありません。
- APIがシンプルになります。
    - `ndarray`, `str`, `bytes`の相互変換はPyO3側でやってくれます。

## Cons

- リリースの仕組みが上手く構成できるかどうかがわかりません。PyO3を使う場合voicevox_coreのDLLからではなく、Rustのクレートとしてのvoicevox_coreからビルドする必要があります。whlにORTのDLLも同梱してこのリポジトリからリリースし、エンジン側で上手く`pip install`という形になるとは思います。
- GCを前提としてAPIを考えるとcore.dllのそれと乖離してしまうかもしれません。
- PyO3にはsoundness (健全性)に関わるissueがたまにあります。使い方次第ではデータ競合やGCの誤作動が発生するかもしれません。とはいえPyO3は長年開発されてきたライブラリであるため、冒険をしてそうな機能を避ければ心配するほどではないかもしれません。
- PyO3というライブラリを使うので、(まだ具体的な計測はしてませんが)ビルド時間は伸びると思います。またmaturin経由の`cargo build`では、何かの`cfg`を有効化しているのか別のdependency graph上でビルドしているような気がします。

**Comment by qwerty2501** [comment]
discordでも書いたのですがこっちにも書いておきます。
仮にpyo3向けの実装を提供する場合、現状voicevox_coreにはC API用のコードがありますがこれはpyo3には不要です。
またpyo3にはpyo3用のコードが必要なので現状のcrateだけでやろうとするとfeature分けしなければならなくなるでしょう。
さらに今後pyo3のような別言語向けのfront実装を行う可能性を考えると以下のようにcrate分けしたほうが良さそうに感じました。これであればfeatureで分ける必要もなくコードの見通しを保ったまま機能を提供できます。

```
voicevox_core
└── crates
    ├── voicevox_core
    ├── voicevox_core_c_ffi
    ├── voicevox_core_pyo3
    └──  ... 
```

**Comment by Hiroshiba** [comment]
PyO3良いですね！！
あとリリースの部分が良い感じになれば、実験的機能という形でマージできればと考えています。
（実験的機能というのは、完全にこの機能がないと動かないような仕組みは避けつつ、メンテナンスは続けて我々の間で評価してみるという感じです）

crate分けるのも良さそうですね･･･！

**Comment by qryxip** [comment]
> - またmaturin経由の`cargo build`では、何かの`cfg`を有効化しているのか別のdependency graph上でビルドしているような気がします。

これについてですが「何かの`cfg`を有効化している」というのは勘違いで、単に`--locked`を忘れてCargo.lockを無視した状態でビルドしていたためでした。

ビルド時間についての私の理解ですが、PyO3を使う場合、次の4通りのdependency graphが存在することになると思います。

1. `voicevox_core`の`cargo build`
    `{voicevox_core}`の`dependencies` ∪ `voicevox_core`の`dev-dependencies`
2. `voicevox_core_c_ffi`の`cargo build`
    `{voicevox_core,voicevox_core_c_ffi}`の`dependencies` ∪ `voicevox_core_c_ffi`の`dev-dependencies`
3. `voicevox_core_pyo3`の`cargo build`
    `{voicevox_core,voicevox_core_pyo3}`の`dependencies` ∪ `voicevox_core_pyo3`の`dev-dependencies`
4. `voicevox_core_pyo3`の`maturin build`で呼び出される`cargo build`
    `onnxruntime-sys`の手前までは3.と同じ、`onnxruntime-sys`から先は別

    ```console
    ❯ maturin build --locked --manifest-path ./crates/voicevox_core_py/Cargo.toml
    🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.8
    🐍 Not using a specific python interpreter
       Compiling onnxruntime-sys v0.0.24 (https://github.com/VOICEVOX/onnxruntime-rs.git#8b45a4a9)
       Compiling onnxruntime v0.0.29 (https://github.com/VOICEVOX/onnxruntime-rs.git#8b45a4a9)
       Compiling voicevox_core v0.1.0 (/home/ryo/src/github.com/VOICEVOX/voicevox_core/crates/voicevox_core)
       Compiling voicevox_core_py v0.0.0 (/home/ryo/src/github.com/VOICEVOX/voicevox_core/crates/voicevox_core_py)
        Finished dev [unoptimized + debuginfo] target(s) in 6.11s
    ⚠️  Warning: No compatible platform tag found, using the linux tag instead. You won't be able to upload those wheels to PyPI.
    📖 Found type stub file at voicevox_core.pyi
    📦 Built wheel for abi3 Python ≥ 3.8 to /home/ryo/src/github.com/VOICEVOX/voicevox_core/target/wheels/voicevox_core_py-0.0.0-cp38-abi3-linux_x86_64.whl
    ```

このうち1., 2., 3.についてはworkspace-hackすれば統一できると思います。

4.については`open_jtalk-sys`が再ビルドを免れて`onnxruntime-sys`が再ビルドされてしまう理由がよくわかりません。ただなんとかできそうな理由である気がします。
(ちなみにmaturinが[こんなこと](https://github.com/PyO3/maturin/blob/v0.13.2/src/source_distribution.rs#L63)をしているため、`onnxruntime-sys`をどうにかしても`voicevox_core`は多分再ビルドされます)

以上より[こういうツール](https://crates.io/crates/cargo-hakari)でworkspace-hackしつつ `onnxruntime-sys`をなんとかして再ビルドされないようにすれば、`cargo build`の時間に影響するのは`pyo3`の追加によるbloatのみになると思います。

**Comment by Hiroshiba** [comment]
これは多分完成しているはず！　なのでクローズしたいと思います！
