### ISSUE TITLE
full_context_label.rsのPhonemeをメンテナンスしやすい形にする

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_core#216]
## 内容
https://github.com/VOICEVOX/voicevox_core/blob/main/crates/voicevox_core/src/engine/full_context_label.rs#L24-L82 の Phonemeが現在HashMapでデータを持っており、またそのkey名が 何を指しているかわかりにくい (p3やf1といったものを初見の人が見て意味がわかるかというと多分Noなので・・・)
そこで open_jtalk のドキュメントを読み込み、それらの短いkeyが何を指しているか調べ、それを元に適切なfield名に変更する
必要ならrustdocなどで補足説明を記載する
またHashMapはアクセスする際にパフォーマンスが悪いので他のstructと同様にfieldにする。
さらに数値にできそうなfieldについては文字列ではなく数値にする

## Pros
- field名がわかりやすくなりメンテしやすくなる
- struct field化することにより実行時のパフォーマンスが向上する
## Cons
ないはず

## その他
@Hiroshiba まえに教えてもらったopen_jtalkのドキュメントへのリンク、ちょっと今出てこないのでもし知ってたらリンク貼ってもらえると助かります

**Comment by Hiroshiba** [comment]
たぶんopenjtalkではなく、HTSのフルコンテキストラベルのドキュメントだと思います！
引っ張ってきました、こちらです。

HTSのページからダウンロードできる配布物の中にフォーマットが書かれてます。
[http://hts.sp.nitech.ac.jp/?Download](http://hts.sp.nitech.ac.jp/?Download)の`HTS-2.3`の`Japanese tar.bz2 (126 MB)`をダウンロードして、`data/lab_format.pdf`を見るとリストが見つかります。

**Comment by qryxip** [comment]
#742 により解決。
