### ISSUE TITLE
AudioQueryを出力するAPIと、AudioQueryから音声合成するAPIを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#221]
## 内容

VOICEVOXの音声合成は、テキストからいきなり音声を生成するパターンと、いったんAudioQueryというのを介するパターンがあります。
ユーザーはAudioQueryを編集することで、イントネーションや話速を変えられるという仕組みです。

エンジンではどちらも実装しているのですが、コア側はまた後者を実装できていません。
このissueは、AudioQueryの入出力を可能にするを実装するのが目的です。

### Pros 良くなる点

音声を良い感じに編集できる。
エンジンで行っている処理をコアに移動できるようになる。（高速化）

### 実現方法

AudioQueryをどう返すのかが一番難しいと思います。
可変長の情報を返す必要があるので、structで返すのも難しいはずです。

特に思いつかなければ、エンジンと同じくjsonでやり取りするのが良いのかなと思っています。

## その他

ちなみにエンジン側の、AudioQueryを返す処理は[ここ](https://github.com/VOICEVOX/voicevox_engine/blob/e2f80ab2c772492712712f9ba508c48d02383efe/run.py#L129)、AudioQueryから音声合成する処理は[ここ](https://github.com/VOICEVOX/voicevox_engine/blob/e2f80ab2c772492712712f9ba508c48d02383efe/run.py#L290)です。

**Comment by Sy-Yamaguchi-cat** [comment]
> 特に思いつかなければ、エンジンと同じくjsonでやり取りするのが良いのかなと思っています。

jsonは文字列なので、結局ライブラリ側でreleaseしないといけないのは変わらないと思います。

**Comment by Segu-g** [comment]
> 特に思いつかなければ、エンジンと同じくjsonでやり取りするのが良いのかなと思っています。

jsonも文字列で可変長なので動的ライブラリ側でreleaseしないといけないのは変わらないと思います.
（垢間違えちゃったので再投稿です）

**Comment by Hiroshiba** [comment]
releaseしないといけないのは確かに･･･。

**Comment by PickledChair** [comment]
確かに json でやりとりする場合も、wav の場合と同様に release 用の API を用意する必要はありますね……。ただし、json 文字列の方がただの線形なデータである分、ネストした構造体のようなものを扱うよりは取り扱いが楽になりそうです（単純に malloc / free の呼び出しを対にすれば良い）。個人的には提案通り json でまず実装してみるのが良い気がしています。

**Comment by qwerty2501** [comment]
json文字列でのやりとりはreleaseしなければならないのはもちろん、jsonのオブジェクト構造の説明が関数の説明を書いた程度ではされないというのはネックといえばネックですかね。ガッツリ書いた場合でも変更入った場合の追従がわりと辛いかもというのはあります。

**Comment by PickledChair** [comment]
> jsonのオブジェクト構造の説明が関数の説明を書いた程度ではされないというのはネック

これは確かにそうですね……。json を使うとして、特に工夫しない場合、コアライブラリの利用者がまず入力テキストに対するデフォルトの AudioQuery を取得する API を叩いて、自分で json オブジェクトの構造を調べる必要がありそうです。

一方、現状のエンジンの方では、ドキュメント (localhost:50021/docs) を開けば AudioQuery の構造が説明されています。json の構造についてはこちらを参照するように案内するという手はありそうです。

<img width="692" alt="audio_query_desc" src="https://user-images.githubusercontent.com/41382894/183435588-602ffe67-6f22-4175-98f3-3b5032f3b9cf.png">

json 以外だと Opaque 構造体等の別の表現も考えられそうでしょうか。query 編集のための API がうまく設計できれば、query の構造の変更には強くなると思います。（頑張れば）可変長データも扱えそうな気がしますが……。また、結局そのような AudioQuery の表現からさらに json 文字列を encode / decode できるような API も用意すると利便性が増しそうです（なければライブラリユーザーに AudioQuery から各データの取得 & json 文字列構築を任せることになる）。

ちょっとまだ考慮不足があるかもしれませんが、とりあえず以上をまとめると、json とそれ以外では、実装の難易度の観点からは前者の方が簡単そうですが、AudioQuery の構造の説明を実装に追従させる必要があります。一方、後者は実装が難しくなりそうですが、API がうまく設計できればユーザーの利便性が増しそうです。ただし、設計がまずければむしろ使いづらくなる可能性もあるかもです。

**Comment by qwerty2501** [comment]
> json 以外だと Opaque 構造体等の別の表現も考えられそうでしょうか。

wrapper作る側だとOpaque 構造体のほうが嬉しいんじゃないでしょうか。

> また、結局そのような AudioQuery の表現からさらに json 文字列を encode / decode できるような API も用意すると利便性が増しそうです

これをつくるのに労力を割くのであれば、各言語向けのwrapperを作ったほうが良いのではないでしょうか？
wrapperをつくればAudioQueryを各言語の自然な形でアクセスさせることができると思います。


個人的にはjson文字列のやり取りをするよりかはwrapperを作って各言語で自然な形にアクセスできるようにする方向に舵を切ったほうが良いと思ってます。
Opaque structの内部実装の難易度についても型変換を適切に行えるかどうかで、あとは量の問題だと思います

Opaque structでのConsとしては関数名がやたら長いのが定義されまくることでしょうか

**Comment by Hiroshiba** [comment]
wrapperだと厳密に動くけど用意とメンテが大変（かもしれない）、
jsonだと用意は簡単だけど厳密性が難しい、という感じでしょうか。

ゴールをちょっと考えたのですが、「エンジン（python）から使えることが最優先」かなと思いました。
これだと、実装はjsonでもwrapperでもどっちも良さそうです。

ゴールの２番めが「色んな人に使ってもらうこと」かなと思いました。
となると、いろんな言語のwrapperが必要になってくるので、おそらくjsonのほうが簡単そうです。

まあでも、せっかくなのでwrapperに挑戦してみたい気もします。
メンテナンスが可能で、かつそこそこ容易に実装できそうであれば、とりあえずpython wrapperを作ってみるのはどうでしょう。

jsonの方も、厳密性を確保しなければ、そんなに実装・メンテナンス難度ともに高くなさそうなので、こっちもやっちゃって良い気がしました。
なので、どっちでもOKだし、どっちもあって良さそうだなという所感です。

**Comment by qwerty2501** [comment]
確かにとりあえず使えるようにすることを目的にするのであればjsonの方が良いかもです

**Comment by qwerty2501** [comment]
ただ私としてもwrapperにしてみてどの程度のものになるのかというのは気になっているのでwrapperからやってみるというのもいいですね。

> ゴールの２番めが「色んな人に使ってもらうこと」かなと思いました。
となると、いろんな言語のwrapperが必要になってくるので、おそらくjsonのほうが簡単そうです。

ここの認識ちょっと違っていて、 jsonで提供した場合 `色んな人に使ってもらう`  状態にならないのではないかと考えてます。
各種言語のwrapperが提供されてようやく `色んな人に使ってもらえる` のかなと。
使う側が楽なのは圧倒的にwrapperです。
まあ各種言語でのwrapperを作る際でもOpaque structで提供するよりもjsonで提供したほうがwrapperを作りやすいという可能性もありそうなのでもしかしたらjsonで提供するのが正解かもしれません。
ひとまず Opaque struct方式でやる前提のAudioQueryに関するc_exportのみの実装とjson方式のc_exportのみの実装を比較のために２つDraft PRしてみてこういう定義になるんだという把握をしてみたほうがいいかもしれません。その上でAPIがややこしく感じるならjsonを受け渡すAPIに転換するとか。
Opaque struct方式だと定義される関数の数がjson方式と比べてかなりのものになりそうなので結局jsonになるという可能性は結構高いかもです

**Comment by shigobu** [comment]
win32APIで文字列を取得する関数でよく見かける手法は、文字列バッファとバッファサイズを受け取り、そこへ格納するものです。
そうすると、メモリの確保と解放は関数呼び出し元で行うので、メモリ解放の関数を用意する必要は無くなります。
例えば「[GetPrivateProfileString ](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestring)」関数がその手法を使っています。

メモリ管理のしやすさに関しては、この手法のほうが良いです。

ただ、この手法は呼び出し元が、十分な長さのメモリ(配列等)を確保する必要があり、足りない場合はエラーか不十分な内容が返されることになります。

**Comment by Hiroshiba** [comment]
@qwerty2501 
> ここの認識ちょっと違っていて、 jsonで提供した場合 色んな人に使ってもらう 状態にならないのではないかと考えてます。

確かにjsonだけで提供した場合、動的ライブラリを読み込むというすごい手間が発生するので `色んな人に使ってもらう` は満たせない気がしました。
json出力にしちゃってそれを良い感じに解釈するwrapperを作る方針も良さそうに思いました。


@shigobu 
> 文字列バッファとバッファサイズを引数で受け取り、文字列バッファへ格納するものです。

この方針も一瞬考えたのですが、長さだけど計算する方法がたぶん無いんですよね･･･。
まあテキストからAudioQueryを作るのは即座なので、長さ計算と格納で同じ処理を２回やっても別にいいのですが、うーんっていう感じです。

**Comment by qwerty2501** [comment]
現状ttsの方はwav用のメモリ領域をライブラリ側で確保するようにしてるので `AudioQuery` をユーザー側で確保してもらうようにする方式にする場合振る舞いの一貫性がなくなってしまいます。
もし仮に `AudioQuery` の長さを計算して自前で確保してもらうようにする場合ttsの方も変えたほうが良さそうです。
しかしttsがライブラリ内部でメモリ領域を確保してるのはaquestalk の振る舞いに寄せてるので、変えないほうが良いということを考えると、`AudioQuery` もライブラリ側でメモリ確保して、ユーザーに使い終わったら開放してもらうようにしたほうがよいかもです

**Comment by Hiroshiba** [comment]
仕様が定まりつつあり、とりあえず実装は開始できそうだと感じたので、要議論のラベルを外したいと思います！

**Comment by qryxip** [comment]
#224 で実装。
