### ISSUE TITLE
バージョンが二重管理になってしまっている

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_core#222]
現状このリポジトリでのVERSION.txtとvoicevox_core crateの Cargo.tomlに設定されている versionでの二重管理になっているのでちょっとなんとかして揃えやすい運用にしたいという気持ちがあります。
実際の所 Cargo.tomlのバージョンは一切使われておらず、またvoicevox_coreは [crates.io](https://crates.io/) に公開しているわけではないので不要かもしれませんが。

不要だと感じたらCloseしていただいて問題ないです。

**Comment by Hiroshiba** [comment]
なんとかしたいですね･･･！

いろいろ運用してきた感じ、mainブランチにあるものはlatestか999.999.999などのバージョンにしておいて、リリースビルド時にリプレイスする運用が楽でした。
エンジンがそうなっています。
https://github.com/VOICEVOX/voicevox_engine/blob/e2f80ab2c772492712712f9ba508c48d02383efe/.github/workflows/build.yml#L697

ただこうするとgitリポジトリからインストールするときに常に999.999.999になりますね･･･。
VOICEVOX COREのgitリポジトリからcargo buildすることを想定しなければ、ブランチ戦略的にはビルド時のバージョンを信頼する運用にしたいです。。

**Comment by qwerty2501** [comment]
Windowsだとdllのバイナリ情報にバージョンが含まれていたかと思いますが、これはCargo.tomlに設定されてるバージョン情報だったりします？
その場合git cloneしたcargoをbuildすることを考慮すると、 engineとは逆に cargoの設定からversion情報を出力してあげるのがきれいなのかなとは思いました

> ブランチ戦略的にはビルド時のバージョンを信頼する運用にしたいかなぁ･･･。

これをしたいモチベーションはなんでしょうか？

**Comment by Hiroshiba** [comment]
モチベは、管理コストを削減できるためです。

OSSの場合、バージョンごとにgit tagを打つのが通例なのですが、tomlに書く場合は別途tagにも同じバージョン情報を書く必要があります。
また、同タイミングでバージョンを更新するPRが来たときに指揮を取ったり、逆にファイル内のバージョンを上げるためだけのPRを作ってマージしたりする必要が出てきます。
実際、tagは更新したけどファイル内のバージョン更新忘れてたということが何度かあり、管理コスト削減のため、最近はこの方針を取っています。

**Comment by qwerty2501** [comment]
それは見やすい位置にバージョン情報があると間違えにくいからということであってます？
仮の話ですがもしリリースを自動化できるようなスクリプトを作ることができたのならCargo.tomlで管理しても読み取ることができれば問題ないのではないでしょうか？

と思ったのですがリポジトリ内で管理されている VERSION.txtは 0.0.1となっており、こっちも使用されていないのでしょうか？

**Comment by Hiroshiba** [comment]
> それは見やすい位置にバージョン情報があると間違えにくいからということであってます？

いえ、tomlとtagで２回設定する必要がないのと、バージョンアップ時にコードを修正する必要がないから間違いにくい感じです。
（確認したいことがわかっておらず、頓珍漢な回答をしているかもしれません･･･）

> 仮の話ですがもしリリースを自動化できるようなスクリプトを作ることができたのならそしてCargo.tomlで管理しても読み取ることができれば問題ないのではないでしょうか？

tagを使う方針に比べると、コードの修正が必要なのが問題になります。
さっき書いたこの辺り↓の工数が発生します。

`同タイミングでバージョンを更新するPRが来たときに指揮を取ったり、逆にファイル内のバージョンを上げるためだけのPRを作ってマージしたりする必要が出てきます。`

> リポジトリ内で管理されている VERSION.txt

build時に置き換えています。
https://github.com/VOICEVOX/voicevox_core/blob/6dbf15c554ff3f155d2ad72152d8673e248100b7/.github/workflows/build_and_deploy.yml#L97
ややこしいからリポジトリ内にあるVERSION.txtは消しても良さそう･･･？

**Comment by qwerty2501** [comment]
私はずっとリポジトリ管理内にある VERSION.txtを指していたんですが、そちらは 各artifact内のVERSIONファイルを指しているような気がしたので話が噛み合っていなかったかもしれません。

tagを使う方針の利点については確かにと思いました。とりあえずはそれで良いように見えます。

> build時に置き換えています。
> https://github.com/VOICEVOX/voicevox_core/blob/6dbf15c554ff3f155d2ad72152d8673e248100b7/.github/workflows/build_and_deploy.yml#L97

置き換えているというか、環境変数から出力しているだけの処理なのでそもそもリポジトリ内の VERSION.txtには触れられてすらいないですね。私も消してしまって良さそうに思いますがこれはなんのために存在していたのでしょうか？ :thinking:

**Comment by Hiroshiba** [comment]
あ、僕はリポジトリにあるのとartifact内のとどちらも合わせて考えてしまっていました！

リポジトリ内のtxtは、以前は置き換えがなかったので使われていたのが、リリース時にtagで置き換える運用になった時に削除が検討されなかったから残ってるんだと思います。
消しちゃって良さそう。

とりあえずtoml側のバージョンはlatestか999.999.999か0.0.0とかにしておいて、リリース時にそこをtagでリプレイス、もしくはコマンド引数で指定とかの運用とかですかね👀

**Comment by qwerty2501** [comment]
Discordでやり取りした感じだとリポジトリのCargo.tomlは999.999.999にしてdeploy時にtagを元に上書きする方針になりそう

**Comment by qwerty2501** [comment]
あとリポジトリ内のVERSION.txtも消す必要がありそう

**Comment by Hiroshiba** [comment]
discordの転写

> qwerty2501 — 今日 16:08
> Rustだとビルド時に CARGO_PKG_VERSION  という環境変数でパッケージのバージョンを取得できるのでビルド前にCargo.tomlのパッケージバージョンを書き換えて CARGO_PKG_VERSION  のバージョンを返す関数があるとよいかも

**Comment by qryxip** [comment]
今 #260 が進行中ですが、仮置きのバージョンって`999.999.999`で落ち着いたんでしたっけ?
(個人的な感覚としては)`0.0.0`の方が一般的なので、こっちの選択肢も残っているんじゃないかと思います。

例えばrust-lang/rust-analyzerはCrates.ioでライブラリとしても提供されているけどリポジトリ上のバージョンは仮置きとなっている、という状態になっていますがそのバージョンは`0.0.0`です。
https://github.com/rust-lang/rust-analyzer/blob/afa374e58e0bce33b666ee83baa24f16cb486a75/crates/proc-macro-api/Cargo.toml#L3
↓
https://crates.io/crates/ra_ap_proc_macro_api

**Comment by qwerty2501** [comment]
なるほど。それでは0.0.0にしておいたほうが良さそうですね

**Comment by Hiroshiba** [comment]
0.0.0でも良いと思います！

経験則ですが、latestは最新の意味なので、一番大きなバージョンにしておくといろいろ便利でした。
たとえばマイグレーション処理をするとき、自分の今のバージョンが、保存されてるファイルのバージョンより新しいかどうかを判定しますが、0.0.0を特別扱いする必要があります。

**Comment by Hiroshiba** [comment]
でもまあマイグレーション処理くらいでしか利点を思いつかないのと、今コアはマイグレーション処理がないので、やっぱり0.0.0でも良いと思います。

**Comment by qryxip** [comment]
#259 によりVERSION.txtはもう存在せず、またバージョン周りの話をするときは別途issueを立てた方がよいためcloseします。
