### ISSUE TITLE
`initialize`を`use_gpu=true, load_all_models=true`で呼ぶと確実に失敗する

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#230]
## 不具合の内容

`initialize`を`use_gpu=true, load_all_models=true`で呼ぶと、`INTERNAL.synthesis_engine.inference_core.initialized`が`false`のままここに突入するため、onnxなどに関係なく確実にエラーになります。

https://github.com/VOICEVOX/voicevox_core/blob/18dc02d0efd94b5076d494677b714565662b6c98/crates/voicevox_core/src/internal.rs#L210

### 現象・ログ

```console
❯ git show --summary
commit 18dc02d0efd94b5076d494677b714565662b6c98 (HEAD -> main, upstream/main, upstream/HEAD)
Author: qwerty2501 <939468+qwerty2501@users.noreply.github.com>
Date:   Thu Aug 11 02:11:15 2022 +0900

    with_disable_mem_pattern を削除(C++版ではなかったコードのため) (#228)

❯ cd ./example/cpp/unix
❯ sed -i 's/\(initialize(\)false/\1true/' ./simple_tts.cpp
❯ sed -i '210s/\(.*\)\(?;\)/\1.map_err(|e| dbg!(e))\2/' ../../../crates/voicevox_core/src/internal.rs
❯ cmake --build ./build && ORT_USE_CORE=1 cargo build && cp ../../../target/debug/libcore.so ./ && ./build/simple_tts あ
Consolidate compiler generated dependencies of target simple_tts
[ 50%] Building CXX object CMakeFiles/simple_tts.dir/simple_tts.cpp.o
[100%] Linking CXX executable simple_tts
[100%] Built target simple_tts
   Compiling voicevox_core v0.1.0 (/home/ryo/src/github.com/VOICEVOX/voicevox_core/crates/voicevox_core)
    Finished dev [unoptimized + debuginfo] target(s) in 2.34s
coreの初期化中...
[crates/voicevox_core/src/internal.rs:210] e = UninitializedStatus
coreの初期化に失敗しました
```

### 再現手順

`use_gpu=true`, `load_all_models=true`で`initialize`を呼び出す

### 期待動作

`use_gpu=true`, `load_all_models=true`以外の指定のときと同様に、正常にinitializeされる

## OSの種類/ディストリ/バージョン

* Arch Linux

## その他

- [C++版でも同様の問題を抱えているように見えます](https://github.com/VOICEVOX/voicevox_core/blob/50082b69e535851a358647477bfc7b8512b43880/core/src/core.cpp)。
- まだ試してませんが、engineでも`--use_gpu --load_all_models`は出来無さそうに見えます。
- 解決策としては、`InferenceCore::decode_forward_no_check_initialized_flag`みたいなのを追加する、`decode_forward`中だけ`initialized = true`として誤魔化すといったものがあると思います。

**Comment by qryxip** [comment]
経緯: https://github.com/VOICEVOX/voicevox_core/issues/227#issuecomment-1211067956

**Comment by qwerty2501** [comment]
なるほど
`decode_forward`  がinitializedのチェックをしているが、GPU使用中にload_all_modelsするとinitiazliedがfalseになるのでエラーになるということですね。
確かinitializedの確認を `decode_forward` で行うようにしたのはRust版からなのでこれはRust版のみ起こってそうです。
Rustの標準ライブラリだとこういう場合 suffixで `unchecked` をつけることが多いので新しく関数つくるなら `decode_forward_unchecked` とかどうですかね。

**Comment by qryxip** [comment]
あれ、これは違いますか

https://github.com/VOICEVOX/voicevox_core/blob/50082b69e535851a358647477bfc7b8512b43880/core/src/core.cpp#L395-L398

> 確かinitializedの確認を decode_forward で行うようにしたのはRust版からなのでこれはRust版のみ起こってそうです。

**Comment by qryxip** [comment]
Rustの慣習的には"unchecked"は`unsafe`の健全性をユーザーに頼るという意味で使われている感覚です。`_no_check`とかならそうでもないとは思います。

> Rustの標準ライブラリだとこういう場合 suffixで unchecked をつけることが多いので新しく関数つくるなら decode_forward_unchecked とかどうですかね。

**Comment by qryxip** [comment]
今ごはん食べたので、`decode_forward_allowing_uninitialized`でPR作ってみます。

**Comment by qryxip** [comment]
あ、これ`Status`も必要なんですね。`decode_forward_with_status`にします。
