### ISSUE TITLE
APIドキュメントが欲しい

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox_core#242]
## 内容

簡易的なAPIドキュメントが欲しいです。
引数の説明や実行結果のサンプルなどが書いてあると嬉しい。

### Pros 良くなる点

ラッパーライブラリを作りやすくなる

### Cons 悪くなる点

ドキュメントを整備する必要が出てくる

### 実現方法

core.hにコメントで書いたり、docsフォルダにmdで書いたり？

## OSの種類/ディストリ/バージョン

（なし）

## その他

（なし）

**Comment by Hiroshiba** [comment]
Rustってなにかかっこいいドキュメント生成ツールみたいなのってあるんでしょうか？👀
（PythonのSphinxみたいな）

**Comment by qryxip** [comment]
Rustのでよければrustdocですかね?
<https://docs.rs/pyo3>

**Comment by qryxip** [comment]
![rustdocの例](https://user-images.githubusercontent.com/14125495/184674265-8e7aae3e-5b42-4ed8-8820-76e95ccf6b34.png)

**Comment by qwerty2501** [comment]
現在C API定義の改善を予定しており、ドキュメント化するのであればその後にしたほうが良さそうというのはあります。
https://github.com/VOICEVOX/voicevox_core/pull/217

cbindgenがコメント出力できるようですが、そのときにスタイル指定できるようでDoxyとあるようです。恐らくDoxygen?
rustdoc形式で書いておけばDoxygen形式で出してくれる可能性はありそうです。
rustdoc形式だと型などがRust文脈のものなので外から見るとやや違和感があるのでできればDoxygen形式で出せそうならDoxygen形式のほうが良いと思います。

**Comment by qwerty2501** [comment]
お、できそうですねぇ

**Comment by qwerty2501** [comment]
とりあえずAPIドキュメントは生成できるようになりました

まだ説明不足だったり、Doxygenの表示がイマイチだったりしますが
