### ISSUE TITLE
onnxruntime-rsを更新するとこちらのCargo.tomlを更新するまでCIの`Security audit`が落ちる

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#248]
## 不具合の内容

Cargo.lockの生成しなおしが失敗するため、CIの`Security audit`が失敗し続けています。

ローカルの環境でも確認できます。

```console
❯ cargo generate-lockfile
    Updating crates.io index
    Updating git repository `https://github.com/VOICEVOX/onnxruntime-rs.git`
    Updating git repository `https://github.com/VOICEVOX/open_jtalk-rs.git`
error: failed to select a version for the requirement `onnxruntime = "^0.0.30"`
candidate versions found which didn't match: 0.1.0
location searched: Git repository https://github.com/VOICEVOX/onnxruntime-rs.git
required by package `voicevox_core v0.1.0 (/home/ryo/src/github.com/VOICEVOX/voicevox_core/crates/voicevox_core)`
```

何故突然こうなったのかは謎です。

### 現象・ログ

<https://github.com/VOICEVOX/voicevox_core/actions/workflows/audit.yml>

### 再現手順

ローカルの環境で`cargo generate-lockfile`

### 期待動作

Cargo.lockをちゃんと吐き、エラー無く動作する

## OSの種類/ディストリ/バージョン

* Linux

**Comment by qryxip** [comment]
## 駄目

```toml
onnxruntime = { git = "https://github.com/VOICEVOX/onnxruntime-rs.git", version = "0.0.30" }
```

```toml
onnxruntime = { git = "https://github.com/VOICEVOX/onnxruntime-rs.git", version = "0.0.30", rev = "bee215aaf6d5e346d96e0724acd02a51f612a72e" }
```

## OK

```toml
onnxruntime = { git = "https://github.com/VOICEVOX/onnxruntime-rs.git", rev = "bee215aaf6d5e346d96e0724acd02a51f612a72e" }
```

**Comment by qwerty2501** [comment]
https://github.com/VOICEVOX/voicevox_core/pull/236　がmergeされますが、git repositoryに対するversion指定は良くないかもしれないですね。
前にversionにしましょうと話した記憶がありますがrev管理の方が良いかも？

**Comment by qryxip** [comment]
なるほど。`0.1.0`はfork元の最初期のものだと思っていたのですが、VOICEVOX/onnxruntime-rs#6 のだったんですね。

**Comment by qwerty2501** [comment]
そうですね。 もとが 0.0.xxx だったのですが今回directml対応したということでマイナーバージョン上げてます

**Comment by qryxip** [comment]
過去のCIログを見るとちょくちょく失敗してますね。`git`に対して`version`での指定をしたときの正しい(?)挙動だったんですね。

**Comment by qryxip** [comment]
てっきりbisectなりして適当なcommitを選んでくれるのかと。

**Comment by qwerty2501** [comment]
私もよしなにやってくれると思ってたんですけどね。tag打ってたら違ったかもしれないですが。
現状tag打たない方針なのでrev指定がやはり良さそうです
