### ISSUE TITLE
build_and_deploy jobにあるenvironmentは必要なのか？

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_core#267]
## 質問の内容

現在 CI上 build_and_deploy job内にある [enviornment](https://github.com/VOICEVOX/voicevox_core/blob/main/.github/workflows/build_and_deploy.yml#L29) が影響して PR上の履歴がかなり流れやすくなってしまってるようです

こんな感じに
![image](https://user-images.githubusercontent.com/939468/189484073-9f69c0a3-de1d-4074-b3f9-b08ad3229874.png)

できればこの `environment` 消したほうがいいのかなとは感じてるんですが codesign時に必要だから存在してるように見て取れます。
どこで使われてるかわからないのですがこれは必要ということでいいんでしょうか？

**Comment by Hiroshiba** [comment]
ちょっと僕もなぜ出るのかよくわかっていないのですが、falseというenvironmentができていたので消してみました。
これで収まればいったん大丈夫そう･･･？

これたしかactionsのコードを修正したほうがよくて、`environment=="hoge" && "hoge"`という形になっているのですが、このときfalseだった場合false environmentを使おうとして、これが出てるんだと思います。
Actionsのドキュメントに書いてないのですが、falseのときは空欄にすればたしか出なくなった気がします。

**Comment by Hiroshiba** [comment]
↑の課題、取り組んでみます！
