### ISSUE TITLE
C APIの関数でinitializeが必要なのか不要なのかドキュメントに書いてほしい

### ISSUE THREAD

**Issue by shigobu** [VOICEVOX/voicevox_core#276]
## 内容

C APIの関数で、使う前にInitializeを呼ぶ必要があるのか無いのかをAPIドキュメントに書いてほしいです。
個人的に.NETラッパーを作成していますが、静的関数にできるのかどうかがわからず全て静的でない関数として定義しました。

おそらく、「voicevox_get_\~」系関数と「voicevox_make_default_\~」系関数が、Initialize関数を呼ばなくても使える関数だと思います。これらの関数の説明に、「Initialize不要で使える」等の説明を書いてほしいです。
あるいは、Initialize関数の説明でもいいかもしれません。「hoo関数とbar関数はInitialize不要で使えます」みたいに。

### Pros 良くなる点

各関数のInitialize要・不要が明確になる。

### Cons 悪くなる点

ない？

### 実現方法

ドキュメントに反映されるコメントに追記する。

## その他

私が作成した.NETラッパーはこちらです。
https://github.com/shigobu/VoicevoxCoreNet

**Comment by qwerty2501** [comment]
@Hiroshiba https://github.com/VOICEVOX/voicevox_core/pull/274#issuecomment-1245419890 に関連して、これは内部で使われている `VoicevoxCore` のオブジェクト設計を C API側に反映できていないのがそもそもの原因だと思います。
恐らく簡単に扱えるために隠蔽していたと思うのですが、これが将来的にさらなる問題を引き起こす懸念はあります。
例えばC API が 内部のVoicevoxCoreを利用するものについては `voicevox_core_new` などと言った関数で初期化して、 `VoicevoxCore` オブジェクトのポインターを返すようにし、 `VocievoxCore` の機能を利用するものについてはこの `VocievoxCore` オブジェクトのポインタを受け取るようにしておけば今回のような疑問を持たれるようなこともなかったでしょう。ドキュメントで説明できていないというのはそうなのですが、そもそも説明が必要なAPI設計になってしまっているのは問題なのではないでしょうか？
今回のAPI改修では主に名前衝突がおこらないためにprefixをつけて回るのが主でしたが、まだリリース前ですのでこういったクラス設計に沿ったAPIに変えるのを行うとすれば今かなと思いました。

以上が私の意見ですがドキュメントで初期化が必要な旨が書いてあれば十分かもしれません。
いずれにせよリリースしてしまうと変えるのはしばらく難しいと思いますのでやるのかやらないのかをオーナーの方が決断したほうがよいと思います。
また変更するのであれば C API版、内部のRust版、python API版で足並みを揃える必要があると思います。

**Comment by Hiroshiba** [comment]
たしかに、initialize時に何かしらのクラスのポインタが返ってきて、それが必要な関数にはポインタを渡す設計がきれいだなと思います。
（onnxruntimeとかもそうだったと思います）

可能であれば今のうちに変えられると嬉しいです。
変更するのに時間がかかりそうであれば、ドキュメントに記載して完了でも、実用上特に問題は無いのかなと思いました。

（python API側とエンジン側にも影響が出そうなので、関係されそうな方にメンションを送ります @qryxip @PickledChair  ）

**Comment by qwerty2501** [comment]
@Hiroshiba 次のリリースいつぐらいまでにしたいですか？

**Comment by Hiroshiba** [comment]
@qwerty2501 特に決めていないのですが、Rust化が入るであろう次のマイナーバージョンアプデは･･･うーん、２ヶ月３ヶ月後とかになるかなと思っています。
ちょっと定まってないのですが、複数エンジンに合わせることになるかなという所管です。

あと質問の意図とずれてるかもなのですが、0.12→0.13と同様にまたコアRust化のリリースを遅らせて、今の0.13を0.14ということにするのも手として残っていると思います。
参考になれば･･･！

**Comment by qwerty2501** [comment]
期間的には問題なさそうですね

**Comment by qwerty2501** [comment]
クラス設計用のissueを作成しました #280
