### ISSUE TITLE
cbindgenの設定をcbindgen.tomlに移行し、CLI版のcbindgenを使う

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#282]
## 内容

cbindgenにはCLI版があり、`cargo install cbindgen`でインストールできます。build.rsからこのCLI版cbindgenに移行することを提案します。

現在voicevox\_core.hは`cargo build -p voicevox_core_c_api --features generate-c-header`という形で生成されています。 (#219)
これはもともと`cargo build`するたびに毎回生成していたのに制限を加えた形ですが、結果として見た目的に「build.rsの中にあるcbindgenを起動するためだけにわざわざクレートごと`cargo build`している」という状態になっています。

### Pros 良くなる点

- GitHub Actionsの流れがより明確になる

## OSの種類/ディストリ/バージョン

GitHub Actionsで走らせているプラットフォーム全部

## その他

CI/CD時間が増えるか減るかはわかりません。feature違いによる依存の再ビルドは減るでしょうし、`cargo install`の代わりにcargo-binstallを使えばバイナリを持ってこれるため、予想としては減るだろうと思っています。

**Comment by qwerty2501** [comment]
> build.rsの中にあるcbindgenを起動するためだけにわざわざクレートごとcargo buildしている

CI上ではC ヘッダーを出力するときはビルドあるいはテストが必要な場合なのでそこまで問題にはならないと考えてます。
また提案だとローカルでCヘッダー出力を確認したい場合にCLI版cbindgenをインストールを明示的に行う必要があるため開発参加障壁がやや上がるのがデメリットになるのではないかと考えてます。現状だとdev-dependenciesとして自動で持ってこれるため。

**Comment by qryxip** [comment]
> また提案だとローカルでCヘッダー出力を確認したい場合にCLI版cbindgenをインストールを明示的に行う必要があるため開発参加障壁がやや上がるのがデメリットになるのではないかと考えてます。現状だとdev-dependenciesとして自動で持ってこれるため。

その観点だったら[cargo-xtask](https://github.com/matklad/cargo-xtask)的な仕組みで`cargo xtask generate-c-header`という手もあるかなと思いました。こっちならcbindgen.tomlへの移行はしなくてよいです。

現在ヘッダの生成についてのドキュメントは無く、書くとしたら「`cargo check -p voicevox_core_c_api --features generate-c-header`したらtarget/voicevox_core.hができるのでそれをコピーしてください」となると思うのですが、それなら「`cargo xtask generate-c-header`してください」(あるいは「`cbindgen -c voicevox_core_c_api`してください」)の方が自然かなと思ったのが動機です。

取り回し的にも
```console
❯ cargo check -p voicevox_core_c_api --features generated-c-header && less ./target/voicevox_core.h
```
```console
❯ cargo check -p voicevox_core_c_api --features generated-c-header && cp ./target/voicevox_core.h ./example/cpp/unix/
```
よりも
```console
❯ cargo xtask generate-c-header | less
```
```console
❯ cargo xtask generate-c-header -o ./example/cpp/unix/voicevox_core.h
```
の方がシンプルかなと。

**Comment by qryxip** [comment]
`--features generate-c-header`をやめる話とは別に、cbindgenのドキュメントではどうもcbindgen.tomlを使うのが推奨されているので、その点で移行した方がよいんじゃないかとも思ってます。

**Comment by qwerty2501** [comment]
現在のコマンドが煩雑であるのはたしかにそうですね。しかし cbindgen.tomlを推奨されているというのはどのあたりをみてそう感じられたのでしょうか？

**Comment by qryxip** [comment]
cbindgen.tomlを使わずに設定を書いているサンプルコードがcbindgenのリポジトリに見当たらないことからそう思いました。

**Comment by qryxip** [comment]
一応cbindgen.tomlを使わない方法も示されているのですが、その方法でも`Config { .. }`の形ではなく[`Builder`](https://docs.rs/cbindgen/0.24/cbindgen/struct.Builder.html#methods)を使うもので、かつ`Builder`にはメソッドのdocstringが欠けているような状態です。
https://github.com/eqrion/cbindgen/blob/master/docs.md#buildrs

**Comment by qwerty2501** [comment]
なるほどそういうことならcbindgen.tomlで管理しても良いかもですね

**Comment by qryxip** [comment]
ではまずcbindgen.tomlへの移行だけでPRを出そうと思います。
