### ISSUE TITLE
[0.13.0] pip install . した core.dll に load_model が無い

### ISSUE THREAD

**Issue by raa0121** [VOICEVOX/voicevox_core#286]
## 不具合の内容

0.13.0 で `pip install .` した core.dll の中に、load_model が存在せず、エラーになる

### 現象・ログ

```
>>> import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\msys64\home\raa0121\develop\voicevox_core\example\python\.venv\lib\site-packages\core\__init__.py", line 140, in <module>
    from ._core import *
  File "C:\msys64\home\raa0121\develop\voicevox_core\example\python\.venv\lib\site-packages\core\_core.py", line 33, in <module>
    lib.load_model.argtypes = (c_int64,)
  File "F:\Python39\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "F:\Python39\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'load_model' not found
```
### 再現手順

```
git clone -b release-0.13 https://github.com/VOICEVOX/voicevox_core 
python configure.py
pip install -r requirements.txt
pip install .
python
>> import core
```

### 期待動作

エラーが発生せず、import が成功する

## OSの種類/ディストリ/バージョン

*   Windows 11 Pro 64bit (10.0.22000.978)

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
あれ、なんでこうなるんでしょう･･･？

**Comment by raa0121** [comment]
分かんないですね…
ちゃんと core.h には定義されてますしね…
export されてる関数は↓でした
```
decode_forward
finalize
initialize
last_error_message
metas
supported_devices
yukarin_s_forward
yukarin_sa_forward
```

**Comment by raa0121** [comment]
https://github.com/VOICEVOX/voicevox_core/blob/0.13.0/configure.py#L260
原因わかりました 0.10.0 がデフォで設定されてるので、古い dll を取ってくるようです

**Comment by raa0121** [comment]
0.13.0 では、core.zip を配布してないので、 configure.py をちゃんとライブラリ別の zip 対応する必要があるようです。

**Comment by Hiroshiba** [comment]
なるほどです！　configure.pyがメンテされていないという感じかもですね！
こちらが近そうに感じました。

- https://github.com/VOICEVOX/voicevox_core/issues/137

**Comment by Hiroshiba** [comment]
Rust化が完全に移行するとこの今のissueも関連issueも全て解決しそうです。
いったん、このissueはopenにしたまま案内用に残しておき、issueの積極的な解決は目指さない（迂回作だけ案内する）という方針にしたいと考えています。

**Comment by qryxip** [comment]
もう1.14はリリースされ、PyO3ベースのPython APIも出したのでもうconfigure.pyの案内も不要なのではないかと思ったのですがどうでしょうか?

**Comment by Hiroshiba** [comment]
役割を終えたのかなと思いました！！
ということでcloseします、issue作成ありがとうございました！
