### ISSUE TITLE
Rust 1.64の`workspace.{package,dependencies}`を利用する

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#287]
## 内容

Rust 1.64がリリースされました。何事もなければ明日の午前9時に #233 が作動します。

Rust 1.64では`workspace.package`と`workspace.dependencies`という指定ができるようになり、`version`や`dependencies`の共通化ができるようになります。

[Announcing Rust 1.64.0 - Cargo improvements: workspace inheritance and multi-target builds](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds)

### Pros 良くなる点

Cargo.tomlの見通しが良くなる

## OSの種類/ディストリ/バージョン

サポートしているものすべて

**Comment by Hiroshiba** [comment]
ラベル付けていただくの、もちろん大丈夫です！
付け方も個人的な感覚と相違ないです🙏
セルフアサインももちろんOKです！

ラベルの付け方もドキュメント化しなきゃですね、時間見つけて書いてみます。

**Comment by qwerty2501** [comment]
標準ライブラリで使えるようになったffiの型も増えたようなのでこれも対応したいですね

**Comment by qryxip** [comment]
今までも`std::os::raw`下にあったのですが、[「`core::ffi`を使え」](https://doc.rust-lang.org/stable/std/os/raw/index.html)とあるのでこれを機に対応してもいいと思います。

**Comment by qwerty2501** [comment]
たしかに `std::os::raw` の説明にはcore::ffi使えとありますがstd::ffiとcore::ffiはどっち使うべきなんでしょうね

**Comment by qryxip** [comment]
このissue、`初心者歓迎タスク`を付けてしまいましたがこれをなんとかする必要がありますね。
https://github.com/VOICEVOX/voicevox_core/blob/01c837195882dc32932e101d3e8e9db27d01b1bc/.github/workflows/build_and_deploy.yml#L94-L100

これを待ってからcargo-editをbinstallしてそれを使うのがいいかも?
https://github.com/killercup/cargo-edit/pull/814

**Comment by qwerty2501** [comment]
リリース戦略をどうするかによりますが、すべて一緒にリリースする戦略ならworkspaceで一括更新できるようにしたほうが良いので待ったほうが良さそうですね

**Comment by qryxip** [comment]
cargo-editですがPRがマージされてv0.11.4が出たみたいですね。binstallもできそうです。
https://github.com/killercup/cargo-edit/releases/tag/v0.11.4
https://github.com/alsuren/cargo-quickinstall/releases?q=cargo-edit-0.11.4&expanded=true
