### ISSUE TITLE
Deps.rsのバッジをREADMEに貼る

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#289]
## 内容

→をREADMEに貼ります。 [![dependency status](https://deps.rs/repo/github/VOICEVOX/voicevox_core/status.svg)](https://deps.rs/repo/github/VOICEVOX/voicevox_core)

Dependabotもいいとは思うのですが多分うるさくなると思います。
ライブラリのどれかがメジャーアップデートされてバッジが黄色くなったタイミングで他のライブラリのマイナーアップデートと一緒に誰かが更新のPR、というのがちょうどいいのではないかと思いました。

### Pros 良くなる点

- ライブラリをアップデートすべきタイミングをほどほどに知ることができる

### Cons 悪くなる点

- READMEの場所を取る

## OSの種類/ディストリ/バージョン

N/A

**Comment by Hiroshiba** [comment]
良いと思います！

正直バッチがあってもなくてもユーザーの増減には関わらなさそうなのですが、ちょっと試してみるのも面白いかなと思いました！
