### ISSUE TITLE
C APIと同様に、Python APIのドキュメントを生成する

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#294]
## 内容

Python APIのdocstringを書き、Sphinxか何かでドキュメントを生成します。

### Pros 良くなる点

- Python APIの使い方がわかりやすくなる

### Cons 悪くなる点

- メンテコスト

## OSの種類/ディストリ/バージョン

サポートしているもの全部

**Comment by qryxip** [comment]
![image](https://user-images.githubusercontent.com/14125495/200177528-59da41ab-bdfc-4445-aafe-f4b5ebeec1db.png)
![image](https://user-images.githubusercontent.com/14125495/200177588-0059ceb9-84da-46be-99c0-867df7b1e247.png)

**Comment by Hiroshiba** [comment]
あ、あとgithub pagesで２つをいい感じに見れるようにするための設定もなにか必要かもですね･･･！
