### ISSUE TITLE
thiserrorをアップデートするとビルドが通らなくなる

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#297]
## 不具合の内容

https://github.com/dtolnay/thiserror/commit/c81dc6731b9578326dcc945b067c9d78ffa3f847 により、thiserror v1.0.33から`thiserror::private::AsDynError`が`thiserror::__private::AsDynError`にリネームされているためこのままthiserrorをアップデートするとビルドが通らなくなります。

### 再現手順

```console
❯ cargo update -p thiserror && cargo check -p voicevox_core
```

### 期待動作

thiserrorを最新版に上げてもビルドが通るようになる

## OSの種類/ディストリ/バージョン

全部

## その他

対応としては次の4つがあると思います。

1. thiserrorをv1.0.33以降にアップデートすると同時に`thiserror::__private::AsDynError`を使うようにする
2. `AsDynError`ではなく、`Deref<anyhow::Error>`を`SourceError`にimplする
3. `SourceError`を`std::error::Error`にして、他のエラーからの変換は明示的に行うようにする
4. `SourceError`を削除して`anyhow::Error`を直接使うようにする (`voicevox_core::Error`の`PartialEq`は手で書く)

**Comment by qwerty2501** [comment]
2か4ですかね
