### ISSUE TITLE
metas情報を返すようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#30]
## 内容

コアの機能の１つに、話者やスタイルの情報をjson形式で返すというものがあります。
https://github.com/Hiroshiba/voicevox_core/blob/f59c6fbe20f248a094afbe717a4c1127ed5ceb96/core.h#L42

こんな感じのjsonです。
```json
[
  {
    "name": "話者１",
    "styles": [{ "name": "ノーマル", "id": 0 }],
    "speaker_uuid": "uuid1",
    "version": "X.X.X"
  },
  {
    "name": "話者２",
    "styles": [{ "name": "ノーマル", "id": 1 }],
    "speaker_uuid": "uuid2",
    "version": "X.X.X"
  }
]
```

### 実現方法

initializeで与えられたroot_dirの下にあるmetas.jsonを読み込んで返す、というのが良いと思っています。
https://github.com/Hiroshiba/voicevox_core/blob/f59c6fbe20f248a094afbe717a4c1127ed5ceb96/onnx/core.cpp#L60

こうすることで、ディレクトリの指定を変えるだけで別のコアを読み込めるためです。

**Comment by Yosshi999** [comment]
返すJSONがvalidであることを保証するかどうかで実装の重さが変わりそうですね。metas.jsonが壊れててもそのまま返してしまって良いのならテキスト読み込みだけで済みそうです

**Comment by Yosshi999** [comment]
header onlyなjsonパーサ（MIT License)
https://github.com/nlohmann/json/tree/develop/single_include

**Comment by Yosshi999** [comment]
せっかくヘッダオンリーなのでそのままファイルを持ってきてしまうという手もあります（ライセンス表記もソースコードに埋まってます）

**Comment by Hiroshiba** [comment]
ヘッダーをコピペするとバージョンアップが大変かなと思いましたが、まあ気が向いた時に上げれば良い気がしました。良さそうです！！

ライセンス表記の意図は、ソースに埋まっているからユーザーに案内しなくても良いと言う意図でしょうか。
であればコンパイルしたら消えてしまうので、たしか別途ユーザーに案内する必要があるはずです。
