### ISSUE TITLE
ONNX モデルの入出力に関するドキュメント

### ISSUE THREAD

**Issue by dhgrs** [VOICEVOX/voicevox_core#300]
## 質問の内容

VOICEVOX CORE をビルドするために必要な ONNX モデルの入出力に関するドキュメントはどこかにありますか? 今のところ見つけられた情報として https://github.com/Hiroshiba/vv_core_inference/tree/14b85deada7952cecb2e2d8a5ec6f4f9c27e03cb/vv_core_inference にある `make_*_forwarder.py` で ONNX モデルを export している例があるので、入出力の変数名まではすぐに分かりましたが、例えば次に具体例をいくつか挙げるような詳細は各コードを細かく見に行く必要があり、すぐには分かりませんでした。

- f0 や length の単位
    - 特に f0 は VOICEVOX EDITOR で上下限が設定されていると思いますが、 decode.onnx に渡されるときは本当にクリップされているのか、内部的には (UI から操作しない限り) predict_intonation.onnx の出力がそのまま使われるのか、などのモデル学習時に注意が必要そうな情報が分かると良いと思います
- サンプリング周波数をどこで設定するか

こういった ONNX モデルを作るのに必要な入出力に関する情報はどこかにありますか? ある場合は、こちらのリポジトリから情報にたどり着ける方が良いと思うので、ドキュメントを追加する PR を作成予定です。ない場合は、欲しい情報をリストアップしたら回答いただけますか?

## OSの種類/ディストリ/バージョン

今回はドキュメントに関する質問のため、省略

## その他

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
モデルの入出力となるデータのドキュメントは用意しておらず、`vv_core_inference`を見るのが一番近道になっています。

> f0

F0の自然対数です。例えば440Hzだと6.086です。無声のときはf0=0にしています。

> length

秒です。

> サンプリング周波数をどこで設定するか

モデルはサンプリング周波数のデータを持っていなくて、エンジン側で差し込んでいます。

**Comment by dhgrs** [comment]
回答ありがとうございます。

ドキュメント更新の PR を作る予定なので、関連する質問をする場所としてこちらの issue を使うつもりですが、別のところ (適当なドラフト PR を作って、そことか?) が都合良ければお伝えください。

早速質問です。

- このリポジトリへの変更は「自分で作ったモデルを組み込みたい場合は vv_core_inference を参照してください」と案内するに留めて、詳細は vv_core_inference で整備していくのが良いと思っています。この方針で問題ないでしょうか?
- decode に渡す f0 と phoneme は波形と同じ sampling rate にリサンプリングされるが、これもエンジンかコアで行われるのでしょうか?
    - Gaussian upsampling を使ってみたく、その場合リサンプリングも decode 内でやりたいが、できるのか確認したい意図です
- decode だけ `Phoneme` が `JvsPhoneme` で他は `OjtPhoneme` のようですが、これは変更可能ですか?
- decode だけ音素が onehot で表現されていますが、他と異なる理由はありますか?
    - 今回のドキュメント化には直接関係なく、そういうもの、としてしまえば良いだけですが、気になりました

最近の画像生成の盛り上がりを見ていて、音声系でも新しいモデルを簡単に VOICEVOX の UI で試せると良いなと思って、ドキュメントやコードを整備できればと思っています。 (自分も生放送でコメントした通り WaveGrad 2 を試してみたいと思っています)

**Comment by Hiroshiba** [comment]
> ドキュメント更新の PR を作る予定なので、関連する質問をする場所としてこちらの issue を使うつもりですが、別のところ (適当なドラフト PR を作って、そことか?) が都合良ければお伝えください。

特に決まりはないのですが、いったんこちらでお願いします！

> このリポジトリへの変更は「自分で作ったモデルを組み込みたい場合は vv_core_inference を参照してください」と案内するに留めて、詳細は vv_core_inference で整備していくのが良いと思っています。この方針で問題ないでしょうか?

なるほどです！！
コアはonnxモデルのラッパーという感じなので、この方針がとても良さそうに感じました。

> decode に渡す f0 と phoneme は波形と同じ sampling rate にリサンプリングされるが、これもエンジンかコアで行われるのでしょうか?

まず認識合わせなのですが、decodeに渡すf0とphonemeは波形と同じサンプリングレートになっていません。
今のVOICEVOXコアの場合、f0とphonemeは100Hzで、波形は24kHzです。

今は、duration出力（yukarin_sモデル）は音素単位、f0出力（yukarin_saモデル）はモーラ単位で、これをコアやエンジン側で長さのつじつまを合わせてdecodeに渡しています。
エンジンのSynthesisEngineクラスがわかりやすいと思います。
https://github.com/VOICEVOX/voicevox_engine/blob/7421f7b996461c9832af8bc2ee56b70ff81976bd/voicevox_engine/synthesis_engine/synthesis_engine.py#L130

今はそのdecodeに入力するf0やphonemeの長さ合わせをエンジンやコアで行っているので、Gaussian upsamplingをdecode内でやるにはそのコードを専用に書き換える必要がありそうに思いました！

> decode だけ Phoneme が JvsPhoneme で他は OjtPhoneme のようですが、これは変更可能ですか?
> decode だけ音素が onehot で表現されていますが、他と異なる理由はありますか?

モデルの作成（学習）に合わせればなんでもOKだと思います。
変更可能というのが何を意図するのか若干わかっておらず、回答が不正確かもです。

あれ、VOICEVOXは現状だと全てOjtPhonemeなはずです。
もしかしたら今のvv_core_inferenceは僕が手元で運用しているものより少しバージョンが古いかも知れません･･･。

> 最近の画像生成の盛り上がりを見ていて、音声系でも新しいモデルを簡単に VOICEVOX の UI で試せると良いなと思って、ドキュメントやコードを整備できればと思っています。

なるほどです！楽しそうです。

**Comment by dhgrs** [comment]
> まず認識合わせなのですが、decodeに渡すf0とphonemeは波形と同じサンプリングレートになっていません。

vv_core_inference でもそうでした。リサンプリングが入っていたことで、波形と同じだと思い込んでいました。失礼しました。

> 今のVOICEVOXコアの場合、f0とphonemeは100Hzで、波形は24kHzです。

以下を見ていると、およそ 100Hz ですが 24000/256=93.75Hz がより正確だと思いました。
https://github.com/Hiroshiba/vv_core_inference/blob/14b85deada7952cecb2e2d8a5ec6f4f9c27e03cb/vv_core_inference/forwarder.py#L183-L184
https://github.com/VOICEVOX/voicevox_engine/blob/7421f7b996461c9832af8bc2ee56b70ff81976bd/voicevox_engine/synthesis_engine/synthesis_engine.py#L464-L465

もし間違っていたらご指摘ください。 (vocoder が HiFiGAN っぽいので多分 256 倍アップサンプリングして波形と同じサンプリング周波数になるのが正しいと思いますが、念の為)

> 変更可能というのが何を意図するのか若干わかっておらず、回答が不正確かもです。

仮に、エンジン側が JvsPhoneme のみに対応していると OjtPhoneme で学習したモデルは動かない可能性があります。そのため、エンジンの設定ファイル等で Phoneme の種類を変えられるのか、エンジンのコードの変更が必要になるのか、どちらか知りたかったというのが質問の意図です。

現在はエンジン側などは OjtPhoneme で動いているので、それ以外 (JvsPhoneme) を使うときは ONNX に加えてソースコードの変更が必要と理解しました。

ちなみに、以下の部分の条件分岐を読み誤って、 JvsPhoneme に変換していると勘違いしていました。

https://github.com/Hiroshiba/vv_core_inference/blob/14b85deada7952cecb2e2d8a5ec6f4f9c27e03cb/vv_core_inference/forwarder.py#L162-L174

**Comment by Hiroshiba** [comment]
> 以下を見ていると、およそ 100Hz ですが 24000/256=93.75Hz がより正確だと思いました。

あっすみません、仰るとおりです！

> エンジンの設定ファイル等で Phoneme の種類を変えられるのか

こちらもなるほどです。
ちなみに現状は外部から音素情報を変更するのは不可能ですが、もちろん設定を渡せるようにすればいいだけなので、改変は簡単だと思います。

ちなみにOjtPhonemeだとROHAN4600コーパスの音素を網羅できていません･･･。
VOICEVOXでは現状OjtPhonemeには無いものはそれっぽい音素ラベルに置き換えて学習しています。

一応RohanPhonemeというのも用意してはいます。参考になれば幸いです。
https://github.com/Hiroshiba/acoustic_feature_extractor/blob/d450b25be86a338c543b701b49972096786c74a8/acoustic_feature_extractor/data/phoneme.py#L278

**Comment by dhgrs** [comment]
学習を開始する前に、入出力のサイズが一致する ONNX を吐き出せることを目標にコードを書いています。その際に問題になった点を追加で質問させてください。

### 実装の確認

ONNX では入出力に key (name) を持たせることができますが、 core では key を使わずに、入力順によって ONNX の入力と実際に与える入力の対応関係をとっています。

https://github.com/VOICEVOX/voicevox_core/blob/084bf63df6824922d398ae49668aa619f2517843/crates/voicevox_core/src/publish.rs#L120-L143

### PyTorch/ONNX の仕様の確認

`torch.onnx.export` で出力する際にどこにもつながっていない入力ノードは、たとえ name を明示的に与えても省略して消されることを `pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime` のイメージで確認しています。 (ドキュメントの記載を見つけられなかったので、ここの確証をとりたい場合は、なるべく小さな再現スクリプトを作るのでコメントください)

### 問題点

core が想定している入力の一部を使わないモデルを考えると、 core が動かそうとした際に引数が多いとエラーを吐くことが予想されます。つまり core 互換性のある ONNX を吐き出せなくなります。これは実際に起こり得るケースで、例えば先ほどの例の length は PyTorch 上で `vowel_phoneme_vector.size(-1)` とかすると取れるので使わないことが考えられます。

個人的には length と、単話者モデルの場合の speaker id は使わない可能性があるので、問題になりがちだと思います。

### 質問

- `torch.onnx.export` あるいはその他の関数で計算グラフがつながっていないノードを残す方法をご存知ですか?
- `predict_intonation` が length を要求する理由はなんでしょうか?
    - speaker id の問題は依然として残りますが、一旦 length 側だけでも解決できると嬉しいので、変更の可能性があるか確認したい意図です
    - 変更点に加えて得られるメリットがモデル開発者が楽になるだけなので、仮に length が要らないとしてもわざわざ修正するかという問題はあると思いますが...

**Comment by Hiroshiba** [comment]
> `torch.onnx.export` あるいはその他の関数で計算グラフがつながっていないノードを残す方法をご存知ですか?

実はonnxに全く明るくないのでわかりません･･･。
@Yosshi999 さんならわかるかも･･･？

> predict_intonation が length を要求する理由はなんでしょうか?

バッチサイズ２以上でも推論可能にしていた名残りです。
でもたしかdecodeはバッチサイズ１のみ対応になっているので、`predict_intonation`がlengthを受け取れる意味はほぼないですね･･･。

---

ちなみにonnxへの入力をkey & value形式で与える場合は、入力をoptionalにすることが可能なのでしょうか。
であれば、その形に変更するのは問題ではないのかなと思いました。

（本来は過去のonnxが読めるよう互換性も気にしないとなのですが、今はまだonnxモデル自体を配布していないので破壊的変更が可能なはずです）

**Comment by dhgrs** [comment]
> 試してはいませんが適当にそのノードに0をかけてどこかで加算すると消えなくなるかもしれません（あまりいい方法ではないですね）

この方法で消えないことは確認できました。おっしゃるように、事情を知らない人にとって意味のない演算が追加されているように見えるので、あまり良い方法ではないと思います。もし可能なら、提案いただいたように core 側で対応していただくのがスマートだと思います。

ただ、私に Rust の経験がないので今すぐに対応 PR を出すことは難しそうなので、一旦この状況を作成予定のドキュメントに書いて注意喚起するに留めようかと思います。 (もちろん、もし対応していただける方がいれば助かります)

**Comment by dhgrs** [comment]
3 週間以上アップデートをしていなかったので、簡単に現状を共有させてください。

- PyTorch の `torch.nn.Module` で (学習途中で低品質ながら) 合成が可能になった
    - タスク的に難しい intonation predictor と decoder は diffusion model で試しています
- 各モジュールが出力する ONNX が https://github.com/VOICEVOX/voicevox_core/blob/main/model/ 以下にある ONNX と入出力の shape, type などの情報が一致する

まだ自作 ONNX を使って VOICEVOX のビルドを試して品質確認はできていないため、 PyTorch の `torch.nn.Module` での動作確認時にモジュール間のつなぎこみでバグ (というか VOICEVOX と違う挙動) を埋め込んでいる可能性があるので、ドキュメントの整備などしつつ、確認していこうと思います。

**Comment by Hiroshiba** [comment]
ご報告感謝です！！
ドキュメント整備しつつ繋ぎこみミスの防止、とても素晴らしいと思います！！！

> タスク的に難しい intonation predictor と decoder は diffusion model で試しています

こちらもすごく結果が楽しみですね！！！
decoderはモデル的に大きくなりそうなのでdiffusionベースは厳しいと感じているのですが、イントネーションだけならかなり現実的なのかなと思いました。
いつかディスカッションできると嬉しいです！！！
