### ISSUE TITLE
（DirectML環境で）一番良いGPUを自動選択・GPUを選択可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#309]
## 内容

オンボードのGPUと外付けのGPUがある場合、たいていはオンボード側がGPU 0版に設定されており、そのままDirectMLを使うとそのオンボードのGPU（弱い方）が利用されます。
これを、より強い方を自動的に使うようにしたいかもしれません。

が、GPUが２枚あり、片方をゲーム用、もう片方をそれ以外用と使い分けてる人もいそうなので、選択可能にもなっていると嬉しそうです。

ユーザーの声
https://twitter.com/nusu_fkr453145/status/1566069300548341761
https://twitter.com/kfd_karimanasan/status/1581287406539771909

### Pros 良くなる点

強いGPUで音声合成できる

### Cons 悪くなる点

アプデすると利用するGPUが勝手に変わる人もいる

### 実現方法

一番いいGPUの選び方が不明･･･。
利用可能なGPU一覧を取って（CUDAだとオンボードGPUは使えないことが多い）、メモリが多い方を使う･･･とか？

**Comment by Hiroshiba** [comment]
メモリはこの方法で取れるっぽい？　(thx @qryxip ！）

> [ORTのドキュメント](https://github.com/microsoft/onnxruntime-openenclave/blob/openenclave-public/docs/execution_providers/DirectML-ExecutionProvider.md#ortsessionoptionsappendexecutionprovider_dml-function)によると、
> これ↓の配列が取れるっぽいのであとはこれをどう扱うかですね
> https://learn.microsoft.com/en-us/windows/win32/api/dxgi/ns-dxgi-dxgi_adapter_desc

**Comment by Hiroshiba** [comment]
NVIDIA 製の GPU を搭載しているノート PC でCPU 内蔵のグラフィックス機能とGPUを切り替える技術はNVIDIA Optimusと呼ばれるそうです。
ゲームとかだと強い方のGPUが使われてるはずなので方法調べてみました。

まず、ユーザー側で手動で設定することは可能そうでした。
http://faq3.dospara.co.jp/faq/show/1577?site_domain=default

VOICEVOX側で自動で乗っかるにはこの資料が役立ちそう？

Enabling High Performance Graphics Rendering on Optimus Systems
https://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf

中身によると、特定のライブラリがある場合に強いGPUが選ばれそう。

> For any application without an existing application profile, there is a set of libraries which, when statically linked to a given application executable, will direct the Optimus driver to render the application using High Performance Graphics. As of Release 302, the current list of libraries are `vcamp110.dll, vcamp110d.dll, nvapi.dll, nvapi64.dll, opencl.dll, nvcuda.dll, and cudart*.*.`.
> 既存のアプリケーション・プロファイルを持たないアプリケーションには、ライブラリのセットがあり、所定のアプリケーション実行ファイルに静的にリンクされると、Optimusドライバにハイパフォーマンスグラフィックスを使用してアプリケーションをレンダリングするよう指示します。リリース302の時点で、ライブラリの現在のリストは、`vcamp110.dll, vcamp110d.dll, nvapi.dll, nvapi64.dll, opencl.dll, nvcuda.dll, and cudart*.*.`です。

バイナリ側で制御するにはグローバル変数を指定すると良いっぽい･･････？

> Starting with the Release 302 drivers, application developers can direct the Optimus driver at runtime to use the High Performance Graphics to render any application–even those applications for which there is no existing application profile. They can do this by exporting a global variable named NvOptimusEnablement.
> Release 302 ドライバから、アプリケーション開発者はランタイム時に Optimus ドライバに指示して、既存のアプリケーション・プロファイルがないアプリケーションでもハイパフォーマンス・グラフィックスを使用してレンダリングすることができるようになりました。これは、NvOptimusEnablement という名前のグローバル変数をエクスポートすることで可能です。

**Comment by qryxip** [comment]
> Rustでやる方法もググったら出てきた
https://users.rust-lang.org/t/question-how-to-dllexport-nvoptimusenablement-symbol-to-auto-select-dedicated-nvidia-gpu/8617/4

(Discordから)

これをC APIとPython APIに足せばよさそうですかね? (もしMaturinと干渉するなら、C APIだけで)
(私の手元にはWindows環境が無いのでレビュー側に回りたいです)

**Comment by Hiroshiba** [comment]
> NVIDIA Optimusが有効のWindows環境を持っていて

まずこの環境持ってる方がいらっしゃらない気がしますね･･･（なのでリリースまで気づかなかったのかなと）
まあえいやで実装しちゃっても良いのかなと思いました！ｗ

**Comment by qwerty2501** [comment]
@qryxip 
> これをC APIとPython APIに足せばよさそうですかね?

frontend側ではなくて共通のRust版coreだとできなさそうですかね？

**Comment by qryxip** [comment]
言われてみればrlibからでもできるかもしれませんね。`#[link_args]`がcdylib側のビルドに伝わってくれるかはわかりませんが。

**Comment by qryxip** [comment]
今のRustだと`#[link_args]`ではなくbuild.rsで設定しろとのことみたいです。

```console
error[E0557]: feature has been removed
 --> rlib/src/lib.rs:1:12
  |
1 | #![feature(link_args)]
  |            ^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of using `-C link-arg=ARG` on command line, which is available from cargo build scripts with `cargo:rustc-link-arg` now
```

**Comment by qryxip** [comment]
シンボルについても(Linuxでしか確認してませんが)rlib側で宣言したものがcdylib側に現れるっぽいので、シンボルはrlib側で、`-C link-arg`はcdylib側で設定すればよさそうですね。

```rust
// src/lib.rs
extern crate rlib as _;
```

```rust
// rlib/src/lib.rs
#[no_mangle]
pub static FOO: i32 = 42;
```

```console
❯ objdump -TC target/debug/liblink_args.so

target/debug/liblink_args.so:     file format elf64-x86-64

DYNAMIC SYMBOL TABLE:
0000000000000000  w   D  *UND*  0000000000000000  Base        _ITM_deregisterTMCloneTable
0000000000000000  w   D  *UND*  0000000000000000  Base        __gmon_start__
0000000000000000  w   D  *UND*  0000000000000000  Base        _ITM_registerTMCloneTable
0000000000000000  w   DF *UND*  0000000000000000 (GLIBC_2.2.5) __cxa_finalize
0000000000002000 g    DO .rodata        0000000000000004  Base        FOO
```

**Comment by qryxip** [comment]
(`cargo:rustc-link-arg`はcdylib側のbuild.rsに書かないと駄目なようです)

**Comment by qwerty2501** [comment]
なるほどまあそれぐらいなら良さそうですね

**Comment by Hiroshiba** [comment]
こちらのタスクに関して、一番良いGPUが使えるようになったはずなので、closeします。
@qryxip さんありがとうございました！！

**Comment by qryxip** [comment]
そういやこのissue、よく考えたらエンジン・エディタで解決されただけでコアとしてのAPIでは解決されてないですね。

**Comment by Hiroshiba** [comment]
あれ、本当ですね！！　すみません、間違えてcloseしてしまいました 🙇
