### ISSUE TITLE
actions-rs/audit-checkの代わりを探す

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#324]
## 内容

#312 でも言ったのですが、actions-rsはメンテナンスが放棄されており、また今後の再開も望めないように思えます。

最近[ついに壊れ始めてエラーを出し始め](https://github.com/VOICEVOX/voicevox_core/actions/runs/3336345706)たように見えます。

## OSの種類/ディストリ/バージョン

Actionsの`ubuntu-latest`

**Comment by qwerty2501** [comment]
binstallでcargo-auditいれてコマンド実行してしまうのが無難かもですね

**Comment by qryxip** [comment]
[cargo-deny](https://github.com/EmbarkStudios/cargo-deny)の[`cargo deny check advisories`](https://github.com/EmbarkStudios/cargo-deny#advisories)に切り替えるのもいいかもしれません。こっちには[cargo-deny-action](https://github.com/EmbarkStudios/cargo-deny-action)がありますし、ライセンスのチェックとかもついでにできます。
