### ISSUE TITLE
WindowsではGPUの情報を得てログに流すようにする

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#336]
## 内容

~~#335 とは別に、~~ Windows環境下で、[winapiを使ってGPUの情報を得](https://gist.github.com/qryxip/be52a959cfb8559e41adfa1bd7445823)てログに流すようにします。

### Pros 良くなる点

- https://github.com/VOICEVOX/voicevox_engine/issues/502 の解決の助けになる

### Cons 悪くなる点

- [winapi](https://docs.rs/winapi/)を直に使う必要がある

## OSの種類/ディストリ/バージョン

* Windows

**Comment by Hiroshiba** [comment]
なるほどです、便利だと思います！
必ず表示されるのではなく、 #335 と同様に環境変数などで制御できると嬉しそうですね！
