### ISSUE TITLE
onnxruntimeのSessionを解放してGPUメモリをリフレッシュできる仕組みを作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#337]
## 内容

onnxruntimeはどうやら使用GPUメモリなどが増え続けてしまう問題があるという報告があります。
SessionをReleaseできれば解決するかもしれません。

- https://github.com/microsoft/onnxruntime/issues/8147
- https://github.com/microsoft/onnxruntime/issues/9509

実装次第では、使っていないキャラクターのSessionを解放するといった需要も満たせると思います。

### Pros 良くなる点

増え続けるGPUメモリ使用量をなんとかする方法が提供できる

### 実現方法

`load_charater`と同じインターフェイスで`unload_character`を実装する？

## その他

コアを使うユーザー的には`VOICEVOX CORE`インスタンスを破棄すればだいたい同じことができるかも･･･？

**Comment by qwerty2501** [comment]
APIに手をくわえるならさきにAPIについての改修を終わらせたほうが良いかも
https://github.com/VOICEVOX/voicevox_core/issues/280
