### ISSUE TITLE
powershell版ダウンロードスクリプトでCPU arch自動判定する処理を実装する

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_core#339]
## 内容

bash版だとcpu archを自動で判定する処理があるが、powershell版だとx64固定なので判定できるようにする

### Pros 良くなる点

環境に合わせたvoicevox coreをダウンロードできるようになる

### 実現方法

https://github.com/VOICEVOX/voicevox_core/blob/main/scripts/downloads/download.ps1#L76-L79 に判定処理を実装する

**Comment by qryxip** [comment]
#602 によりPowerShell版は消去されたため、解決。
