### ISSUE TITLE
speaker_id と話者の対応はどこを見ればわかりますか？

### ISSUE THREAD

**Issue by mtsnrtkhr** [VOICEVOX/voicevox_core#354]
## OSの種類/ディストリ/バージョン

voicevox_core-0.13.0を使わせていただいています。
プログラムで指定する話者ID(example/python/run.pyではspeaker_idと記載されている変数)と各音声ライブラリの対応が分からずにいます。

ビルド済みのコアライブラリ
https://github.com/VOICEVOX/voicevox_core/releases/tag/0.13.0
に「詳細は voicevox_core.zip 内にある README.txt をご参照ください。」
と記載があり、README.txtには各音声ライブラリの規約が載っているのですが、
どの音声ライブラリを使っているか分からないため対応ができません。

例えば、https://ponkichi.blog/raspberry-voicevox/ のサイトには話者IDとの対応が記載されていましたが
このような情報が、ライブラリのバージョンとの対応付けされ、
README.txtなど、分かりやすい場所に記載いただけると助かります。

**Comment by Hiroshiba** [comment]
こんばんは！

バージョン0.13系であれば、ライブラリのmetas()関数を実行すれば取得できると思います！

speaker_idと内容をリスト化するのは、metasで取れる情報をテキスト化する部分をメンテナンスしないといけなくなるので、あまり気乗りしないというのが本音です。
ですが @mtsnrtkhr さんが実装してくださるなら話は別です！よかったら実装してみませんか？

もしくは、そういう機能がほしい旨をissue化してみてください。
そのときにどこをどう変えれば良さそうか、コードを読んだりしてちょっと調べて頂けると、別の方が実装しやすいと思います！

**Comment by Hiroshiba** [comment]
表題のことは解決したと思うのでissueをcloseします。
もし何かあれば続けてコメントをどうぞ！

**Comment by mtsnrtkhr** [comment]
@Hiroshiba さん
早速ご回答ありがとうございます!
metas()がそういう機能なのですね。
かなりドキュメントは検索したつもりでしたが分かりませんでした。

そして、Pythonを使っているのですが、
import core
print(core.metas())
と実行すると下記エラーが発生しました。

Exception has occurred: OSError
exception: access violation reading 0x00000000000000B0

その際の変数の値は下記のようでした。

lib:<CDLL 'c:\Users\PathToProgram\.venv\lib\site-packages\core\lib\core.dll', handle 7ffc6f7b0000 at 0x1a718103fd0>
metas:<_FuncPtr object at 0x000001A718111450>

エラーメッセージを検索すると、pythonのドキュメントにたどり着きました。

Windows では、関数が無効な引数とともに呼び出された場合の一般保護例外によるクラッシュを防ぐために、 [ctypes](https://docs.python.org/ja/3.8/library/ctypes.html#module-ctypes) は win32 構造化例外処理を使います:

core.dllのデジタル署名のタイムスタンプは下記でした。
‎2022‎年‎8‎月‎11‎日 2:41:00

これはmetasの使いかたが誤っているのでしょうか？
それとも何かの不具合でしょうか？

現在0.13.0を使っていますので、新しいもので試してみてどうなるかこちらでご連絡させていただきます。
本件はCloseいただいて結構です。

私の知識がこの程度ですので、開発は難しい気がしますが、
README.txtに「peaker_idと音声ライブラリの対応はcore.metas()を実行してご確認ください。」
と付け加えるだけでも助かると思いました。
しかし、ビルド済みのコアライブラリに記載のREADME.txtがレポジトリのどこにあるかも見つけられておらず‥‥。
お役に立てずすみません。

**Comment by Hiroshiba** [comment]
> README.txtに「peaker_idと音声ライブラリの対応はcore.metas()を実行してご確認ください。」
と付け加えるだけでも助かると思いました。

「使い方がない」のが問題かなと思いました！

ちなみに0.14からはAPIドキュメントがあるのですが、metasを実行すれば良いというのはわからなさそうでした。
使い方を案内するissueを作成してみました。

#358 

よかったら取り組んでみませんか？ご興味あれば↑でコメント頂けると！

> これはmetasの使いかたが誤っているのでしょうか？

`initialize()`の実行が必要です。
https://github.com/VOICEVOX/voicevox_core/blob/176717cef50f7606a1f20d907329c68b2cc9bf23/core/src/core.h#L38

サンプルコードが役に立つかもしれません。
https://github.com/VOICEVOX/voicevox_core/blob/176717cef50f7606a1f20d907329c68b2cc9bf23/example/python/run.py

**Comment by mtsnrtkhr** [comment]
@Hiroshiba さん

早速ご返信ありがとうございました！
initialize()が必要だったのですね。
無事にmetasのデータが取得できました。
使いかた案内のissueもありがとうございます！
そちらでご返信いたします。
