### ISSUE TITLE
download.shが社内環境のヘッダ書き換えで動かなくなってしまう

### ISSUE THREAD

**Issue by misogihagi** [VOICEVOX/voicevox_core#378]
## 不具合の内容

download.shが社内環境のヘッダ書き換えで動かなくなってしまう。
社内のプロキシからアクセスするとヘッダが書き換えられて最初が大文字になってしまいシェルがこけます。

### 現象・ログ

参考までにその時のcurlです。
```
HTTP/1.1 302 Found
Server: GitHub.com
Sate: Fri, 13 Jan 2023 14:52:06 GMT
Content-type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
Location: https://github.com/VOICEVOX/voicevox_core/releases/tag/0.13.3
...
```

## OSの種類/ディストリ/バージョン

Ubuntu:20.04

**Comment by qryxip** [comment]
なるほど。PRは作れますか? (grepとsedに`i`を付けるとかでよさそうですが)

**Comment by misogihagi** [comment]
@qryxip 
言われてみればそうですね
下のほうでPR出してますけどそっちのほうが変更少ないのでそっちに変えておきます〜
まあRust版が出るまでの辛抱ですが
