### ISSUE TITLE
tracing-subscriberが問答無用でANSI escape sequenceを出す

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#385]
## 不具合の内容

tracing-subscriberは出力がリダイレクトされていたとしても問答無用でANSI escape sequenceを出してしまいます。そのことを忘れてました。

### 現象・ログ

~~<https://twitter.com/chagara_r/status/1616108219415564288>~~
<https://twitter.com/chagara_r/status/1616109330604118022>

### 期待動作

ファイルに書き出されるときはエスケープシーケンスを出さない

## OSの種類/ディストリ/バージョン

多分全部

## その他

解決方法としてはリダイレクトを検出するか(attyクレートは確か開発が止まっているので、代替を探す)、色を付けるのをそもそもやめるかですね。

**Comment by Hiroshiba** [comment]
おお、なるほどです！！

ちょっとよくわかっていないのですが、色を付けるのをやめたら治まる感じでしょうか。
であれば、本番ビルド時は色付けをやめる形がいいのかなと思いました！

**Comment by qryxip** [comment]
> attyクレートは確か開発が止まっているので、代替を探す

[is-terminal](https://docs.rs/crate/is-terminal)らしいのでそれにしようかと。

clap-rs/clap#4249

**Comment by qryxip** [comment]
貼るべきツイートはこっちでしたね。CP932のコマンドプロンプトは...そっかそれもありますね。
<https://twitter.com/chagara_r/status/1616109330604118022>
