### ISSUE TITLE
C_APIのバッファのクローン(memcopy)を減らす

### ISSUE THREAD

**Issue by higumachan** [VOICEVOX/voicevox_core#389]
## 内容

現状はc-apiにて
https://github.com/VOICEVOX/voicevox_core/blob/a787f6d0f4bc111568114801ac38ca826320c339/crates/voicevox_core_c_api/src/lib.rs#L190-L253)

https://github.com/VOICEVOX/voicevox_core/blob/a787f6d0f4bc111568114801ac38ca826320c339/crates/voicevox_core_c_api/src/helpers.rs#L108-L118

https://github.com/VOICEVOX/voicevox_core/blob/a787f6d0f4bc111568114801ac38ca826320c339/crates/voicevox_core_c_api/src/helpers.rs#L128-L139

のように，Rustから取得されるバッファをlibc::mallocで確保し直したバッファにコピーしています．

Rust側で確保されているバッファのポインタをそのまま返すようにすると，コピーの回数が減るかと思います．

### Pros 良くなる点

- 瞬間的なバッファの使用量が半分になる
- バッファのコピーが一つ減るので高速になる(可能性が高い)
- unsafeな関数の呼び出し回数が減る

### Cons 悪くなる点

- 読むときに必要なRustの知識が増える(主観的な話ですが)

### 実現方法

Rustの[Box::leak](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.leak)を利用すると以下のようにかけます．

```rust
#[no_mangle]
pub unsafe extern "C" fn voicevox_predict_duration(
    length: usize,
    phoneme_vector: *mut i64,
    speaker_id: u32,
    output_predict_duration_data_length: *mut usize,
    output_predict_duration_data: *mut *mut f32,
) -> VoicevoxResultCode {
    into_result_code_with_error((|| {
        let output_vec = lock_internal().predict_duration(
            std::slice::from_raw_parts_mut(phoneme_vector, length),
            speaker_id,
        )?;
        let boxed_slice = output_vec.into_boxed_slice();
        output_predict_duration_data_length.write(boxed_slice.len());
        output_predict_duration_data.write(Box::leak(boxed_slice).as_mut_ptr());

        Ok(())
    })())
}
```

<s>
```rust
#[no_mangle]
pub unsafe extern "C" fn voicevox_predict_duration_data_free(predict_duration_data: *mut f32) {
    Box::from_raw(predict_duration_data);
}
```
</s>

指摘頂いた点を修正したので追記: 

```rust
#[no_mangle]
pub unsafe extern "C" fn voicevox_predict_duration_data_free(predict_duration_data: *mut f32, predict_duration_data_length: usize) {
    drop(Box::new(slice::from_raw_parts(predict_duration_data, predict_duration_data_length)));
}
```

**Comment by qryxip** [comment]
確かにRust側でもfreeはできそうですね。

ただその`Box::from_raw`ですが、`Box<f64>`になって先頭の一要素しか解放されない気がします。`length`も要求して`Vec::from_raw_parts`を使うことになるのではないかと思います。

**Comment by higumachan** [comment]
> ただそのBox::from_rawですが、Box<f32>になって先頭の一要素しか解放されない気がします。lengthも要求してVec::from_raw_partsを使う形になるのではないかと思います。 

確かにそのとおりでした．
こんな感じですかね．

```rust
#[no_mangle]
pub unsafe extern "C" fn voicevox_predict_duration_data_free(predict_duration_data: *mut f32, predict_duration_data_length: usize) {
    drop(Box::new(slice::from_raw_parts(predict_duration_data, predict_duration_data_length)));
}
```

ただ，APIが変わってしまうため議論しなければ行けないポイントは増えますね．

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！たしかにメモリコピーを一度減らせそうだと感じました！

パラメータにlengthが追加されると、ユーザーにとってはAPIが変わるだけでなくその値を保持する必要があって少し大変になりそうだなと感じました。
そこはライブラリ側で持ってあげる形、つまり仰るとおりMapを作ることで結構きれいに解決できるのかなと感じました！！

**Comment by qryxip** [comment]
[Rustのアロケータ自身](https://doc.rust-lang.org/std/alloc/struct.System.html)はサイズを覚えていないのかと思ったのですが、どうやら覚えていないみたいですね。
Mapで持つのが`usize`か[`std::alloc::Layout`](https://doc.rust-lang.org/stable/std/alloc/struct.Layout.html#method.new)かの違いだけになりそうですが、後者の方が意図が明確になるかも?

**Comment by qryxip** [comment]
いや内部はglibcのmallocとかを呼んでいたと思うので、中途半端に使ったら危ないかもしれません。`usize`の方がいいかも。

**Comment by higumachan** [comment]
すこし方針を変えて，Boxを経由せずに`Vec::leak`を利用して実装するほうが安全そうだったのでこちらで実装を行いました．
