### ISSUE TITLE
Releaseページのaarch64とarm64の混在について

### ISSUE THREAD

**Issue by osakanataro** [VOICEVOX/voicevox_core#408]
## 質問の内容
Releaseページにおいてあるファイルは基本的にlinux-aarch64だが、下記だけlinux-arm64となっているが、誤りか？
[voicevox_core-linux-arm64-cpu-0.14.0.zip](https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.0/voicevox_core-linux-arm64-cpu-0.14.0.zip)

下記のようにaarch64を指定してダウンロードしてみた場合は、linux-aarch64のファイルを取りに行こうとしている
```
$ bash download.sh --cpu-arch aarch64
対象OS:linux
対象CPUアーキテクチャ:aarch64
ダウンロードvoicevox_coreバージョン:0.14.0
ダウンロードデバイスタイプ:cpu
voicevox_coreをhttps://github.com/VOICEVOX/voicevox_core/releases/download/0.14.0/voicevox_core-linux-aarch64-cpu-0.14.0.zipからフ ァイルをダウンロードします...
open_jtalkをhttps://jaist.dl.sourceforge.net/project/open-jtalk/Dictionary/open_jtalk_dic-1.11/open_jtalk_dic_utf_8-1.11.tar.gzからファイルをダウンロードします...
curl: (22) The requested URL returned error: 404
open_jtalkをダウンロード完了,tar.gz形式で./voicevox_core/open_jtalk_dic_utf_8-1.11に解凍します...
open_jtalk_dic_utf_8-1.11/char.bin
open_jtalk_dic_utf_8-1.11/matrix.bin
open_jtalk_dic_utf_8-1.11/sys.dic
open_jtalk_dic_utf_8-1.11/unk.dic
open_jtalk_dic_utf_8-1.11/left-id.def
open_jtalk_dic_utf_8-1.11/rewrite.def
open_jtalk_dic_utf_8-1.11/pos-id.def
open_jtalk_dic_utf_8-1.11/right-id.def
open_jtalk_dic_utf_8-1.11/COPYING
open_jtalkのファイルを展開完了しました。後続のファイルダウンロード処理を待ってください
$
```

**Comment by Hiroshiba** [comment]
@osakanataro issue作成ありがとうございます！！

arm64を想定しています！
`download-linux-aarch64`をarm64にし忘れていて、３つあるlinux×arm64(aarch64)のうち２つがaarch64になっていました。

whlの方はpython側がそう決めているのでaarch64のままですが、downloadの方はarm64にするのが良さそうです。
要議論を外してバグラベルを付けたいと思います！

**Comment by Hiroshiba** [comment]
@qryxip さんが作ってくださった[こちらのPR](https://github.com/VOICEVOX/voicevox_core/pull/416)で直りそうです！（ thx @qryxip !）

本来ならリビルドすべきですが、ちょっとビルド工程がややこしいため、0.14.0でリリースされているものをリネーム処理したいと思います。
（共有です！ @y-chan @qryxip @qwerty2501 @PickledChair  ）

**Comment by Hiroshiba** [comment]
完了かなと思ったのでcloseしました。
また問題がありそうでしたらissue作成いただけると助かります！
