### ISSUE TITLE
example/python がLinux環境で動作しない

### ISSUE THREAD

**Issue by osakanataro** [VOICEVOX/voicevox_core#418]
## 不具合の内容
core.py で libcore.so を読み込もうとしているが、そのようなバイナリファイルは存在していない
シンボリックリンクとして libvoicevox_core.so を libcore.so として読み込ませたところ
「undefined symbol: voicevox_load_openjtalk_dict」というエラーとなる

### 現象・ログ
[osakana@alma9 python]$ ls
README.md  __pycache__  core.py  requirements.txt  run.py  voicevox_core
[osakana@alma9 python]$ python run.py \
    --text "これは本当に実行できているんですか" \
    --speaker_id 1
Traceback (most recent call last):
  File "/home/osakana/work/voicevox_core/example/python/run.py", line 3, in <module>
    import core
  File "/home/osakana/work/voicevox_core/example/python/core.py", line 28, in <module>
    raise Exception(f"coreライブラリファイルが{core_dll_path}に存在しません")
Exception: coreライブラリファイルが/home/osakana/work/voicevox_core/example/python/voicevox_core/libcore.soに存在しません
[osakana@alma9 python]$ ls -F voicevox_core/
README.txt                 libvoicevox_core.so*        voicevox_core.h
VERSION                    model/
libonnxruntime.so.1.13.1*  open_jtalk_dic_utf_8-1.11/
[osakana@alma9 python]$ cd voicevox_core/
[osakana@alma9 voicevox_core]$ ln -s libvoicevox_core.so libcore.so
[osakana@alma9 voicevox_core]$ cd ..
[osakana@alma9 python]$ ls -F voicevox_core/
README.txt   libonnxruntime.so.1.13.1*  open_jtalk_dic_utf_8-1.11/
VERSION      libvoicevox_core.so*       voicevox_core.h
libcore.so@  model/
[osakana@alma9 python]$ python run.py     --text "これは本当に実行できて いるんですか"     --speaker_id 1
Traceback (most recent call last):
  File "/home/osakana/work/voicevox_core/example/python/run.py", line 3, in <module>
    import core
  File "/home/osakana/work/voicevox_core/example/python/core.py", line 61, in <module>
    lib.voicevox_load_openjtalk_dict.argtypes = (c_char_p,)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/osakana/work/voicevox_core/example/python/voicevox_core/libcore.so: undefined symbol: voicevox_load_openjtalk_dict
[osakana@alma9 python]$

### 環境
環境1(上記のログ) AlmaLinux 9 (x86_84)
環境2 Armbian 22.11 Jammy Gnome(Orange Pi 5/Ubuntu 22.10ベース/aarch64)

**Comment by PickledChair** [comment]
報告ありがとうございます！

#308 と同内容のためクローズさせていただきます。実のところ、`example/python` は現在メンテナンスされておりません（README ではまだ案内されてますが、実態に即していないですね……。わかりづらくて申し訳ないです）。こちらの Issue で https://github.com/VOICEVOX/voicevox_core/issues/308#issuecomment-1276572550 にて言及されているのですが、Python から voicevox_core を使うサンプルについては現在は [`example/pyo3`](https://github.com/VOICEVOX/voicevox_core/tree/main/example/pyo3) が後継の扱いになりつつあります。そちらをお試しください（こちらも整備中のため、ドキュメントがやや整っておりませんが……）。

**Comment by Hiroshiba** [comment]
@osakanataro issue作成ありがとうございます！！

あーーー。。example/pythonはメンテされてないの漏れていました。。
@.PickledChair さんありがとうございます、助かります 🙇‍♂️ 

[pyo3版かなり良かった](https://github.com/VOICEVOX/voicevox_core/issues/414)ので整備していきたいですね･･･！！

**Comment by osakanataro** [comment]
現状、仕様上はexample/pythonでできてexample/pyo3でできないことって、SPEAKER_IDをオプションで指定できない、ということぐらいですかね

**Comment by PickledChair** [comment]
> 現状、仕様上はexample/pythonでできてexample/pyo3でできないことって、SPEAKER_IDをオプションで指定できない、ということぐらいですかね

見てみた感じでは、確かにそのように見えますね。以下の部分を直接書き換える必要があるようです。

https://github.com/VOICEVOX/voicevox_core/blob/a0cfe34700e134890b6f0a3cbb674de49cdbbf7a/example/pyo3/run.py#L11

あくまでサンプルコードなので、コードを参考に使用者が自分の都合で（例えば、speaker_id をオプションで指定できるように）改造して使って良いものと思います。最初からオプションで speaker_id を指定可能なサンプルコードであった方が良いというご提案でしたら、Pull Request を作っていただけたらと思います。
