### ISSUE TITLE
C APIのE2Eテストを作る

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#424]
## 内容

<https://github.com/VOICEVOX/voicevox_core/pull/400#issuecomment-1413947194>

### Pros 良くなる点

- 単体テストがカバーしない範囲をテストできる
    - ログ出力なども含む

### Cons 悪くなる点

- 実装コスト

### 実現方法

[Rustのintegration test](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests)内でDLLのテストをします。

まず/crates/voicevox_core_c_api/tests/runみたいな場所にworkspaceを切り離した`bin`クレートのパッケージを作り、そこでは[libloading](https://docs.rs/crate/libloading) (`dlopen`/`LoadLibrary`をやるクレート)でDLLを呼び出します。
そしてintegration test (/crates/voicevox_core_c_api/tests/{tts,tts-via-audio-query,get-version,invalid-model,missing-openjtalk-dic,…}.rs)ではそれをビルドし、[assert_cmd](https://docs.rs/crate/assert_cmd)でテストします。

この方法であれば将来このリポジトリでもcode coverageを取りたいとなったときにこの統合テストもちゃんと対象になる、と思うのですが検証はまだしていません。

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
良さそうに感じました！！

openjtalk用の辞書をどう用意し、どう差し込むかが腕の見せ所なのかなと思いました。

**Comment by qryxip** [comment]
辞書については今[/crates/voicevox_core/src/test_util.rs](https://github.com/VOICEVOX/voicevox_core/blob/main/crates/voicevox_core/src/test_util.rs)にあるやつを/crates/test_utilとして独立させ、それを利用することを考えてます。Rust APIの方のテストも少々すっきりするはず。

```diff
-        let open_jtalk_dic_dir = download_open_jtalk_dict_if_no_exists().await;
+        let open_jtalk_dic_dir = test_util::OPEN_JTALK_DIC_DIR;
```

**Comment by qryxip** [comment]
そうするとDLL呼び出しの`bin`は/crates/test_utilに含められるかも?

**Comment by Hiroshiba** [comment]
> 辞書については今[/crates/voicevox_core/src/test_util.rs](https://github.com/VOICEVOX/voicevox_core/blob/main/crates/voicevox_core/src/test_util.rs?rgh-link-date=2023-02-04T19%3A44%3A47Z)にあるやつを/crates/test_utilとして独立させ、それを利用することを考えてます。

おおおお、素晴らしい便利関数ありましたね、完全に失念していました！！

> 今思い付きましたが、そうするとDLL呼び出しのbinも/crates/test_utilに含められるかも?
> よく考えたらworkspaceを切り離す必要性は薄いし。

workspaceを切り離すというのは、つまりrootに統合テスト用のディレクトリを作ってそこにcargo.tomlを配置する感じでしょうか。
`voicevox_core_c_api`をビルドした後の成果物のテストをどこに置くべきか若干難しいですが、たしかにworkspaceを分けず`crates`内でやっちゃうのもありなのかなと思いました！

**Comment by qryxip** [comment]
> workspaceを切り離すというのは、つまりrootに統合テスト用のディレクトリを作ってそこにcargo.tomlを配置する感じでしょうか。（あるいは更に１つディレクトリを用意してその下にtoml配置)

rootというよりは以下のようにtests/下に置いて[`workspace.exclude`](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-members-and-exclude-fields)で切り離すことを考えてました。

> まず/crates/voicevox_core_c_api/tests/runみたいな場所にworkspaceを切り離したbinクレートのパッケージを作り

(https://github.com/VOICEVOX/voicevox_core/issues/424#issue-1570729940)

ただその必要性はよく考えたら薄いというよりは無い上、workspaceを統合した場合`voicevox_core_c_api`から構造体定義を持って来れるというメリットもあります。

> `voicevox_core_c_api`をビルドした後の成果物のテストをどこに置くべきか若干難しいですが

テスト内で普通に`cargo build`してそれをそのまま使おうと思ってます。実行バイナリにDLLをリンクする必要は無いし、ビルドが終わった後のプロセスからビルドを実行する分には問題無いはずなので。

**Comment by qryxip** [comment]
code coverageも試したらちゃんと取れました。

<details>
<summary>実験</summary>

```rust
#[no_mangle]
pub extern "C" fn hello() {
    if false {
        println!("this is dead code");
    }
    println!("Hello!");
}
```

```rust
use libloading::Library;

fn main() -> anyhow::Result<()> {
    unsafe {
        let lib = Library::new("./target/debug/liblib.so")?;
        let hello = lib.get::<unsafe extern "C" fn()>(b"hello")?;
        hello();
    }
    Ok(())
}
```

```rust
use duct::cmd;

#[test]
fn test() -> anyhow::Result<()> {
    cmd!("cargo", "build", "-p", "lib", "-p", "run").run()?;
    //assert_cmd::Command::cargo_bin("run")?
    //    .assert()
    //    .success()
    //    .stdout("Hello!\n")
    //    .stderr("");
    Ok(())
}
```

![image](https://user-images.githubusercontent.com/14125495/216807501-c026f40c-aefc-46c6-8c5b-bc419b8c4087.png)

↓ コメントアウトを解除

```rust
use duct::cmd;

#[test]
fn test() -> anyhow::Result<()> {
    cmd!("cargo", "build", "-p", "lib", "-p", "run").run()?;
    assert_cmd::Command::cargo_bin("run")?
        .assert()
        .success()
        .stdout("Hello!\n")
        .stderr("");
    Ok(())
}
```

![image](https://user-images.githubusercontent.com/14125495/216807559-955209fc-7b3d-46b3-bb86-c9b811b91239.png)
</details>

議論することが無ければ実装に入れるとは思いますが、今やるかどうかは優先度次第ですね。
テスト機構はともかくE2Eテスト自体を考えないといけないので、qwertyさんの #370 の後でもよさそうな気がします。

**Comment by Hiroshiba** [comment]
ビルド後にテスト、良さそうに感じました！
ただ単体テストするときはそこはテストされない（あるいは省ける）ようになってると開発しやすそう…？

#370 は新しいAPIが増える一方で、とりあえずC APIの挙動は変わらないようにできればと考えてます！
なのでむしろ複合テストがあった方がちゃんと通れてるかテストできて良いかもとちょっと思いました…！

**Comment by qryxip** [comment]
> ビルド後にテスト、良さそうに感じました！ ただ単体テストするときはそこはテストされない（あるいは省ける）ようになってると開発しやすそう…？

重いテスト用に[`#[ignroe]`](https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested)というattributeがあって、それを付ければ単体テストとは分離することができます。実行するときは`--ignored`か`--include-ignored`でやる形になります。

> #370 は新しいAPIが増える一方で、とりあえずC APIの挙動は変わらないようにできればと考えてます！ なのでむしろ複合テストがあった方がちゃんと通れてるかテストできて良いかもとちょっと思いました…！

なるほど。それなら取り掛かった方がいいですね。

**Comment by Hiroshiba** [comment]
`#[ignore]`、なるほどです。いたれりつくせりだ。

**Comment by qwerty2501** [comment]
#370 ではengine互換向けのAPI以外は破壊的変更入ります

**Comment by qryxip** [comment]
なるほど。なら`compatible_engine`の分だけ作ればいいですかね。

**Comment by qwerty2501** [comment]
そうですね。現状でも使われてるのはそこなので
