### ISSUE TITLE
ONNX Runtime本体にマージされたRust実装を使う

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#427]
## 内容

日本時間で2023年2月9日、[ONNX Runtime本体へのRustバインディング追加のPR](https://github.com/microsoft/onnxruntime/pull/12606)がマージされました。

まだ深く触れたりした訳ではないのですが、onnxruntime-rsとの最大の違いとしてはonnxruntime.dllの読み込みが`dlopen`/`LoadLibrary*`ベースになったことが挙げられるのではないかと思います。DLLのパスを指定することもできます。ただし読み込んだDLLは`Environment`共々[`OnceCell`](https://docs.rs/once_cell/1/once_cell/sync/struct.OnceCell.html)で管理されるみたいなので、DLLの読み直しはできなさそうです。

[`onnxruntime::environment::Environment::with_library_path`](https://github.com/microsoft/onnxruntime/blob/6eeeecf07fd67e410c94bfdbe43a98d045d512fd/rust/onnxruntime/src/environment.rs#L257-L262)

あとは`ORT_RUST_STRATEGY=compile`という指定でonnxruntime.dllのダウンロードするのではなく手元でCMakeする選択肢が入ったことでしょうか (あと何故かこっちがデフォルトになってます)。

### Pros 良くなる点

個人的な意見としては、`dlopen`/`LoadLibrary*`ベースになったことはVOICEVOX COREにとっても大きいと思ってます。
DLLが無いときには人間が読めるメッセージを出せますし、voicevox\_core.dllの読み込みから`initialize`までの間にonnxruntime.dllをどっかからダウンロードしてくる機構も考えられます。あとはrpathの指定や[`$ORT_OUT_DIR`でのハック](https://github.com/VOICEVOX/onnxruntime-rs/issues/3)も不要になりますし、Python APIの取り回しも良くなるでしょう。

### 実現方法

必要であるならVOICEVOX/onnxruntimeとしてフォークし、onnxruntime-rsから切り替える。

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！
移行を検討しても良いのかなと思いました！

VOICEVOXのonnxruntime-rsはいくつかの変更が加わっていますが、これらの差分がなくても大丈夫なのかは検討しないとかも？
https://github.com/VOICEVOX/onnxruntime-rs/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged

**Comment by qryxip** [comment]
Safe Rust部分(`onnxruntime`)はまた追加しなおす必要がありそうですね。

これの/onnxruntime/src/部分をそのまま移植すればよさそうではあります。
https://github.com/VOICEVOX/onnxruntime-rs/compare/cd5a6ebae8abc06080f4da9a248be590fc6ce2fe..405f62fb53df1b59b0e69adafbd1c28e4d5c2787

**Comment by Hiroshiba** [comment]
こちらのタスクですが、とりあえず本家onnxruntimeのリポジトリをforkしていろいろ進めています！
https://github.com/VOICEVOX/onnxruntime
