### ISSUE TITLE
EngineのSynthesis Engineに搭載されている機能を一部移行する

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox_core#43]
## 内容

現状、dllで提供される`yukarin_s_forward`、`yukarin_sa_forward`、`decode_forward`を利用するには、そこまでのデータの整形を開発者が自ら行う必要があり、ユーザーの最大化につながるであろうサードパーティ連携の妨げになってしまう恐れがあると思います。
そこで、CoreがONNX化・一部オープンソース化された今だからこそ、[Engineの`synthesis_engine.py`](https://github.com/VOICEVOX/voicevox_engine/blob/master/voicevox_engine/synthesis_engine.py)の`create_accent_phrase`(OpenJTalkに依存するのでこれは不要かも?)、`replace_phoneme_length`、`replace_mora_pitch`、`synthesis`といった、TTSの主要機能系関数をC++もしくはCythonで書き直し、Core(のPythonライブラリ)に同梱することで、より利用しやすい形にできるのではないかと考えます。

若干、以下に挙げるコメントと類似する内容だと思います。
https://github.com/VOICEVOX/voicevox_engine/issues/119#issuecomment-976306867

CythonとC++の2種類の手法を挙げた理由を記載しておきます。
- Cythonで書くメリット
  - numpyの資産を利用できる。
  - 既存コードの流用が若干可能
- C++で書くメリット
  - `core.dll`/`libcore.so`/`libcore_cpu.dylib`に内包できるため、他言語からも利用可能になる
  - 最大限考慮すれば、Synthesis過程を高速化できる可能性がある(どの程度かは不明、numpyを使った方がいい可能性もあり)

Cythonで書くのが一番楽かもしれませんが、個人的には他言語や様々な形で利用可能になるC++で書くのがよいと思います。
(単純に私が過去に作り上げた資産を流用できるというのもあります...w)
Cythonで書いてもdllなどに内包できるかもしれませんが、やり方に関する情報が少ないうえ、coreがnumpyなどのライブラリに依存するような形になる可能性もあり、あまり良くないかと思います。

### Pros 良くなる点

Coreの利用の幅が広がり、扱いやすさが向上する

### Cons 悪くなる点

最低限の機能で構成されていたCoreが肥大化する
そもそも、 https://github.com/VOICEVOX/voicevox_engine/issues/119#issuecomment-976306867 ではCoreに移植することに関して議論がなされておらず、別ライブラリに分けるような方向性で議論が進んでいます。
しかし、個人的な考えとして、他言語からも読み込みやすいCoreの動的ライブラリ1つとその他のCUDAなどの環境さえ用意すれば大体の環境で実行できるので、良いと思います。

### 実現方法

C++であれば、私が以前に作った[node-voicevox-engine](https://github.com/y-chan/node-voicevox-engine)のC++部分をベースに、Coreに組み込めると思います。
Cythonであれば、[Engineの`synthesis_engine.py`](https://github.com/VOICEVOX/voicevox_engine/blob/master/voicevox_engine/synthesis_engine.py)をCythonで書き直すことで対応できると思います。
いずれにしても、提案者は私なので、私が出来る範囲で対応したいと思います。

**Comment by Hiroshiba** [comment]
良いですね！！
どこからどこまでがエンジン側で、どこからどこまでがコア側なのかしっかり分けたほうが良さそうです。
コアに機能を足すのではなく、TTSライブラリ用のリポジトリをコアとエンジンの間に挟むという手もあるかもです。

**Comment by qwerty2501** [comment]
TTSライブラリ用のリポジトリに分けるかどうかはコアのみを使用したい需要があるかどうかによりそうですね。
個人的には現状どういう需要があるかわからないし、とりあえず分ける方向でいってもいいのかなと思いました。

**Comment by qwerty2501** [comment]
どの程度使い物になるかわかりませんがこういうものを見つけたのでおいておきます
[SWIG](http://www.swig.org/index.php)
C/C++で書いたものを他言語向けのラッパーを自動生成できるようです。
