### ISSUE TITLE
バージョンがあがったことでpythonのexampleが使えなくなった

### ISSUE THREAD

**Issue by misogihagi** [VOICEVOX/voicevox_core#431]
## 不具合の内容

rust版になったことで[pythonのexample](https://github.com/VOICEVOX/voicevox_core/tree/main/example/python)が使えなくなりました。

### 現象・ログ

[core.py
](https://github.com/VOICEVOX/voicevox_core/blob/main/example/python/core.py)で使われているlibcoreがないから起きるようです。

0.14.1の場合
<details>
<summary>0.14.1のダウンロード</summary>

$ ./download.sh
対象OS:linux
対象CPUアーキテクチャ:x64
ダウンロードvoicevox_coreバージョン:0.14.1
ダウンロードデバイスタイプ:cpu
voicevox_coreをhttps://github.com/VOICEVOX/voicevox_core/releases/download/0.14.1/voicevox_core-linux-x64-cpu-0.14.1.zipからファイルをダウンロードします...
open_jtalkをhttps://jaist.dl.sourceforge.net/project/open-jtalk/Dictionary/open_jtalk_dic-1.11/open_jtalk_dic_utf_8-1.11.tar.gzからファイルをダウンロードします...
open_jtalkをダウンロード完了,tar.gz形式で./voicevox_core/open_jtalk_dic_utf_8-1.11に解凍します...
open_jtalk_dic_utf_8-1.11/char.bin
open_jtalk_dic_utf_8-1.11/matrix.bin
open_jtalk_dic_utf_8-1.11/sys.dic
open_jtalk_dic_utf_8-1.11/unk.dic
open_jtalk_dic_utf_8-1.11/left-id.def
open_jtalk_dic_utf_8-1.11/rewrite.def
open_jtalk_dic_utf_8-1.11/pos-id.def
open_jtalk_dic_utf_8-1.11/right-id.def
open_jtalk_dic_utf_8-1.11/COPYING
open_jtalkのファイルを展開完了しました。後続のファイルダウンロード処理を待ってください
voicevox_coreをダウンロード完了,zip形式で./voicevox_coreに解凍します...
Archive:  /tmp/tmp.li9Gyxh8Xc
   creating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/
  inflating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/README.txt
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/VERSION
  inflating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/libonnxruntime.so.1.13.1
  inflating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/libvoicevox_core.so
   creating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d0.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d1.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d10.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d11.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d2.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d3.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d4.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d5.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d6.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d7.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d8.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/d9.bin
  inflating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/metas.json
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd0.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd1.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd10.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd11.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd2.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd3.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd4.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd5.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd6.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd7.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd8.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pd9.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi0.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi1.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi10.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi11.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi2.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi3.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi4.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi5.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi6.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi7.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi8.bin
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/model/pi9.bin
  inflating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.14.1/voicevox_core.h
voicevox_coreのファイルを展開完了しました。後続のファイルダウンロード処理を待ってください
全ての必要なファイルダウンロードが完了しました
</details>

```
$ ls voicevox_core/
README.txt  VERSION  libonnxruntime.so.1.13.1  libvoicevox_core.so  model  open_jtalk_dic_utf_8-1.11  voicevox_core.h
```

0.13.1の場合
<details>
<summary>0.13.3のダウンロード</summary>

$ ./download.sh -v 0.13.3
対象OS:linux
対象CPUアーキテクチャ:x64
ダウンロードvoicevox_coreバージョン:0.13.3
ダウンロードデバイスタイプ:cpu
voicevox_coreをhttps://github.com/VOICEVOX/voicevox_core/releases/download/0.13.3/voicevox_core-linux-x64-cpu-0.13.3.zipからファイルをダウンロードします...
open_jtalkをhttps://jaist.dl.sourceforge.net/project/open-jtalk/Dictionary/open_jtalk_dic-1.11/open_jtalk_dic_utf_8-1.11.tar.gzからファイルをダウンロードします...
open_jtalkをダウンロード完了,tar.gz形式で./voicevox_core/open_jtalk_dic_utf_8-1.11に解凍します...
open_jtalk_dic_utf_8-1.11/char.bin
open_jtalk_dic_utf_8-1.11/matrix.bin
open_jtalk_dic_utf_8-1.11/sys.dic
open_jtalk_dic_utf_8-1.11/unk.dic
open_jtalk_dic_utf_8-1.11/left-id.def
open_jtalk_dic_utf_8-1.11/rewrite.def
open_jtalk_dic_utf_8-1.11/pos-id.def
open_jtalk_dic_utf_8-1.11/right-id.def
open_jtalk_dic_utf_8-1.11/COPYING
open_jtalkのファイルを展開完了しました。後続のファイルダウンロード処理を待ってください
voicevox_coreをダウンロード完了,zip形式で./voicevox_coreに解凍します...
Archive:  /tmp/tmp.ygwkTgLgAh
   creating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.13.3/
  inflating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.13.3/core.h
 extracting: ./voicevox_core/voicevox_core-linux-x64-cpu-0.13.3/VERSION
  inflating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.13.3/libcore.so
  inflating: ./voicevox_core/voicevox_core-linux-x64-cpu-0.13.3/README.txt
voicevox_coreのファイルを展開完了しました。後続のファイルダウンロード処理を待ってください
全ての必要なファイルダウンロードが完了しました
</details>

```
$ ls voicevox_core/
README.txt  VERSION  core.h  libcore.so  open_jtalk_dic_utf_8-1.11
```

```
if get_os == "Windows":
    lib_file = "core.dll"
elif get_os == "Darwin":
    lib_file = "libcore.dylib"
elif get_os == "Linux":
    lib_file = "libcore.so"
```

## VOICEVOXのバージョン

0.14.1

**Comment by sevenc-nanashi** [comment]
#308 と被ってそうですね。クローズします。

**Comment by Hiroshiba** [comment]
@misogihagi 
isuse作成ありがとうございます！！

python/exampleがごっそり変わりました。
使い心地もかなり変わっているのですが、もしよかったらまた触ってみていただければ･･･！！
