### ISSUE TITLE
rust版のダウンローダーはすでに使えますか？

### ISSUE THREAD

**Issue by misogihagi** [VOICEVOX/voicevox_core#433]
## 質問の内容

スクリプト版とrust版のダウンローダーがあると思います。
rust版試しましたが問題なく動作しました。
まだメンテ中ですか？

## VOICEVOXのバージョン

0.14.1

**Comment by Hiroshiba** [comment]
@misogihagi すでに使えます！！とても便利なはずです。
まだREADMEなどで案内できてないので、していきたいですね！！

どうでしょう、READMEでの案内などを書いてみませんか？ 👀  @misogihagi

**Comment by misogihagi** [comment]
ダウンロード状況も表示されるのでとても便利でした👍
README書きたいのはやまやまなのですが、その前に

1. パワーシェルとシェルスクリプトの両方をメンテしていくのは大変なので
2. スクリプト版のダウンローダーはメンテしない
3. ダウンローダーは基本的にgithub releaseから使う

ということでよろしいでしょうか？

**Comment by Hiroshiba** [comment]
確認ありがとうございます！！
３に関してはそのとおりです。ビルド済みのを配布した方が便利で、それだとreleasesが最適なので･･･！

1と2に関してはそのような方針だった記憶があるのですが、ちょっと認識確認します 🙇 
@qryxip @qwerty2501 @PickledChair どうでしたっけ。。どこかで議論があったかもなのですが、掘り出せず。。

**Comment by PickledChair** [comment]
https://github.com/VOICEVOX/voicevox_core/pull/375#issuecomment-1407076012

おそらくこの辺りのコメントのときには、Rust版ダウンローダーへの一本化という話になっていたと思います（ #369 や #399 のときのコメントの流れを見てもそんな感じでした）。私も異論はないです👍

**Comment by Hiroshiba** [comment]
あ、そちらですね！！！　ありがとうございます！
とのことなのですが、どうでしょう・・・！！ @misogihagi

**Comment by misogihagi** [comment]
とりあえずダウンローダーをスクリプト版からrust版を使うようにreadme変えてみました。
rustのいいところでもあり悪いところでもあるんですけど、アーキテクチャの案内が無作法になってしまいますね…

**Comment by qryxip** [comment]
@Hiroshiba #602  によって解決済みの認識です。closeできると思います。
