### ISSUE TITLE
DirectMLのサポート開始

### ISSUE THREAD

**Issue by tuna2134** [VOICEVOX/voicevox_core#442]
## 内容

onnxruntimeではDirectMLがサポートされています。そこでgpu版にdirectmlを追加するのはどうでしょう？
NVIDIA製以外の他のgpuが使えるため

### Pros 良くなる点

Gpuのサポートが新たに追加できる。

### Cons 悪くなる点

調査中

**Comment by tuna2134** [comment]
あ、見落としていました。

**Comment by Hiroshiba** [comment]
もうサポート済みですね…！
