### ISSUE TITLE
library not found "libonnxruntime.so.1.13.1"

### ISSUE THREAD

**Issue by AkariOficial** [VOICEVOX/voicevox_core#446]
> 

> ## 質問の内容

## VOICEVOXのバージョン

0.14.1

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

## その他

これらのエラーが発生しています 
```sh
Traceback (most recent call last):
  File "/root/pacotes/voicevox_core/teste/test.py", line 1, in <module>
    from voicevox_core import synthetize
  File "/usr/lib/python3.10/site-packages/voicevox_core/__init__.py", line 11, in <module>
    from ._rust import METAS, SUPPORTED_DEVICES, VoicevoxCore  # noqa: F401
ImportError: libonnxruntime.so.1.13.1: cannot open shared object file: No such file or directory
```

ライブラリ「libonnxruntime.so.1.13.1」を配置すると、正常に動作することを思い出してください。しかし、プロジェクトから削除すると、このエラーが発生します。これを解決したい

**Comment by Hiroshiba** [comment]
English please!

**Comment by AkariOficial** [comment]
> English please!

library not found "libonnxruntime.so.1.13.1"

```sh
 Traceback (most recent call last):
  File "/root/pacotes/voicevox_core/teste/test.py", line 1, in <module>
    from voicevox_core import synthetize
  File "/usr/lib/python3.10/site-packages/voicevox_core/__init__.py", line 11, in <module>
    from ._rust import METAS, SUPPORTED_DEVICES, VoicevoxCore  # noqa: F401
ImportError: libonnxruntime.so.1.13.1: cannot open shared object file: No such file or directory
```

Remember that when I put the library "libonnxruntime.so.1.13.1" it works fine. But when I remove it from the project I get this error. I want to solve this

**Comment by Hiroshiba** [comment]
It is expected to work without `libonnxruntime.so`.
This is not a particular problem, so I will close the Issue.

If you have any further questions, please comment.
