### ISSUE TITLE
Android向け動的ライブラリを作成・試運転してみる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#449]
## 内容

Android向けビルドが追加されました。

- https://github.com/VOICEVOX/voicevox_core/issues/437

実際に製品版をビルドして、プレビュー版としてコアリポジトリ内で提供してみます。
そのあと実際に動いたらこのissueは完了だと思います。

## その他

ちょっと時間頂くかもしれません。

**Comment by Hiroshiba** [comment]
@char5742 
予定が結構詰まっていて製品版のビルドは１週間ほどお時間頂くことになるかもです、おまたせしてしまって申し訳ないです 🙇

**Comment by Hiroshiba** [comment]
あ、もしかしたらzipファイルの名前衝突が起こってるかも･･･？

**Comment by char5742** [comment]
すみません！！衝突してしまっていますね
artifact_nameは android-arm64-cpu みたいに変えるべきでした。

https://github.com/VOICEVOX/voicevox_core/blob/20b45a16f4e2aa89fbda5f43a6ed25942e4dc58a/.github/workflows/build_and_deploy.yml#L71-L72

https://github.com/VOICEVOX/voicevox_core/blob/20b45a16f4e2aa89fbda5f43a6ed25942e4dc58a/.github/workflows/build_and_deploy.yml#L152-L154

https://github.com/VOICEVOX/voicevox_core/blob/20b45a16f4e2aa89fbda5f43a6ed25942e4dc58a/.github/workflows/build_and_deploy.yml#L181-L188

**Comment by char5742** [comment]
適当な仕事で本当にごめんなさい！修正PRを出させていただきました

**Comment by Hiroshiba** [comment]
いえいえ！　こうやって気づけて修正PRもいただけるなら全く問題ないです！！

**Comment by Hiroshiba** [comment]
OSS版の方ですがandroid版が作れるっぽいことを確認しました！

- https://github.com/Hiroshiba/voicevox_core/releases/tag/0.15.0-android.1

**Comment by Hiroshiba** [comment]
@char5742 製品版のAndroidビルド、作ってみました！！

- https://github.com/VOICEVOX/voicevox_core/releases/tag/0.15.0-preview.0

**Comment by char5742** [comment]
ありがとうございます！早速試してみますね

**Comment by Hiroshiba** [comment]
楽しみですね！！

discordにてお聞きしたこちらのサンプルプログラムですが、VOICEVOX COREの事例紹介に追加させていただいてもよろしいでしょうか 👀 
https://github.com/char5742/voicevox_flutter

追加プルリクをお願いできれば！！
ご面倒であればこちらでちょこっと追加させていただこうかなと思います 🙏

**Comment by char5742** [comment]
私の方でPR出させていただきます！READMEとかもう少し手直ししたいので

**Comment by Hiroshiba** [comment]
承知しました、お待ちしています！！

**Comment by Hiroshiba** [comment]
動くっぽいことを確認できたのでcloseしたいと思います。
@char5742 さんありがとうございました！！
