### ISSUE TITLE
voicevox engineとcoreで音声合成の処理時間が違う

### ISSUE THREAD

**Issue by Garden-Tree** [VOICEVOX/voicevox_core#465]
## 不具合の内容

voicevox engineをローカル（docker）で起動してからrequestを送って音声合成をする場合とvoicevox coreをライブラリとしてソースコードに読み込んで音声合成をする場合で処理時間が変わってしまう。（ネットワーク越しのengineのほうが高速。）

### 現象・ログ
「あのイーハトーヴォのすきとおった風、夏でも底に冷たさをもつ青いそら、うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。」を音声合成するのにかかる時間

engine: 約1.5sec
core: 約3.3sec

#### engine

1. windows版dockerにてvoicevox engineを起動
```PowerShell
docker pull voicevox/voicevox_engine:cpu-ubuntu20.04-latest
docker run --rm -it -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:cpu-ubuntu20.04-latest
```
2. Pythonでrequestを送信して音声合成
```Python
import requests
import json
import time

def voicevox_synthesize(text, speaker):
    start = time.time() # debug

    res1 = requests.post('http://127.0.0.1:50021/audio_query', params = {'text': text, 'speaker': speaker})
    res2 = requests.post('http://127.0.0.1:50021/synthesis', params = {'speaker': speaker},data=json.dumps(res1.json()))
    with open("engine.wav", "wb") as f:
        f.write(res2.content)
    print(time.time() - start) # debug

text = "あのイーハトーヴォのすきとおった風、夏でも底に冷たさをもつ青いそら、うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。"
speaker = 3 # ずんだもん
voicevox_synthesize(text, speaker)
```
参考: https://qiita.com/taka7n/items/1dc61e507274b93ee868

#### core
1.  `voicevox_core-0.14.3+cpu-cp38-abi3-win_amd64.whl`をダウンロードして、pythonにインストール
```
py -m pip install voicevox_core-0.14.1+cpu-cp38-abi3-win_amd64.whl 
```
2. ONNX Runtimeと辞書ファイルをダウンロードし、直下に配置
3. Pythonで音声合成を実行
```Python
import time
from pathlib import Path
from voicevox_core import VoicevoxCore

core = VoicevoxCore(open_jtalk_dict_dir=Path("open_jtalk_dic_utf_8-1.11"))
def voicevox_synthesize(text, speaker):
    start = time.time() # debug

    if not core.is_model_loaded(speaker):  # モデルが読み込まれていない場合
        core.load_model(speaker)  # 指定したidのモデルを読み込む
        wave_bytes = core.tts(text, speaker)
    with open("core.wav", "wb") as f:
        f.write(wave_bytes)
    print(time.time() - start) # debug

text = "あのイーハトーヴォのすきとおった風、夏でも底に冷たさをもつ青いそら、うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。"
speaker = 3 # ずんだもん
voicevox_synthesize(text, speaker)
```
参考: https://happy-shibusawake.com/voicevox_engine/1004/

### 期待動作

ネットワークを超えない分、coreの方が高速に動作するのではないか？

## VOICEVOXのバージョン

voicevox_core             0.14.3+cpu
https://hub.docker.com/r/voicevox/voicevox_engine
共にCPU版

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 Home 64bit 22H2
CPU: Ryzen 9 5900X
RAM: 32GB
(GPU: RTX 3070 Ti)

Python 3.11.3

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
一般的に速度は変わらないはずですが･･･謎ですね･･･。

コアの方のコード、初回以外TTSされない様になっているように見えました。
`wave_bytes = core.tts(text, speaker)`はインデントが１つ左にあるのが正しそうに思います。

いくつか示唆を得られそうなコメントをしてみます。参考になれば幸いです！

#### 1. すでにロードされている

たぶん気をつけられていると思うのであまり可能性は高くなさそうなのですが、キャラクターのロードに差があるかもです。
コピペして何度も同じ関数を呼ぶのはどうでしょう。こんな感じに。

```python
text = "あのイーハトーヴォのすきとおった風、夏でも底に冷たさをもつ青いそら、うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。"
speaker = 3 # ずんだもん
voicevox_synthesize(text, speaker)
voicevox_synthesize(text, speaker)
voicevox_synthesize(text, speaker)
voicevox_synthesize(text, speaker)
voicevox_synthesize(text, speaker)
```

#### 2. CPU利用率を見てみる

タスクマネージャーあたりでCPU利用率が見れるはずです。
CPUが動いてる割合が違うようであれば、そこにヒントがあるかもです。

#### 3. コアとエンジンはバージョンが同じでも中身が異なる場合がある。

エンジンの1.4.1とコアの1.4.1はもしかしたら中身がずれてる可能性があります。
どちらも1.4系の最新版を使うと確実に一緒です。

**Comment by Garden-Tree** [comment]
解決しました。。。
複数回実行してみると二回目以降は約1.5secになりました。
モデルのロードをしていなかったのが原因でした。
お騒がせしました。
