### ISSUE TITLE
`group_imports=StdExternalCrate`でRustfmtをかける

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#466]
## 内容

<code>--config [group\_imports](https://rust-lang.github.io/rustfmt/?version=v1.5.2&search=#group_imports)=StdExternalCrate</code>でRustfmtをかけます。

<https://github.com/VOICEVOX/voicevox_core/issues/237>と類似したものです。現在このリポジトリの`use`のスタイルは、qwertyさんが書いたのとSuitCaseさんが書いたのと私が書いたので混沌とした状態になっています。これを一つに統一します。

`StdExternalCrate`である理由は、Rust Analyzerが(現在のところ)アイテムの自動インポートを行うときにそのようなスタイルで追加してくるからです。

![ra\_import](https://user-images.githubusercontent.com/14125495/233133617-c6a42b93-cbaa-4281-894f-25ccec84c213.gif)

### Pros 良くなる点

- このリポジトリにPRを出す人が混乱しないでよくなる
    現在このリポジトリには統一されたルールなんてものは無いわけですが、初めて来た人にとってはそのことは自明ではなく、**ほんのちょっとだけ**混乱する要素になるかなと思っています。

### Cons 悪くなる点

- CIでこれを強制する場合、Nightly Rustの管理が必要になる
    ただし[Nightly Rustには他に使い道がいくつかあります](https://github.com/VOICEVOX/voicevox_core/pull/425#issuecomment-1474659197)。

### 実現方法

1. `cargo +nightly fmt -- --config group_imports=StdExternalCrate`
2. (未定) ActionsでNightly Rustを管理するようにし、Actions上で`group_imports=StdExternalCrate`をチェックするようにする

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
importの順番が一意になる感じですよね。
コードの統一感は見通しの良さに繋がっていろんな恩恵があるので割と導入したいなと思いました！

基幹部分にnightly使うのはだいぶ危うそうですが、formatterだけならありだと思います。
cargo +nightlyはnightlyなRustのインストールが必要な感じでしょうか…？

あるいは同等のことをするサードパーティライブラリがあるなら、そちらに依存するのもありかもです。
実際エディタやエンジンはESLintやisortなので。

**Comment by qryxip** [comment]
> cargo +nightlyはnightlyなRustのインストールが必要な感じでしょうか…？

はい。必要ですね...

**Comment by qryxip** [comment]
> あるいは同等のことをするサードパーティライブラリがあるなら、そちらに依存するのもありかもです。

Rustfmtくらいしか多分無いですね...

Rustfmtではないフォーマッターとしてはprettypleaseというものがあるのですが、これは機械的に生成された数千数万行のコードを破綻無くフォーマットするための用途で用いられており(例えば我々がonnxruntime-rsやopen_jtalk-rsで使っているbindgen)、`group_imports`にあたる設定は無かったんじゃないかと。

**Comment by Hiroshiba** [comment]
なるほどです。
公式ライブラリに含まれてるとリリースまで時間がかかるという欠点もあるんですねー

流石にnightlyは難しいかなと思いました！
たまにその設定でformatかけてあげる、とかですかねぇ。。

**Comment by qryxip** [comment]
nightly入れるとしたら、`nightly-2023-04-20`のような形で入れておき`update_rust_toolchain`ワークフローによるstableの更新のときにnightlyも更新するといったことを考えてました。もちろんlintやbuildはstableのままで。

参考として聞きますが、サニタイザとか[cargo-udeps](https://github.com/est31/cargo-udeps)とか他のnightly依存のツールも避ける方針でしょうか?

**Comment by qryxip** [comment]
> 流石にnightlyは難しいかなと思いました！

単純にここら辺のコスト感覚を共有しておきたいなと思いました。
私としては、手元で作業する我々は普通にstableのRustfmtを使っておいて、CIではnightlyのRustfmtでチェックするという感じで考えています。

**Comment by qryxip** [comment]
あと「nightlyなRustのインストールが必要」の時点で、もしかしたらですが齟齬が発生していそうな予感もしています。

私が考えているのはCIでのみnightlyにする方針ですが、仮に手元でやりたくなったときも

```console
❯ rustup install nightly
```

とだけ実行すれば60MiBくらいのダウンロードの後Nightly Rustが使えるようになります。pyenvやnvsにあたるものは標準搭載です。

**Comment by Hiroshiba** [comment]
・コード実行するRustがnightlyになるのは避けたい
・フォーマットだけnightlyになるのはOK
・CIがnightlyもOK
って感じです。

ただ、開発者にとって「フォーマッターがないのにCIが落ちる」のはストレスになりそうです。
rustupをわかってないのですが、+nightlyを書いたときだけnightlyが使われる感じでしょうか？

**Comment by qryxip** [comment]
はい、そうです

**Comment by Hiroshiba** [comment]
なるほどです！

nightlyは相当不安定なことがあり得るのでできれば避けたいかもです。
フォーマット用の仕様が入ったり消えたりするのも少ししんどそうです。
betaに入ってるならbetaが良さそうですが、どうでしょう。

**Comment by qryxip** [comment]
開発者のストレスについてですが、Reviewdogから言われる形であれば軽減できるかもしれません

**Comment by Hiroshiba** [comment]
どこを修正すればよいかわかるから、でしょうか？
「フォーマッターがないのにCIが落ちる」が気になってます。
「`cargo +beta fmt -- --config group_imports=StdExternalCrate`でフォーマットしてください」と案内できるならまあ良いかなーと

**Comment by qryxip** [comment]
案内というより、reviewdogならsuggestionまで出せるんじゃないかと思っています。
<https://github.com/reviewdog/reviewdog#code-suggestions>

**Comment by qryxip** [comment]
> betaに入ってるならbetaが良さそうですが、どうでしょう。

あ、betaには入っていないですね...状況はこんな感じです。
<https://github.com/rust-lang/rustfmt/issues/5083>

**Comment by Hiroshiba** [comment]
なるほどです、suggestionまで出せるなら結構ありかもと思いました！！
betaに入ってないのもなるほどです。

CIに入れてreviewdogでsuggestion出してもらう、という体験をしてみたいです･･･！！！
（順番入れ替えだと結構でかいsuggestionになるはずなので、たぶんsuggestion出ないんじゃないかなーとちょっと思ってます）

**Comment by qryxip** [comment]
> Rust Analyzerとずれるとなると、+nightlyなfmtをかけたコードを、通常のRust toolchainで見るとエラーやwarningになる感じでしょうか。 ちょっと厳しそうに思いました。nightlyが明けて正式導入されたらかなぁと･･･。

いえ、Rust Analyzer式で揃えた筈の`use`が、`StdExternalCrate`に弾かれるだけです。Rust Analyzer自体及びstableのRustfmtは何も言いません。

> それはそれとして、reviewdogは興味があります！！ もし`group_imports=StdExternalCrate`が難しそうであれば、いったんこちらのissueは閉じて、reviewdogを導入していくって感じですかね。

まあ`use`が現状混沌としているのは事実なので、手動でRust Analyzer式(機械によるフォーマットが現状不可)にしようかと。

**Comment by Hiroshiba** [comment]
なるほどです！！

まずフォーマッターを導入するかの判断について優先順位が高い順に整理していくと

* Rustに詳しくない開発者がストレスを感じるのは避けたい
	* フォーマット方法は必ず案内
	* nightly Rustの挙動が変でCIが落ちるのは避けたい
* Rustに詳しい開発者がストレスを感じるのは避けたい
	* importのフォーマッターは導入したい
* レビュワーがストレスを感じるのは避けたい
	* これはフォーマッターが導入されたにせよされなかったにせよほぼ変わらない

ということかなと。従うと

* READMEでフォーマット方法を案内
	* nightlyのインストールと`cargo +nightly fmt -- --config group_imports=StdExternalCrate`を案内
* CIの導入はどちらでも
	* nightly Rustが狂うこともあると思うのでCIは一長一短
	* errorレベルではなくwarnやinfoレベルならOK
* 今のコードに`group_imports=StdExternalCrate`フォーマットする

ですかね！

**Comment by Hiroshiba** [comment]
あ。

> 手動でRust Analyzer式

という提案頂いてたの見逃しました。
↑の流れなら`group_imports=StdExternalCrate`のフォーマッターありかなと思いましたが、ちょっと良くない感じですか。

**Comment by qryxip** [comment]
「Rust Analyzer式」のと互換性が無いですね...まとめるとこんな感じです。

| groups imports                                  | フォーマッタ                                          | `Preserve`の部分集合? | `StdExternalCrate`の部分集合? | Rust Analyzesr式の部分集合? |
| :-                                              | :-                                                    | :-                    | :-                            | :-                          |
| `Preserve`<br>(stableを含むRustfmtの規定の設定) | N/A (既定設定のRustfmtはすべてを受理し、何も行わない) |                       | :heavy_check_mark:            | :heavy_check_mark:          |
| `StdExternalCrate`<br>(nightly限定)             | nightlyのRustfmt                                      | :x:                   |                               | :x:                         |
| Rust Analyzer式                                 | 存在しない                                            | :x:                   | :x:                           |                             |

**Comment by qryxip** [comment]
あとRust Analyzer式group importsですが、rust-lang/rust-analzyerのPR/issueコメント以外にドキュメントは多分存在しないですね... 

Rust Analyzerは婉曲的に表現するとかなりフットワークが軽いので、しれっとデフォルトの挙動が変更されるかもしれません。
[週一でリリースされるRust AnalyzerのChangelog](https://rust-analyzer.github.io/thisweek)
("drop support for …"という字面が"New Features"の方に含まれていたりします。多分"New Features"と"Fixes"と"Internal Improvements"の三つしか無いのでは?)

なのでRust Analyzer式で一度だけフォーマットし、CIの設定やドキュメントの記述はせずに、以後しばらくの間は(qwertyさんやSuitCaseさんも含めて)PRに対する突っ込みは一切入れない、というのが丸いのかなと今は思っています...

**Comment by Hiroshiba** [comment]
なるほどです！
良い感じの一意なimport用フォーマッターが誰でも浸かる形でリリースされると嬉しそうだなーと思いました。

一旦closeで良さそうでしょうか？

**Comment by qryxip** [comment]
まあ一旦closeしてもよさそうですね。

**Comment by qryxip** [comment]
まあRustの`use`のスタイルは、できる表現が2015年から段々増えていったという事情もあって慣習の統一は多分難しいですね... 極端な話こんな書き方も今はできるわけで。

```rust
use {
    self::sub::C,
    super::B,
    crate::A,
    ::{
        anyhow::{bail, Context as _},
        itertools::Itertools as _,
        octocrab::{
            models::{
                repos::{Asset, Release},
                AssetId,
            },
            Octocrab,
        },
        std::{
            borrow::Cow,
            env,
            future::Future,
            path::{Path, PathBuf},
            sync::Arc,
            time::Duration,
        },
    },
};
```

Rustfmtが強権をふるえば話は別でしょうけど、version 1を宣言したRustfmtがデフォルトの挙動を変更できるはずがなく... 

Rust Analyzerが"Reporder import groups"みたいなcode actionを用意すれば統一のきっかけにはなるかもしれない、という程度ですね。
