### ISSUE TITLE
glob importの取り扱いについて考える

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#467]
## 内容

このようなワイルドカードインポートについて、やっているところ(主にqwertyさん)と避けているところ(主に私)が混在しているため、どちらかに統一します。

<https://github.com/VOICEVOX/voicevox_core/blob/44c4582401fb5c0fb2e7392469cdb10e737cbd6c/crates/voicevox_core/src/engine/mod.rs#L9>

以前の議論は<https://github.com/VOICEVOX/voicevox_core/pull/135#discussion_r878257691>という認識です。

Rustでは名前空間を何でもかんでもフラットにするような文化はそんなになく、別に止められているわけではないけど積極的に推進されてもいないはずです(ただし「外」から見える名前空間をフラットにするために子モジュール下から親モジュール下にre-exportされるといったことはよく行われます)。そのため私が書いた部分はqwertyさんのスタイルから外れた書き方をしていました。

ただこのスレッドで書かれている通り、このスタイルは別にアンチパターン認定されているわけではありませんし、SuitCaseさんも同意しています。そのため<https://github.com/VOICEVOX/voicevox_core/issues/466>とは逆に私が書いた部分をqwertyさんに合わせるのが丸いのかなと思っています。Rustの`use`は結構柔軟によしなに可視性を解決してくれるので、コードを読む分はともかく書く分には支障は出ないかと思います。
[Rustのモジュールを詳細に理解する(5) 可視性 - 簡潔なQ](https://qnighy.hatenablog.com/entry/2019/05/10/190000) (「可視性と `use`」を参照のこと)

### Pros 良くなる点

- このリポジトリにPRしに来た人が混乱しなくてよくなる

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by qryxip** [comment]
> Pythonなどではたしか＊は非推奨なのですが、Rustは特に無い感じでしょうか。

まあ非推奨ってことはなく、局所的に使う分にはむしろ一般的なんですが、qwertyさんスタイルレベルのはそんなに無い気がするのでissueにすべきか今まで悩んでました。

> インポート順序で読み込まれる関数が変わるなどの危険

Rustだとその場合「どっちかを名指ししてインポートしろ」というようなコンパイルエラーになったような...? ただしこういう場合は`a::S`が優先されるといったことはあったはず。

```rust
use a::S;
use b::*; // 中に`S`が入っている
```

どっちかというとデメリットとしてはリーダビリティの低下かと思ってます。

**Comment by Hiroshiba** [comment]
なるほどです。

難しい判断ですが、特に指標がないのであれば前に習うのが丸いのかなと思いました！！
なので最初に @qryxip さんが提案されていた形の、qryxipさんが書いたとこ周りを＊にするのが良さそうかかと！！

**Comment by qryxip** [comment]
この件、最近考えていることがあります。

`use super::*`って(stdを含む)dependencyの`use`も一緒に持って来るんですよね。「下」でしか使わないアイテムを「上」で`use`してもいいわけですし、**「上」と「下」の両方でしてもよいです**。例えば次のコードにおいて、`mod b`下の`use std::marker::PhantomData`は無くても動きますが、rustcはこれについて何の警告もしません。

```rust
mod a {
    use std::marker::PhantomData;

    type _A = PhantomData<()>;

    mod b {
        use std::marker::PhantomData;

        use super::*;

        type _B = _A;
        type _C = PhantomData<()>;
    }
}
```

名前空間をフラットにすると考えるならdependencyの`use`っていっそのこと一番上(lib.rs)に持って来るべきなんじゃないか?と思ったりもするのですが、そのようにしているコードって今まで見たことが無いんですよね。

まあこういうわけで、未だにちょっと引っ掛かってます。

**Comment by Hiroshiba** [comment]
`use super::*;`のほうが少人数での開発速度は上がると思います！
保守や新規参入者の学習曲線を考えると、直接指定したimportのが良いと思います。

なのでAPIなどが全部固まって開発が完了したあとに、１つ１つのimportに切り替えるのが良いのかなと。

ただまあこうすると新しいのの開発速度は下がるのと、いつ開発が完了したと判断するのかよくわからないので難しいですね･･･。
とりあえずこのまま共存し続けて、開発は無さそうだというタイミングで再考するのはどうでしょうか。

（あと、`*`でのimportと直接のimportが被る件については、既存開発者がなんか変だなと感じる以外は意外とデメリット無いなぁと思いました。
新規参入者のために、`*`でのimportは一旦そのままにして、直接指定するimportを増やしていっても良いかも？）

**Comment by qryxip** [comment]
> 新規参入

これは本当に重視したいところですね...なんとかしてバザール型にしたいという思いがあります。
