### ISSUE TITLE
Renovateを導入する

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#470]
## 内容

[Renovate](https://github.com/renovatebot/renovate)を導入します。

<https://github.com/VOICEVOX/voicevox_core/issues/289>で私は「Deps.rsのバッジが黄色くなったタイミングで手動でアップデートするのがちょうどいいのではないか」ということを言いましたが、今現在の状態のように、PRが溜まるとちょうどよいタイミングというのが中々訪れません。そのような状況でも**有無を言わさず**PRを自動的に作ることで、「やるべきタスク」として可視化するという効果が期待できるのではないかと思いました。

Renovateは聞いている限りだとRustとの相性も悪くないようです。Renovateの設定は多岐にわたるようで、 複数のパッケージの更新を一つのPRにまとめたりできるようです([例](https://github.com/sksat/kuso-subdomain-adder/pull/196#issuecomment-998198166))。[update\_rust\_toolchain](https://github.com/VOICEVOX/voicevox_core/blob/main/.github/workflows/update_rust_toolchain.yml)もRenovateに一本化できそうです([例](https://github.com/sksat/minecraft-whitelist-validator/pull/293))。

### Pros 良くなる点

- 依存ライブラリの更新を、「やるべきタスク」としてPRという形で可視化できる
- 更新を忘れがちなGitHub ActionsのActionも、自動的に更新のPRを受け取れる
- Renovateはリリースノートも抽出してくれてPRの本文で教えてくれる
    - ライブラリ数十個分のリリースノートを見に行くのは正直ちょっとだるいので、これは助かるかも

### Cons 悪くなる点

なし (PRの頻度をほどほどに抑えるという前提だと)

### 実現方法

私はまだRenovateを使った経験がないので、まずは私個人で実験をしつつ、丁度よい塩梅の設定を発見したらPRを作成する。

RustのOSSではあまりRenovateの採用を見ない(Depedabotなら見る)のですが、[ArkEdge Space Inc.のOSS](https://github.com/arkedge?type=source)と、そこのCI周りを設定しているであろう[sksat](https://github.com/sksat)という人のRustリポジトリとかが参考になるかなと思っています。
(地上で動くHTTPサーバーだろうが宇宙に飛ばすマイコンだろうがほぼRustで統一している会社らしいとのことで、以前から存在は知ってました)
> 我々は Rust という[プログラミング言語](http://d.hatena.ne.jp/keyword/%A5%D7%A5%ED%A5%B0%A5%E9%A5%DF%A5%F3%A5%B0%B8%C0%B8%EC)の生産性を信じており，[OBC](http://d.hatena.ne.jp/keyword/OBC) の[デバイスドライバ](http://d.hatena.ne.jp/keyword/%A5%C7%A5%D0%A5%A4%A5%B9%A5%C9%A5%E9%A5%A4%A5%D0)や高信頼性が必要な地上のシステムなど，ミッションクリティカルなソフトウェアはすべて Rust で開発しています． そして，それが持続できるように，日常的に Rust を書くエンジニアを増やしていきます．
>
> さらに，今後我々が開発するすべての [OBC](http://d.hatena.ne.jp/keyword/OBC) は，Rust が実行可能になります． つまり，Rust が動作しない[マイコン](http://d.hatena.ne.jp/keyword/%A5%DE%A5%A4%A5%B3%A5%F3)は，我々は決して採用しません．

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
なるほどです。
依存バージョンの更新は結構後回しになりがちですが、コアはテストが結構書かれているのでそこそこの頻度で更新してもよいのかなと思いました。
そういったツールの導入も試してみたいところです。

２〜３ヶ月に１回アップデートとかが良いかもですね！
あと、個人的にはrust toolchainの更新頻度も下げていいかなと思っています。
同じタイミングでtoolchainとcargo.tomlを更新するのはどうでしょう。
（特に使いたいものも無く、そのPRを毎回見るのもという感じなので･･･。
使いたい機能がある場合はアップデートするのはありだと思います）

**Comment by qryxip** [comment]
うーん私は月5〜10回のPRが飛ぶくらいの調整を考えてました...
(rust toolchainとかはCIが通れば`automerge`したりしながら)

(6週間おきの)RustのリリースごとのPRで、CIが通ったら強制的にautomergeというのはどうでしょうか?

**Comment by Hiroshiba** [comment]
なるほどぉ。
いろいろちょっと整理してきました。

まずそもそもライブラリを追従するですが、「脆弱性などがあったときにライブラリを更新しやすいため」だと思います。
また、ライブラリを更新するのはメンテナー的にはどうしても手間で、かつ自動PRはGithubでの検索効率を落とすので生産性が逆に下がると考えてます。

であれば、更新が億劫にならない中で一番長い頻度で、自動PR（可能ならautomergeも）が来るのが一番いいのかなと思いました！

で、おそらく追従が結構めんどくさくなりがちなライブラリで一番更新頻度が高いのは、VOICEVOX全体でelectronが該当しそうでした（要検証）。
electronのアプデ頻度は大体２ヶ月に１回です。（ちなみにEOLは半年強っぽかったです）
なので、VOICEVOX全体的に、２ヶ月に１回の頻度（例えば奇数月の1日目）でライブラリをアップデートすると良いのかなと思いました！！

コアのライブラリもこの頻度が良いと思いましたが、どうでしょうか。
（Rustなどの言語自体のアップデートは、本来はパッチアップデートが出たタイミングが良さそうに思います。）

**Comment by Hiroshiba** [comment]
さらに「こういうことができればいいな～」と思ったアイデアがあったのでメモです。

最新版に常に保ち続けるのは必ずしも正解ではないと思ってます。
というのも、最新版のライブラリにしかないようなバグを踏んでしまう可能性があるからです。
これは3日後に修正されるかもしれないけど、その3日間はバグってしまいます。

例えば2週間より前に出ているマイナーバージョンの最新版を取って来れるとこの問題を回避できそうだなとか思いました。
Renovateにそういう機能があれば非常に嬉しいかもです。

**Comment by qryxip** [comment]
`update_rust_toolchain`の置き換えとしてだけRenovateをお試し、というのもいいのではないかと最近思っています。

**Comment by Hiroshiba** [comment]
Renovateが導入されました 🎉 

が、動いて無さそう･･･？

**Comment by qryxip** [comment]
私の権限で設定画面を開けたのですが、dry-run的なモード(`Silent`)になっているっぽい...?

![image](https://github.com/VOICEVOX/voicevox_core/assets/14125495/25af0b1f-332d-43bc-8ba3-9d15fbcb1257)
![image](https://github.com/VOICEVOX/voicevox_core/assets/14125495/3b336ead-9155-4cd0-88ee-b425bd07a905)

**Comment by Hiroshiba** [comment]
runしたら60個くらいのプルリクエストが開かれそうになったので、1回権限を剥奪しました 🙇

**Comment by Hiroshiba** [comment]
Renovate再度ONにしてみます！

**Comment by Hiroshiba** [comment]
おーーーー！！うまいこといってそうですね！！！

- https://github.com/VOICEVOX/voicevox_core/pull/639

`Renovate Updates`一覧を見ても良い感じっぽかったです。Actionsもアプデしてくれてそうで便利そう。
<img width="1164" alt="image" src="https://github.com/VOICEVOX/voicevox_core/assets/4987327/f8ce6deb-5fc6-4741-82cf-c7c35ec6a845">

**Comment by Hiroshiba** [comment]
ちょっと相談させてください！

force pushのたびに通知が飛んできていて、多分このままだと通知で疲弊してしまうデメリットが大きいかもと感じました。
もちろんメリットとして、どれぐらいの差分があるのかがわかるのは良いことだと思いますが･･･。
メンテナはおそらく無視するようになってしまい、あと個人的には特にこのリポジトリをウォッチしてる人にネガティブになってしまうのが気になってます。

確かアップデートの頻度を2ヶ月に1回目標にしている感じでしたっけ。
であれば2ヶ月に1回プルリクエストが来る形でも目標は達成できるのかなと感じました。

もちろんそれ以外の思いがあると思うので、コメントで相談させていただいた次第です！！
良い落としどころがあればいいのですが･･･。
譲れないポイントとか覚えとかあったら知りたいです！
