### ISSUE TITLE
Voicevox coreのPythonスクリプトを実行する際にエラーが発生しています。

### ISSUE THREAD

**Issue by Nexus-Vediir** [VOICEVOX/voicevox_core#474]
こんにちは、Voicevox core を使ったスクリプトを実行しようとするとエラーが出てしまいます
```python
The given version [13] is not supported, only version 1 to 10 is supported in this build.
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `0x0`,
 right: `0x0`: Can not get ort api ptr.', C:\Users\runneradmin\.cargo\git\checkouts\onnxruntime-rs-6a272c20db5f1ac0\405f62f\onnxruntime\src\lib.rs:203:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
VoicevoxコアのどのバージョンがONNXのどのバージョンをサポートしているかを教えていただけますか？それが分かりません。
入力されたテキストを自動的に音声化するためにVoicevoxを使用するスクリプトを作成しようとしていますが、これを使用するのは正しい方法ですか？例がある方は教えてください。よろしくお願いします。

**Comment by sevenc-nanashi** [comment]
製品版ではOnnxRuntime 1.13.1が使われていますね。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
onnxruntimeは1.13.1が用いられています。

onnxruntimeのバージョン情報がドキュメントに書いていませんね･･･！！
ダウンローダーを利用したらダウンロードされるのが良さそうに思いました。
ちょっとissueを作成してみます。

もしその機構がない場合は、VOICEVOX ENGINE側に必要なバージョン情報があるので参考になれば！
https://github.com/VOICEVOX/voicevox_engine/blob/3afd8bf67f767ae0b5c67729bff1e25180675e60/.github/workflows/build.yml#L57
