### ISSUE TITLE
VoicevoxTtsOptions exclamation

### ISSUE THREAD

**Issue by alexfevery** [VOICEVOX/voicevox_core#476]
日本語下手ごめんなさい。VoicevoxTtsOptionsの内容は”enable_interrogative_upspeak”　入っています, これは質問(？)にとしてとっても役にたつですが、　exclamation(!)　の設定がありません。感嘆詞の抑揚 (怒りとか）どうすればいいですか?　
ありがとうございます

**Comment by Hiroshiba** [comment]
`！`の仕様は現状ありません。
