### ISSUE TITLE
ビルド手順の再考

### ISSUE THREAD

**Issue by Yosshi999** [VOICEVOX/voicevox_core#50]
## 内容

現状学習済みonnxモデルが手元にある状態でCPU版をpip installすることしかできない。cmakeの実行をsetup.pyから切り離し、手動でやらせた方がいいのかもしれない

他に方法があったら意見ください。

### ユースケース
* 手元に学習済みモデルがあり、CPU/GPU版core.dllをビルドしたのちpython moduleをインストールする
* 暗号化された公式のcoreモジュールをreleasesからダウンロードし、それに紐づけるようにpython moduleをインストールする
* (github actionで) core.dllをビルドしつつ、別途unit testを実行する (python setup.py test)
  * 現状python setup.py testをやるとcore.dllのビルドが走り、python moduleがビルドされ、unittestが実行されていて、core.dllのビルドが無駄

**Comment by Yosshi999** [comment]
そもそもcmake時にCPU/GPUの切り替えをしないという選択肢もあります。その場合はダウンロードしてきたonnxruntimeがcuda対応かどうかをruntimeで判断します

**Comment by Hiroshiba** [comment]
> そもそもcmake時にCPU/GPUの切り替えをしないという選択肢もあります。
