### ISSUE TITLE
wheelパッケージが大きすぎる

### ISSUE THREAD

**Issue by misogihagi** [VOICEVOX/voicevox_core#509]
## 内容

wheelファイルは700MB以上あります。
ダウンローダを使わずにvoicevox_coreを扱えればと思いますが、そのまま実行しようとしてもonnxが必要でエラーになり結局ダウンローダを使います。
どのみちダウンローダを使うならwheelに含めたモデルは使われないのではと思っています。
それならwheelパッケージからモデルを追い出せば？と思います。

## VOICEVOXのバージョン

0.14.3

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

## その他

以下は`docker run  -p 8888:88888  -u root jupyter/scipy-notebook jupyter-notebook --allow-root`で実行したときのjupyterノートブックです。
https://github.com/misogihagi/voicevox_core/blob/patch-6/example/jupyter/voice_vox.ipynb

**Comment by Hiroshiba** [comment]
いつのまにかwheelのパッケージ容量が下がって、モデルを別でダウンロードできるようになっているかも？

例

- https://github.com/VOICEVOX/voicevox_core/releases/tag/0.15.0-preview.8

**Comment by qryxip** [comment]
#522 ですね。#522からこのissueにlinkし忘れていました。

**Comment by Hiroshiba** [comment]
あ、ほんとですね！！　じゃあ完了したということでcloseで･･･！！
