### ISSUE TITLE
Question speed_Scale VoiceVox Core

### ISSUE THREAD

**Issue by Cristian-Araya-Cubillos** [VOICEVOX/voicevox_core#526]
## 質問の内容

ちょっと質問なのですが、AudioQueryでspeed_scale変数が見つからないのですが、どうすれば音声速度を上げることができるのでしょうか？
私はpythonとVoiceVox_Coreライブラリーを使用しています

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [x ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
AudioQueryにはspeed_scaleが存在するはずです。もしかしたら使ってるコアのバージョンが古いのかも？

https://github.com/VOICEVOX/voicevox_core/blob/b8c1b316203a0963ce3d3aca787fd392cceba930/crates/voicevox_core/src/engine/model.rs#L40

Pythonの場合は得られたAudioQueryの`.speed_scale`を変更すればOKです。
C APIの場合は得られた`audio_query_json`をjsonとして解釈した後、`speed_scale`の中身を変更すればOKです。

分からなかったらまたコメントしてください！ 👍

**Comment by Cristian-Araya-Cubillos** [comment]
バージョン0.14.3を使っているのですが、models.pyには以下のように書かれています：
![image](https://github.com/VOICEVOX/voicevox_core/assets/80790384/bbf263b0-7a4c-4f50-8e44-867120acd269)

で、Audio_queryを呼び出すと、以下のようになります：
![image](https://github.com/VOICEVOX/voicevox_core/assets/80790384/536c7349-5b28-497f-b743-d56a95370812)

今、この行を追加したのでテストしてみようと思いますが、もし失敗があれば、アドバイスをいただければと思います、よろしくお願いします。
![image](https://github.com/VOICEVOX/voicevox_core/assets/80790384/3e0b4ebb-ecf6-4f55-af11-028368c03994)

**Comment by sevenc-nanashi** [comment]
```py
audio_query = core.audio_query(text, speaker_id)
audio_query.speed_scale = 2.0
```
のようにします。
