### ISSUE TITLE
onnxruntime problem

### ISSUE THREAD

**Issue by Cristian-Araya-Cubillos** [VOICEVOX/voicevox_core#530]
## 質問の内容

onnxruntimeファイルはどこにありますか？
![image](https://github.com/VOICEVOX/voicevox_core/assets/80790384/83815908-e204-4496-b631-9d936fdce158)

このコードを使用する
![image](https://github.com/VOICEVOX/voicevox_core/assets/80790384/4d8fb526-3b2d-4152-9e81-34a5a937d79d)

しかし、私はバージョン1.15.1を持っています。どうすれば1.13.1を私の持っているものに変更できますか？

0.14.4

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ x] Linux

**Comment by Hiroshiba** [comment]
in release zip
