### ISSUE TITLE
build.ymlのonnxruntimeがビルドできない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#54]
## 不具合の内容

linuxのarm用（？）にonnxruntimeの自動ビルドを用意しているのですが、エラーで落ちてしまうっぽいです。

### 現象・ログ

https://github.com/VOICEVOX/voicevox_core/runs/4641665798?check_suite_focus=true

![image](https://user-images.githubusercontent.com/4987327/147473418-f4b3ae73-7146-41f1-9207-4b28e3fb4477.png)

### 再現手順

forkしてreleaseタグを作ってビルドする

## その他

プライベートリポジトリでもビルドしているのですが、通らなくてちょっと困っています。
別途onnxruntimeをビルドするリポジトリを作ってそちらに移してしまってメンテするのもありなのかなと感じました。

**Comment by Hiroshiba** [comment]
@aoirint もし簡単に直せそうだったら修正お願いできるととても嬉しいです・・・！

とりあえず該当ビルドをパスできるようにしようかなと思います。

**Comment by Hiroshiba** [comment]
動的にmatrixを変更するのがちょっと泥沼になりそうだったので引き返してきました。
https://swfz.hatenablog.com/entry/2021/06/29/195359

別リポジトリにきりだそうとしてみます・・・！

**Comment by Hiroshiba** [comment]
別リポジトリを作って、onnxruntimeをビルドする部分を切り出してみました。

- https://github.com/VOICEVOX/onnxruntime-builder/pull/1

**Comment by Yosshi999** [comment]
checkoutで落ちるのは大分奇妙ですね。アクセスしているリポジトリは実在するようです。
https://www.githubstatus.com/ をみるとGitHub Actionの調子が悪いようなので放っておけば勝手に直るかもしれません
> Investigating - We are investigating reports of degraded performance for GitHub Actions.
Dec 27, 13:20 UTC

**Comment by Hiroshiba** [comment]
おお、なるほどです！！　ステータスチェックしておけばよかったです。
別リポジトリにして管理しておくのは、たしか当時もorganizationできたら分離したいと思っていたことだったので、このまま別リポジトリにしちゃおうかなと思います。

**Comment by aoirint** [comment]
Yosshi999さんの指摘通り、GitHub Actionsの一時的な不調だと思いました。

ONNX Runtimeのビルドはこのまま別リポジトリに分けてしまっていいと思います。

voicevox_core側では、分けたリポジトリのReleaseからビルド済みのarmhf用ONNX Runtimeをダウンロードしてくるようにすればいいかなと思いました！

armhf対応を入れたのはわたしなので、ENGINEのONNX対応が終わったら調整してみたいと思います（他にやってもいいという方いればおまかせします）。

**Comment by aoirint** [comment]
ヒホさんONNX Runtimeのリリース作成ありがとうございます。

いくつか修正したいところがあったので、いったん書いておきます。

本家のONNX RuntimeのReleaseでは圧縮ファイルの中の一番上はディレクトリ（圧縮ファイルのファイル名と同じ名前）になっているので、それに合わせたいです（core側の自動ビルドはこれが前提になっています）。

形式はURL末尾の拡張子で分岐させているのでzipでもtgzでも動作しますが、本家のLinux版はtgzになっているので、Releaseではtgzにしておきたいです。

core側では、同一リポジトリでビルドしたONNX Runtime用にmatrixにonnxruntime_artifact_nameを用意していましたが、別リポジトリでビルドすることになったので不要になりました。coreのarmhfビルドを入れるときに、これを使った処理は消してしまってよさそうです。

**Comment by Hiroshiba** [comment]
異論ないです、使いやすいようにしちゃいましょう！

**Comment by Hiroshiba** [comment]
@aoirint プルリクマージしました！
releasesのタグはどうするのが都合良さそうでしょうか。
以前作った1.9.1を一回消してまた作り直すか、1.9.1.1みたいにさらに刻むかなどを考えています。
（どちらでもよければ後者にしようかなと思ってます）

**Comment by aoirint** [comment]
> タグ

1.9.1.1みたいに刻むのがいいかなと思いました。キャッシュでURLを使っていたと思うので、バージョンは変えたいと思いました。
