### ISSUE TITLE
ダウンローダーがクラッシュする

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox_core#572]
## 不具合の内容

0.15.0-preview.5のdownload-linux-64で0.15.0-preview.5をダウンロードしようとするとクラッシュします。

### 現象・ログ

```
❯ ./download-linux-x64  --version 0.15.0-preview.5
 INFO 対象OS: linux
 INFO 対象CPUアーキテクチャ: x64
 INFO ダウンロードデバイスタイプ: cpu
 INFO ダウンロードvoicevox_coreバージョン: 0.15.0-preview.5
voicevox_core-linux-x64-cpu-0.15.0-preview.5.zip        ⠄ Inflating...
open_jtalk_dic_utf_8-1.11.tar.gz                          Done!
強制終了
[ble: exit 137]
```

### 再現手順

上のコマンドを実行する。

### 期待動作

ダウンロードされ、voicevox_core下に展開される。

## VOICEVOXのバージョン

0.15.0-preview.5

9c100df でも確認出来ました

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux (Ubuntu、`5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`）

## その他

（なし）

**Comment by sevenc-nanashi** [comment]
WSLを再起動したら直りました。なんでだろう…

**Comment by Hiroshiba** [comment]
なるほどです！！
WSLで問題が起きる可能性があるのは有用な情報に感じました。次に迷われた方がすぐ解決できるはずなのでissue作成ありがとうございます！
