### ISSUE TITLE
xcframeworkにmodule.modulemapを同梱して欲しい

### ISSUE THREAD

**Issue by fuziki** [VOICEVOX/voicevox_core#578]
## 内容

xcframework対応ありがとうございます！
とても嬉しいです！

ただ、0.15.0-preview.5のxcframeworkには、module.modulemapが同梱されておらず、SwiftからHeaderを見つけることができません。
そこで、xcframeworkにmodule.modulemapを同梱して頂けるとiOSで開発する上で大変助かります。

参考：[https://medium.com/@kennethyoel/a-swiftly-oxidizing-tutorial-44b86e8d84f5](https://medium.com/@kennethyoel/a-swiftly-oxidizing-tutorial-44b86e8d84f5)

module.modulemapの例：

```
module VoicevoxCore {
  header "voicevox_core.h"
  export *
}
```

xcframeworkの構造：

```
voicevox_core-osx-arm64-cpu-0.15.0-preview.5.zip
voicevox_core.xcframework
├── Info.plist
├── ios-arm64
│   ├── Headers
│   └── libvoicevox_core.dylib
└── ios-arm64_x86_64-simulator
    ├── Headers
    └── libvoicevox_core.dylib

module.modulemap追加後
voicevox_core.xcframework
├── Info.plist
├── ios-arm64
│   ├── Headers
│   │   ├── voicevox_core.h
│   │   └── module.modulemap
│   └── libvoicevox_core.dylib
└── ios-arm64_x86_64-simulator
    ├── Headers
    │   ├── voicevox_core.h
    │   └── module.modulemap
    └── libvoicevox_core.dylib
```

### Pros 良くなる点

* iOSでvoicevox_coreを容易に利用できるようになります。
  * 具体的にはPackage Managerにzipのパスを入れるだけで、voicevox_coreに含まれる関数を利用できるようになります。

```swift
    targets: [
        .target(
            name: "MyApp",
            dependencies: [
                .target(name: "onnxruntime"),
                .target(name: "VoicevoxCore"),
            ]
        ),
        .binaryTarget(
            name: "onnxruntime",
            url: "https://github.com/VOICEVOX/onnxruntime-builder/releases/download/X.X.X/onnxruntime.xcframework.zip",
            checksum: "hash"),
        .binaryTarget(
            name: "VoicevoxCore",
            url: "https://github.com/VOICEVOX/voicevox_core/releases/download/X.X.X/voicevox_core.xcframework.zip",
            checksum: "hash"),
    ]
```

### Cons 悪くなる点

* module.modulemapの管理が必要になります。

### 実現方法

`xcodebuild -create-xcframework` の `-headers` にヘッダファイルではなく、ヘッダファイルとmodule.modulemapが含まれるディレクトリを指定すると、modulemapが同梱され、Swiftからヘッダを見つけることができるようになります。

https://github.com/VOICEVOX/voicevox_core/blob/9c100df86803234e64267796da0be0c9da2c3b22/.github/workflows/build_and_deploy.yml#L365-L370

## VOICEVOXのバージョン

0.15.0-preview.5

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by y-chan** [comment]
Issueありがとうございます！
なるほど、modulemapというものがあるといいんですね...!
おそらく、modulemapを管理するコスト自体はそこまでかからないだろうなーと思っている(変更が加わることがまずないはずな)ので、追加すること自体は問題ないと思います！
置くとしたらどこがいいでしょうかね...`voicevox_core/crates/voicevox_core_c_api/include/`とか...?

実現方法までわかっている状態だと思いますので、良ければプルリクエスト(PR)を作成してみませんか...?:eyes:
PRが取り込まれた際には、VOICEVOXの貢献者としてお名前を記載させていただきます...!

**Comment by fuziki** [comment]
ありがとうございます！
ぜひPR作成までやらせてください

ただ、あまりrustのメジャーなディレクトリ構成に自信がないので、modulemapの配置場所をご相談できると助かります。
`crates/voicevox_core_c_api/include/` にmodulemapを配置で良いでしょうか？

**Comment by Hiroshiba** [comment]
なるほど、単純にファイルを置いてビルド時に指定したら良い感じなんですね！
僕もどこに置けば良さそうかいまいち自信がないです･･･。
`./crates/voicevox_core_c_api/include/`でも良さそうだし、`./build_util/`でも良さそうだし、`./crates/voicevox_core_c_api/misc/`とか作っても良さそうだし、`.github/workflows/build_and_deploy.yml`内でファイル生成やっちゃってもそこまで悪くなさそうだし･･･。

@qryxip さん的にどうでしょう 🙇

**Comment by qryxip** [comment]
include/voicevox_core.hは #493 からコミットされるようになった自動生成(`linguist-generated`)のファイルです。"include"という名のディレクトリの下である必然性は特にありませんし、このディレクトリに何か別のものが混入しても今現在においては問題は起きないでしょう。

あと[swift-bridge](https://docs.rs/crate/swift-bridge)によるvoicevox_core_swift_apiを誕生させるというアイデア(#550 。[Javaは今レビュー段階](https://github.com/VOICEVOX/voicevox_core/pull/558))がありますが、今のところはvoicevox_core_c_api下に置いても問題無いと思います。

ただmodule.modulemapが"include"という名のディレクトリの下にあるべきかというと微妙な気もするので、/crates/voicevox_core_c_api/xcframework/Headers/module.modulemapみたいな位置に置いておいて`build_and_deploy`上で`cp`して組み立てる、というのがよいかもしれません。

**Comment by Hiroshiba** [comment]
なるほどです、賛成です！！
追加の案で`modulemap`内にコメントがかければそのファイルが何なのかを、無理であればそのディレクトリにREADMEを置いてファイルの説明があると追いやすそうかもと思いました！

**Comment by fuziki** [comment]
ありがとうございます！
PR作成したので、確認お願いいたします🙇
https://github.com/VOICEVOX/voicevox_core/pull/579
