### ISSUE TITLE
VVMのマニフェストの形式の再考

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#581]
## 内容

今現在、VVMのmanifestはこのような形になっています。

もしもこの形式を考え直すなら、[v0.15のリリース](https://github.com/VOICEVOX/voicevox_core/issues/545)より前に行うのが最善です。

```json
{
  "manifest_version": "0.0.0",
  "metas_filename": "metas.json",
  "decode_filename": "decode.onnx",
  "predict_duration_filename": "predict_duration.onnx",
  "predict_intonation_filename": "predict_intonation.onnx",
  "style_id_to_model_inner_id": {
    "302": 2,
    "303": 3
  }
}
```

私がとりあえず思ったのは次の2つです。

1. `manifest_version`はSemVerでなくてもよいかもしれません。

    edition的な概念が将来生まれるかもしれませんが、その時は別の概念にすればよいと思います。

    ```json
    {
      "manifest_version": 2,
      "manifest_edition": "3-model"
    }
    ```

2. `style_id_to_model_inner_id`について、"model_inner_id"ではなく"inner_voice_id"とかでもよいかもしれません 。

    <https://github.com/VOICEVOX/voicevox_core/pull/551#discussion_r1284943586>

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
> manifest_versionはSemVerでなくてもよいかもしれません。

これはそうだと思います。
日付などの手もあるかもしれませんが、普通に整数値にしてインクリメントしていく形が良さそうに思いました。

> style_id_to_model_inner_idについて、"model_inner_id"ではなく"inner_voice_id"とかでもよいかもしれません 。

`style_id_to_inner_voice_id`で！！

**Comment by qryxip** [comment]
追加で:

3. VVMにもUUIDを振った方がよいのでは?

**Comment by qryxip** [comment]
4. ファイルが生のonnxなのか、復号が必要なのかのプロパティもあった方がよいのではないか

**Comment by Hiroshiba** [comment]
> VVMにもUUIDを振った方がよいのでは?

これちょっと考えたんですけどどっちに倒そうか難しい感じです 😇 
VOICEVOXの都合だけ考えると、必要になるのかどうかがわからず、であれば必要になった時に足す形が一般的には良いのかなと。。

@y-chan さん的にSHAREVOXやユーザーニーズを考えたとき、使うあるいは使いそうだったりであれば是非足した方が良いかなと！！

（ちなみにVOICEVOX的には「使うかも」って感じです。これくらいの淡い温度感で用意していいのかどうかがわからない。。）

**Comment by Hiroshiba** [comment]
> 4. ファイルが生のonnxなのか、復号が必要なのかを示すプロパティもあった方がよいのではないか (filetype = "onnx" | "encrypted"のような形で)

なるほどです！！
OSS側で対応するのは暗号化有無ぐらいだと思うので、`filetype`ではなく`isEncrypted`のが良いかも？
（ブランドエディションや暗号化方法にもし違いがあっても、それはこの引数じゃなく他に引数を足す形を取ると綺麗そうなので）

**Comment by y-chan** [comment]
コメント遅くなりました！

VMM Manifestについてですが、SHAREVOXだとUUIDがライブラリを読み込むためのキーとして用いているので、あると嬉しい(VMM形式になるとファイル名を引数にとってモデルを読み込むことになるのでおそらくいらない)かなぁと思いました。
あと欲しいとすれば、VMMの名前でしょうか。
ボイボ寮n期生のような名前("name")があると嬉しいのかなとかはちょっと思いましたが、それくらいな感じですかね...!

**Comment by Hiroshiba** [comment]
あ〜　たしかにnameはあると便利かも。賛成寄りです。

**Comment by qryxip** [comment]
UUIDについてですが、今は[nanoid](https://docs.rs/crate/nanoid)でIDとなる文字列を生み出してそれを`VoiceModelId`としているので、それをUUIDにすればVOICEVOX側としても綺麗になるかなと思います。

**Comment by qryxip** [comment]
一つ追加で思い付きました。TFLite使うならこれも要るかも?

5. `runtime` (`"torch" | "onnxruntime" | "tflite"`)

**Comment by Hiroshiba** [comment]
@qryxip おお、なるほどです！
これは必要になってから足せるから、必要になってからでも良いかも？
（何が必要になってくるか本当にわかんないので、今はシンプルにしときたいという気持ちはあります）

**Comment by Hiroshiba** [comment]
こちらのタスクをまとめ直しました。やることは次の3点かなと。

1. `vvm_format_version`周り
	- manifest.jsonに`vvm_format_version`を足す
	- ↑のバリデーションを書く（ファイルのバージョンが、自分の知っているものと違っていたらエラーという挙動で良いはず）
	- ↑テストを書く
2. `style_id_to_model_inner_id`→`style_id_to_inner_voice_id`
3. UUID足す（オプションだけどやっといた方が良さそう）

それ以外はマストじゃないかなという気持ちです（ずれていたら教えてください）。

２は多分僕でも簡単にできて、１も値を足すぐらいだったらできる気がするのですが、バリデーションコードを多言語ラッパーできる形で書いたり、３の`UUID`足したりするのはだいぶ苦戦する気がします。
とりあえず自分がプルリクエスト作る場合は２と１ちょっとみたいな感じを目指そうと思います 🙇

**Comment by qryxip** [comment]
> １も値を足すぐらいだったらできる気がするのですが、バリデーションコードを多言語ラッパーできる形で書いたり、

`Manifest`に触るのは内部だけのはずなので、他言語のは要らない気がします。
serdeレベルのやつなら、テスト含めてこんな感じでしょうか。

<details>
<summary>一例</summary>

```rust
use serde::{de, Deserialize, Deserializer};

#[derive(Deserialize)]
struct Manifest {
    vvm_format_version: ManifestVersionV1,
    // …
}

struct ManifestVersionV1;

impl<'de> Deserialize<'de> for ManifestVersionV1 {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        return deserializer.deserialize_str(Visitor);

        struct Visitor;

        impl<'de> de::Visitor<'de> for Visitor {
            type Value = ManifestVersionV1;

            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
                formatter.write_str("a string")
            }

            fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
            where
                E: de::Error,
            {
                match v {
                    "1" => Ok(ManifestVersionV1),
                    v => Err(E::custom(format!("未知の`vvm_format_version`です: `{v}`"))),
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use rstest::rstest;

    use super::Manifest;

    #[rstest]
    #[case("{\"vvm_format_version\":\"1\"}", Ok(()))]
    #[case(
        "{\"vvm_format_version\":\"2\"}",
        Err("未知の`vvm_format_version`です: `2` at line 1 column 25")
    )]
    fn vvm_format_version(
        #[case] input: &str,
        #[case] expected: Result<(), &str>,
    ) -> anyhow::Result<()> {
        let actual = serde_json::from_str::<Manifest>(input).map_err(|e| e.to_string());
        let actual = actual.as_ref().map(|_| ()).map_err(std::ops::Deref::deref);
        assert_eq!(expected, actual);
        Ok(())
    }
}
```

</details>

```console
Error:
   | {
 2 |   "vvm_format_version": "2"
   |                            ^ 未知の`vvm_format_version`です: `2` at line 2 column 27
   | }
```

エラー内容が多少雑でいいならこれでもOK。
(確かSHAREVOX COREが今こうなっているはず)

```rust
use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    vvm_format_version: ManifestVersion,
    // …
}

#[derive(Deserialize)]
enum ManifestVersion {
    #[serde(rename = "1")]
    V1,
}
```

(あとこういうのは`1`ではなく`"1"`とするのが一般的らしい?のでそうしています)

> ３の`UUID`足したりするのはだいぶ苦戦する気がします。 とりあえず自分がプルリクエスト作る場合は２と１ちょっとみたいな感じを目指そうと思います 🙇

まずRustについてですが、IDを文字列ではなく[`Uuid`](https://docs.rs/uuid/1/uuid/struct.Uuid.html)にし、

<https://github.com/VOICEVOX/voicevox_core/blob/c8f5c3a02dd692a5c4fc250ed392dd1bc3b8a4a1/crates/voicevox_core/src/voice_model.rs#L17>

[nanoid](https://docs.rs/crate/nanoid)でIDを発行しているところを削除して`Manifest`で持つようにするだけでいいと思います。

<https://github.com/VOICEVOX/voicevox_core/blob/c8f5c3a02dd692a5c4fc250ed392dd1bc3b8a4a1/crates/voicevox_core/src/voice_model.rs#L66>

C/Python/Javaについては、`UserDict`の単語IDの取り回しと同様にすればいいと思います。
(別に文字列のままでもいいのですが、`speaker_uuid`のような事情もないし`UserDict`との統一性を出した方がよいと思いました)

**Comment by Hiroshiba** [comment]
@qryxip ありがとうございます！！
勉強も兼ねて挑戦してみたいという気持ちがあります！
ただ時間がしばらく取れなさそう（他に優先度の高いボイボのタスクが多い）なのでかなり先になる気がしています。
もしリリースタイミングが決まった場合は、簡単なところだけ実装してしまって難しそうなところは0.16以降に後回しになると思います。
なので、現状でももし他にできそうな方がいたらお任せしたいです 🙏

**Comment by qryxip** [comment]
@Hiroshiba さん、 @y-chan さん、 @qryxip の3名で行った2024-03-04のミーティングから:

- <https://github.com/VOICEVOX/voicevox_core/issues/581#issuecomment-1837168657>に従う
- serdeの機能が絡むため、ここにいる3人の中では @qryxip が適任

**Comment by qryxip** [comment]
あ、最後のPRからlinkしてなかった。 #794, #795, #796 により完遂されました。

**Comment by Hiroshiba** [comment]
ありがとうございます！！🙇
