### ISSUE TITLE
C API用のzipファイルからmodelディレクトリをなくし、別でmodelダウンロード可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#596]
## 内容

C API用のdllが入ったZIPファイルの中には、音声合成するためのモデルが大量に含まれている700MB程度のmodelディレクトリが同梱されています。
dllが含まれているZIPファイルからこのmodelディレクトリをなくし、別でダウンロード可能にしておくと色々都合が良さそうです。

例えばこちらの課題ある通り、全部のモデルをダウンロードするのではなく、必要なモデルだけをダウンロードする需要があったりします。
これを実現するためには、とりあえずまずはZIPファイルの中からモデルディレクトリを無くす必要がありそうです。

- https://github.com/VOICEVOX/voicevox_core/issues/566

### Pros 良くなる点

モデルファイルを別途ダウンロード可能になる。
OSや環境ごとにモデルの同梱が不要になるのでビルドが早くなる。

### Cons 悪くなる点

設計が自明ではない。

### 実現方法

色々やり方がありそうですが、変更量が小さくなるようにまずは以下の流れを考えてます。

1. dll用のZIPにモデルディレクトリを同梱しないようにする
2. 別でモデルディレクトリをZIPファイルとしてリリースする
3. ダウンローダー内でモデルディレクトリZIPファイルをダウンロード＆展開可能にする

この形であれば、ZIPファイルダウンロード＆ダウンローダーを実行した結果が、変更前と変更後で同じになると思ってます。

## その他

0.15リリースに間に合わせられると良さそうかも。

- https://github.com/VOICEVOX/voicevox_core/issues/545

ちなみにPython wheelの中からモデルディレクトリがすでに消えているっぽい･･･？

- https://github.com/VOICEVOX/voicevox_core/issues/509

**Comment by Hiroshiba** [comment]
@qryxip みたいなこと考えているんですがどう思われますか･･･？ 👀 
多分発展系として色々ありそうではありますが、とりあえず第1弾として分離だけやっちゃおうかなと。
問題なさそうだったら取り組んでみようと思ってます！

**Comment by qryxip** [comment]
ひとまず分離するというのはよいと思います。
(SHAREVOXも分離された状態でReleaseに上がってます)

**Comment by Hiroshiba** [comment]
メモです

* READMEの分離どうするか
	* コアライブラリ側のREADMEは今まで通り配布
	* 音声モデル（modelディレクトリ）のREADMEはそのディレクトリの下に配置
* 用語
	* コア内ではVVMを音声モデルと呼んで案内する
	* [この用語集](https://github.com/VOICEVOX/voicevox_project/issues/27#issuecomment-1509711845)に従う
	* コアの中で音声モデルと呼んでいることと、他の場所では音声ライブラリと呼んでいることがややこしくないか・異常が起きていないかを確認する必要がある
