### ISSUE TITLE
downloadクレートの名称をdownloaderにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#607]
## 内容

voicevox_coreクレートは、自身を意味する`voicevox_core`を名乗っていますが、downloaderは`download`クレートになっています。
現`download`クレートも自身を意味する`downloader`に変えたほうがわかりやすい気がしました。

### Pros 良くなる点

クレート内容とクレート名が同じになる。
補助的な効果として`cargo -p download`など初学者にとってちょっと分かりにくいコマンドじゃなくなる。

### 実現方法

クレート名を変更してREADMEなども変更。

## その他

`download`コマンドの名称を`download`から`downloader`にすべきかはちょっと分かりませんでした。
それでもいいと思うけれども変えるほどではないかも。

**Comment by Hiroshiba** [comment]
@qryxip さん、 @y-chan さん的にはどうでしょう･･･？

**Comment by y-chan** [comment]
確かに、クレート名と本来の名前が合致していないので、変えちゃっていいのでは無いかなと思いました！
他所から依存されているライブラリではないですし、名称変更を行うのは特に問題は無いかなという感じです。

**Comment by qryxip** [comment]
よいと思います。

**Comment by Hiroshiba** [comment]
タイトル変えておきます！
📝 docsのファイル名も変える必要がありそう。

**Comment by Hiroshiba** [comment]
こちらやっちゃおうと思います！

**Comment by Hiroshiba** [comment]
@qryxip @y-chan 
この際に`download.exe`を`downloader.exe`にしてしまおうか迷ってます 😇 

実行バイナリの名称は、何をするかではなく、何をするものなのかを書いた方が良いと思ってます。
例えば喋る機械の名称は「スピーカー」であり、「スピーク」ではない。
ので、どちらかというと正しいのはdownloaderかなと。

ただ、破壊的変更するべきもののほどなのかが若干自信が無く･･･。
ちなみに置き換え作業の面では、全部downloaderにしちゃった方が間違えにくいと思います 😇

**Comment by qryxip** [comment]
個人的にはバイナリ名は`download(.exe)`のままでよいのではと思っています。

"builder.sh"のような名前より"build.sh"の方が多数ですし、Windows/Unix両方において、バイナリ名は"コマンド名"と捉えた方がよいのではと思っています。

**Comment by Hiroshiba** [comment]
なるほどです！
確かにこのバイナリがもっと物感がある（例えばguiがあるとか）んだったらダウンローダーの方が正しそうですが、これはコマンド感が強いのでUnixの慣習に倣ってdownload.exeでも良さそうに思いました。

今ドキュメントでは`downlaodコマンド`（あるいは`download`実行バイナリ）を指して`ダウンローダー`と呼んでいてどっちやねんっていう感じなのですが、まあ引き続きその感じでドキュメントを書いていけば問題なさそうですかね。

**Comment by Hiroshiba** [comment]
`download`コマンド（＝`download`実行バイナリ）を指して「ダウンローダー」と呼ぶ形で良さそうに感じたので、そっちに合わせようと思います！
