### ISSUE TITLE
ヘッダやバイナリにバージョン情報を埋め込む

### ISSUE THREAD

**Issue by Yosshi999** [VOICEVOX/voicevox_core#65]
## 内容
恐らく現状core.hや実装にバージョンを返す関数がなく、またpythonモジュールがビルド時にバージョンを埋め込むために参照している`/VERSION.txt` が更新されずそのままになっている。
DLLとpythonモジュールのバージョン情報は一致している方が良いと思うので、そのあたりの修正方法やVERSION.txtの処置を決めてほしい。

### Pros 良くなる点
* ファイル名のパース以外の方法で、外部からバージョンを参照できるようになる
* pythonモジュールとDLLとreleaseページのバージョン名の一致

### Cons 悪くなる点
* リリース手順が増える

### 実現方法
* pythonモジュール&DLLのビルド時にいずれもVERSION.txtを参照して埋め込む
* core.hに埋め込み、pythonモジュールはそれを見る

**Comment by Hiroshiba** [comment]
issueありがとうございます！
VERSION.txtが存在することが認識から外れていました。

リリース時にVERSION.txtを更新するのは結構忘れがちで、仕組みで解決したいなと感じています。
VERSION.txtは、リリースビルド時にtag名（0.9.0とか0.10.prview.1とか）が書き込まれる形にし、github上でメンテナンスするときは`latest`になっているのが良いのかなと感じています。

エンジン側にも似た問題があったりします。

- https://github.com/VOICEVOX/voicevox_engine/issues/274

**Comment by Hiroshiba** [comment]
build時にバージョンファイルを作る部分があったのでメモ

https://github.com/VOICEVOX/voicevox_core/blob/5db2faef093071a534738849c164282f32e83048/.github/workflows/build.yml#L272

**Comment by Hiroshiba** [comment]
ちょっとどうすれば良いのか迷っています。

1. 一番うれしいのは、バージョン更新リリース時に何も設定しなくても上手くいく形
2. 他にも問題が発生しないようなものだと嬉しい

setup.pyでgithubコード上のVERSION.txtを参照するようにすると、release tagを作るたびにVERSION.txtを更新する必要があり、↑の1が叶わなそうです。

setup.pyで参照するファイルを`build時にバージョンファイル`に合わせる方が良いのかなと感じました。
ただこうすると、ソフトウェアビルド時にコアなりエンジンなりのバージョンファイルがどうしても入り乱れるので、2が叶わない気もします。

コアとしてとれる最善策は、 @.Yosshi999 さんが提案されている`core.hに埋め込み、pythonモジュールはそれを見る`かもと思いました。

コード側でVERSIONをdefineしておいて、cmakeでバージョンを与えられるようにし、ビルド時に`env.BUILD_IDENTIFIER`を与えるという流れはどうでしょう？

**Comment by qryxip** [comment]
@Hiroshiba `compatible_engine`にバージョン情報を持たせることってありますか? 最近は<https://github.com/VOICEVOX/voicevox_engine/pull/1110>もあったし、そのような構想はもう無いと認識していますが、そうであればこのissueはcloseできると思います。

**Comment by Hiroshiba** [comment]
@qryxip 確認ありがとうございます！！

closeが良さそうな気がしました！

そもそもRustに変わったあたりでバージョン情報 返す C API は 実装済みで、かつ自動的にビルド時のバージョン情報が埋め込まれるようになっています。
で、 @qryxip さんのおっしゃる通り`compatible_engine`からはバージョン情報を返していませんが、そもそもこれは目的が互換性のためで、過去にバージョン情報を返していなかったんだったら改めて実装する必要はなさそうかなと。

ということでクリア済みの認識なので、closeします！
