### ISSUE TITLE
READMEのサンプルを、製品版のものを実行する用途のコードに変更する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#66]
## 内容

READMEにpythonで実行するサンプルコードが書かれていますが、こちらは`models`ディレクトリにあるダミー用のモデルをつかって音声合成するサンプルコードになっていると思います。
https://github.com/VOICEVOX/voicevox_core/tree/5db2faef093071a534738849c164282f32e83048#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%81%AE%E5%AE%9F%E8%A1%8C

以前のREADMEでは製品版のものを使うコードがサンプルとして書かれていました。
https://github.com/VOICEVOX/voicevox_core/tree/0.9.4#%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%89%E3%81%8B%E3%82%89%E5%AE%9F%E8%A1%8C

ユーザーが知りたいのはたぶん以前のものと同じ、製品版を使うサンプルコードだと思うので、変更すると良さそうに感じました。

こちらの方のツイートを見て気づきました。
https://twitter.com/Lapis256/status/1484107704398651398

### Pros 良くなる点

製品版の音声合成ライブラリを利用するサンプルが伝わる

### 実現方法

サンプルには製品版を使うサンプルを書いて、別で「ビルド」みたいな項目を作ってそこにcmakeを使う例を書くのが良いかなと思いました。

## その他

@Oyaki122 @Yosshi999 意見伺えると嬉しいです！

**Comment by Yosshi999** [comment]
賛成です。ついでにexample/pythonのcore.pyd, core.pyxも今は使われていないので消してしまいたいですね
