### ISSUE TITLE
同期版APIを作る？

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#662]
## 内容

Python版のAPIを眺めていたのですが、普段駆け出しのPythonユーザーがおそらく1回も見たことがないであろうasyncが必須になっていることに気づきました。
asyncはPythonのどの標準ライブラリにもおそらく現れておらず（？）、しばらくプログラミングをしていた方ですら扱い方を知らない人の方がおそらく多いくらい難しいと思います。
なんとなくの直感ですが、VOICEVOX COREを手に取ってくれたプログラマーの3割は脱落しそうかなと･･･。

可能であれば同期版APIを提供してあげるとユーザ数は飛躍的に伸びるだろうなと思いました。
どういう方法があるか、やるやらも含めて議論できるといいのかなと思い、issueを立ててみました。

### Pros 良くなる点

初学者に優しくなる

### Cons 悪くなる点

下手したら関数の量が倍になる

### 実現方法

Rust APIで同期版を作り、非同期が難しそうな言語では同期版を提供する。
（非同期が一般的な言語ではasync版だけでもいいかも･･･？）

## VOICEVOXのバージョン

0.15より後？

## その他

0.15では非同期版だけの提供でいいのかなと思いました！
できる限り優しいexampleにしてあげたいですね･･･！

**Comment by sevenc-nanashi** [comment]
> Rust APIで同期版を作り、非同期が難しそうな言語では同期版を提供する。

Rust API側（voicevox_coreグレート）は変える必要はないと思います。
それぞれの言語バインディングでRUNTIME.block_on（C APIのように）すればシグネチャの変更だけで済むと思います。

**Comment by Hiroshiba** [comment]
> Rust API側（voicevox_coreグレート）は変える必要はないと思います。 それぞれの言語バインディングでRUNTIME.block_on（C APIのように）すればシグネチャの変更だけで済むと思います。

その手もあるかなと思います。
最終的にRust APIでも同期版を提供する方針であれば、それを作って各言語でラップする形が良いのかなーと。

**Comment by qryxip** [comment]
その`RUNTIME.block_on`で包むのをRust APIで一括でやってしまえば、APIとしての見通しと統一性が向上するんじゃないかと思っています。

`RUNTIME.block_on`がFFI側から減らせればたぶんすっきりするし、混乱も減らせるんじゃないかと思います。
例えば今私が見つけたPython APIのここ、 #555 の後に #553 を入れたので忘れてましたが、この`tokio::sync::Mutex`およびそれに伴う`RUNTIME.block_on`はもう要らないはず。こういうのも減らせるかと。

<https://github.com/VOICEVOX/voicevox_core/blob/eda04a0d3115764bd74a78874e0e3696357ac0cd/crates/voicevox_core_python_api/src/lib.rs#L148>

**Comment by qryxip** [comment]
手元で`async def`の外でpyo3-asyncioの関数を呼んでみたのですが、その際起きることとしてはコルーチンが返されて後で`TypeError`になるのではなく、その場で`RuntimeError`を吐くようです。

```console
>>> synthesizer = asyncio.run(Synthesizer.new(openjtalk))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: no running event loop
```

**Comment by Hiroshiba** [comment]
onnxruntimeがどうなってるのか、SessionのAPIを見てみました。

* 同期的にコンストラクタで作る
	* [C++](https://github.com/microsoft/onnxruntime-inference-examples/blob/07aaa43bfc69f84a90c4a2a94a11ff4bbf7f0091/c_cxx/MNIST/MNIST.cpp#L61)
	* [Python](https://onnxruntime.ai/docs/api/python/api_summary.html#load-and-run-a-model)
* 同期的にglobalな関数で作る
	* C
	* [Java](https://onnxruntime.ai/docs/api/java/ai/onnxruntime/OrtEnvironment.html#createSession(byte%5B%5D))（envを作ってenv.createSession）
* 非同期的にstaticメソッドで作る
	* [javascript](https://onnxruntime.ai/docs/api/js/interfaces/InferenceSessionFactory.html#create)

onnxruntimeは全言語で全然違うインターフェースを持っていそうな雰囲気を受けました。別々な設計方針で開発してる･･･？（流石にそれはめちゃめちゃ大変そう。。。）

**Comment by Hiroshiba** [comment]
[aws-cdk](https://github.com/aws/aws-cdk)も調べてみました。
awsが自作しているjavascriptを他言語に変換するフレームワークjsiiを使っていました 😇 
https://github.com/aws/aws-cdk/blob/857ab7d8eb465afa50753b74d6a2a4bec2cddf1e/CONTRIBUTING.md#repo-layout

**Comment by qryxip** [comment]
#702, #705, #706により達成。
