### ISSUE TITLE
Raspberry Pi (arm64) 向けビルドの追加

### ISSUE THREAD

**Issue by Lapis256** [VOICEVOX/voicevox_core#67]
## 内容
Releasesにあるarmhf向けの共有ライブラリがarm64のPythonで利用できないので、arm64向けの共有ライブラリも自動ビルドしてリリースしてほしいです。

### Pros 良くなる点
- arm64のRaspberry Pi OSでも動作させられるようになる
- 64bitに対応する事でRaspberry Piでのパフォーマンスが向上するかもしれない

### Cons 悪くなる点
- #40 でもあるようにリリース作業時間が伸びてしまう

### 実現方法
- libcoreのarm64向け自動ビルドを追加する

## OSの種類/ディストリ/バージョン
OS: Debian GNU/Linux 11 (bullseye) aarch64
Host: Raspberry Pi 4 Model B Rev 1.2

## その他
ONNX Runtimeもarm64向けに自動ビルドしたほうがいいかもしれません。

**Comment by Hiroshiba** [comment]
issueありがとうございます！

armhf向けのonnxruntimeは提供されておらず、こちらで自前ビルドしてたりします。
https://github.com/VOICEVOX/onnxruntime-builder/blob/72f8f31ad71f131cef692b32b4bf2d65a94a4a94/.github/workflows/build.yml

もし対応するとしたら、↑の`onnxruntime-builder`リポジトリ内で64bit版のをビルド可能にしたあと、こちらのリポジトリで対応するのが良さそうだと感じました。

ちなみに`onnxruntime-builder`はforkしたあと、github releasesでタグを作ればgithub actionsで誰でもビルドを試すことができます。
もしよかったらチャレンジしてみませんか･･･？👀 @Lapis256

**Comment by Lapis256** [comment]
わかりました、チャレンジしてみようと思います。
@Hiroshiba

**Comment by Hiroshiba** [comment]
早速ありがとうございます！！

↓にビルド済みのものがあると思います！
https://github.com/VOICEVOX/onnxruntime-builder/releases/tag/1.10.0.1

**Comment by Hiroshiba** [comment]
@Lapis256 さん、その後どうでしょう👀

**Comment by Lapis256** [comment]
@Hiroshiba 
自動ビルドを追加して動く事を確認したのですが、onnxruntimeのバージョンが一つだけ違ったので試すだけにとどめていました。
他のとバージョンが揃ったようなので、プルリクエストを出そうと思います。

**Comment by Hiroshiba** [comment]
おお！！ありがとうございます！！

**Comment by Hiroshiba** [comment]
リリースビルド、作ってみました！ https://github.com/VOICEVOX/voicevox_core/releases/tag/0.11-preview.0
