### ISSUE TITLE
バージョンを振る

### ISSUE THREAD

**Issue by tuna2134** [VOICEVOX/voicevox_core#677]
## 概要
現状Python向けのものは適当なバージョン振られていないため、今後のアップロードに影響があるため、振っていただけると助かります。

## 改善方法
python向けのライブラリのCargo.tomlのversionの部分を変更すればいいと思います。

**Comment by tuna2134** [comment]
Cargo.tomlには書いているけど、"0.0.0"はじゃなくてもう少しまともなバージョン付けを。。。

**Comment by sevenc-nanashi** [comment]
https://github.com/VOICEVOX/voicevox_core/blob/main/.github/workflows/build_and_deploy.yml#L253
で振られてますね、タグとバージョンが一致しないミスとか考えるとこれがいいのかなぁと思います。

**Comment by Hiroshiba** [comment]
あ、バージョンはビルド時にGithub workflowから与えられる設計になっています！
バージョンをコーディングすると、バージョンアップやテストビルドの度にコードを更新したりプルリクエストを送る必要があって不便だったので、今はそうなっています。

workflowのbuild_and_deploy.ymlのVERSION引数や環境変数を追うとどうなってるのかわかりやすいかなと…！

**Comment by tuna2134** [comment]
となると、Py側の変更が良さそう？ですかね？

**Comment by Hiroshiba** [comment]
こちらのPyPIビルドの話ですよね。

- https://github.com/VOICEVOX/voicevox_core/issues/653

コードに依りそうですが、同じくGithub workflowのworkflow_dispatchやworkflow_callで引数指定する形にしていただけると運用的には助かります。
Python APIは↓のようになってるので、参考になれば！

バージョン情報のset
https://github.com/VOICEVOX/voicevox_core/blob/4c4b7677b3693ed3a361422c1c9819595270110c/.github/workflows/build_and_deploy.yml#L253

Python APIのビルド
https://github.com/VOICEVOX/voicevox_core/blob/4c4b7677b3693ed3a361422c1c9819595270110c/.github/workflows/build_and_deploy.yml#L281

**Comment by tuna2134** [comment]
> こちらのPyPIビルドの話ですよね。
> 
> 
> 
> - https://github.com/VOICEVOX/voicevox_core/issues/653
> 
> 
> 
> コードに依りそうですが、同じくGithub workflowのworkflow_dispatchやworkflow_callで引数指定する形にしていただけると運用的には助かります。
> 
> Python APIは↓のようになってるので、参考になれば！
> 
> 
> 
> バージョン情報のset
> 
> https://github.com/VOICEVOX/voicevox_core/blob/4c4b7677b3693ed3a361422c1c9819595270110c/.github/workflows/build_and_deploy.yml#L253
> 
> 
> 
> Python APIのビルド
> 
> https://github.com/VOICEVOX/voicevox_core/blob/4c4b7677b3693ed3a361422c1c9819595270110c/.github/workflows/build_and_deploy.yml#L281

> voicevox.__version__でバージョンをpy側から呼び出さないといけないと思うので。。。
これに関してどうしますか？

**Comment by Hiroshiba** [comment]
`__version__`は、ここかなと 
https://github.com/VOICEVOX/voicevox_core/blob/4c4b7677b3693ed3a361422c1c9819595270110c/crates/voicevox_core_python_api/src/lib.rs#L24

**Comment by tuna2134** [comment]
最悪、replaceするようshell組めばいけそうですが

**Comment by tuna2134** [comment]
> `__version__`は、ここかなと
> 
> https://github.com/VOICEVOX/voicevox_core/blob/4c4b7677b3693ed3a361422c1c9819595270110c/crates/voicevox_core_python_api/src/lib.rs#L24

なら、なんとかなりそうですね、、、
クローズでよさそうかな？

**Comment by Hiroshiba** [comment]
ですね、一旦解決だと思います！
