### ISSUE TITLE
推論をキャンセル可能にする

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#687]
## 内容

asyncなタスクに一般的に期待される機能の一つとして、キャンセル可能であるというのがあると思います。しかし現状の実装では、ONNX Runtimeの推論はasyncの文脈でキャンセルすることができません。何故ならスレッドは外から停止できないからです。ここでONNX Runtimeの`RunOptions::SetTerminate`によって、推論のキャンセルを可能することを提案します。

`terminate`というプロパティですが、次のように説明されています。

> If a currently executing session needs to be force terminated, this can be called from another thread to force it to fail with an error.

(C API)

> Set to True to terminate any currently executing calls that are using this RunOptions instance. The individual calls will exit gracefully and return an error status.

(Python API)

意味を掴みかねていたのですが、コードを見ると`bool terminate`を`const bool&`で引き回してそれをチェックし続けていました。試してはいないのですが、ある`RunOptions`で推論を開始したあと、その`RunOptions`の`terminate`を`true`にセットすると、`"Exiting due to terminate flag being set to true."`というメッセージと共に推論が止まってくれるということだと予想しています。

<https://github.com/microsoft/onnxruntime/blob/v1.16.2/onnxruntime/core/framework/stream_execution_context.cc#L211-L216>

APIとしては次のような形がよいのかなと思っています。

- ~~同期/非同期APIにおいて、`Synthesizer`の各操作は`class SynthesisTask`を返すようにする。`SynthesisTask`は`.wait()`で続行、`.cancel()`でキャンセルする。~~

<div></div>

- 同期/非同期APIにおいて、`Synthesizer`の各メソッドに推論キャンセルのためのオプションを一つ追加する。例えば`#[repr(C)] struct VoicevoxInferenceCanceller`。
    ~~(追記) 直に`bool`でもいけるかもしれない~~
- 非同期APIにおいては、さらにasync文脈でのキャンセルでも推論をキャンセルするようにする。

### Pros 良くなる点

- asyncなAPIとして完成に近づく
- 推論の中止ができる

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

TFLiteにもキャンセル機構があるようです。

**Comment by Hiroshiba** [comment]
なるほどです、キャンセル可能にするの面白そうですね！！
onnxruntime 1.16が必要な感じでしょうか。

> 同期/非同期APIにおいて、Synthesizerの各メソッドに推論キャンセルのためのオプションを一つ追加する。例えば#[repr(C)] struct VoicevoxInferenceCanceller。

素人なのであれなんですが、頭の中でどうやってこれで実行中の処理をキャンセルできるのかが分かりませんでした･･･！！
`VoicevoxInferenceCanceller`に`cancel()`メソッドと`onCancelCalled`コールバックがある･･･？

**Comment by qryxip** [comment]
> どうやってこれで実行中の処理をキャンセルできるのかが分かりませんでした･･･！

`VoicevoxInferenceCanceller`は[crossbeam-channel](https://docs.rs/crossbeam-channel)の`Sender` (以下TX)と`Receiver` (以下RX) を持っていて、`Synthesizer`のメソッドに渡すとRXを複製してonnxruntime-rsを触る部分付近まで持って行きます。そしてRXを待つタスクと推論を実行するタスクでスレッド(`std::thread`)を分け、RXにイベントが来たらonnxruntimeの`RunOptions::SetTerminate`を叩きます。

`#[repr(C)]`なのは`#[repr(Rust)]`だとC APIにおいてユーザーにデストラクト処理を要求してしまうためそうしたいというものなのですが、これは中身を`int _id`とかにすれば実現できるのかな思っています。その場合(TX, RX)の実体は`VoicevoxSynthesizer` (⊋ `voicevox_core::Synthesizer`)かグローバルで持つことになる...
...とここまで考えて思ったのですが、C以外のAPIには関係が無いので、やっぱり`#[repr(Rust)]`にしてC APIユーザーにはデストラクト関数を呼び出してもらうというのがよいのかもしれません。

> （まあ議論は時期尚早かもしれませんが）

このオプションは前からあるみたいなので、1.16にしなくても今のonnxruntime-rsをちょっと弄れば実装できる気がします。ただCORE 0.15では`warn!("推論はキャンセルされません! 終わるまで動き続けます")`みたいな表示を出すので十分な気もするので、まあ後でしょうかね。

**Comment by Hiroshiba** [comment]
なるほどです！！Rustの中でのイメージは結構わかった気がします。
ちょっとまだC APIのインターフェースが一意に定まってない感ありますが、まあ実装しようとなったタイミングで決めていくのでも良いのかなとか思いました！

**Comment by qryxip** [comment]
なんか`Session::run_async`というのが追加されたようです。`Drop`時に`SetTerminate`するんだとか。
<https://github.com/pykeio/ort/pull/174>

**Comment by qryxip** [comment]
`run_async`が含まれた[ort v2.0.0-rc.1](https://github.com/pykeio/ort/releases/tag/v2.0.0-rc.1)がリリースされました。入れるとしたら`trait InferenceRuntime`から拡張という形になりますね。

同期版にキャンセル機構を入れるかどうかですが、個人的にはしなくていいのではないかと思っています。キャンセル機構が要るような人は非同期版を使うでしょうし、ENGINE以降にキャンセル機能を追加するときはもうPyO3版でvoicevox_core_compatible_engine.{pyd,pyi}みたいなのを作ってそれをコアとして取り扱った方がいいのでは?と思います。

**Comment by Hiroshiba** [comment]
PyO3版はエンジンで使うときに[過去のコアを使えない問題](https://github.com/VOICEVOX/voicevox_engine/issues/454#issuecomment-1229190128)が･･･
と思ったのですが、vvm導入でその懸念がなくなってることに気づきました。なんとかなる気がしますね。

そもそもエンジンはcompatible_engine以外用いるモチベがなかったのですが、推論キャンセルほどの有用機能がC APIで使えないとなるとかなり話は変わってくるように感じました。
推論キャンセルを使えてかつvvmも使えるとなると、エンジンは重い腰をあげて最新版コアAPIを使うモチベーションがぐっと上がると感じます。

（コンテキストが深い内容なのですが、エンジンでできることが増えるかもなので共有です @y-chan  @tarepan ）

**Comment by qryxip** [comment]
@tarepan 文脈を補足しておくと、 VOICEVOX COREは[PyO3によるPython APIを提供して](https://voicevox.github.io/voicevox_core/apis/python_api/autoapi/voicevox_core/index.html)おり、[pyo3-asyncio](https://docs.rs/crate/pyo3-asyncio)により[Rustの`Future`](https://doc.rust-lang.org/stable/std/future/trait.Future.html) → Pythonのコルーチンの変換を行っています。上記の[`ort::Session::run_async`](https://docs.rs/ort/2.0.0-rc.1/ort/struct.Session.html#method.run_async)は`Future`を返す、実質的なasync関数です。pyo3-asyncioをもってすればFastAPIのasyncioで扱えると思います。

---

あとpyo3-asyncioは[Rustの`futures::Stream`](https://docs.rs/futures-core/0.3/futures_core/stream/trait.Stream.html) → Pythonのasyncジェネレータの変換も"unstable"な機能としてあるようです。ストリーミングもasyncioの文脈でできるかもしれません。

まあC APIでも頑張れば非同期的な表現はできなくはないと思います。その場合はcompatible\_engine(CORE)側とvoicevox_engine/core側の両方で手間がかかりそうな気はしますが。

> PyO3版はエンジンで使うときに[過去のコアを使えない問題](https://github.com/VOICEVOX/voicevox_engine/issues/454#issuecomment-1229190128)が･･･
> と思ったのですが、vvm導入でその懸念がなくなってることに気づきました。なんとかなる気がしますね。

onnx版は最新のONNX Runtimeでなんとかなるとして、[tch-rs](https://docs.rs/crate/tch)の導入も検討した方がよいですかね?

**Comment by qryxip** [comment]
あ、あとPython側からはパッケージのインストールの他にも`importlib`で読み込むという選択肢も一応あると思います。

**Comment by tarepan** [comment]
@Hiroshiba @qryxip  
情報共有ありがとうございます！  
ENGINE では推論キャンセルが長いこと提案されてきた（現在停滞中 https://github.com/VOICEVOX/voicevox_engine/issues/677 ）ため、CORE での実装は非常に有益だと考えます。  
脱 compatible_engine は前向きです。CORE で進行中の改良（VVM等）が release として安定化するのを楽しみにしています。

**Comment by Hiroshiba** [comment]
> 既にonnxで提供されているものは最新のONNX Runtimeでなんとかなるとして、[tch-rs](https://docs.rs/crate/tch)の導入も検討した方がよいですかね?

あ、これは他に手段がいくらでもあるので、まあいらないかなと！
