### ISSUE TITLE
onnxruntime-rsからortに乗り換える

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#718]
## 内容

ONNX Runtimeを扱うためのライブラリを、onnxruntime-rsから[ort](https://docs.rs/crate/ort)にします。

#427 の方は、ちゃんと使えるようになるのに何年待たなくてはならないかわからないのでortの方がよいと思いました。

### Pros 良くなる点

- ちゃんとメンテされるライブラリに乗っかることができる
    - `dlopen`/`LoadLibrary`, 静的リンク
    - DirectMLを含むEP対応
    - WASM対応
    - etc.

### Cons 悪くなる点

onnxruntime-rsと比べると無いはず。 microsoft/onnxruntime本家のRustバインディングが動きだしたら別かとは思いますが、今動きだしたとして半年は待つ必要はありそうな感じなので…

### 実現方法

1. ortをVOICEVOX下にフォークする
    - 今までVOICEVOX/onnxruntime-rsに加えた変更のうち、必要なものを入れる (ortは結構先を進んでいるので、多分そんなに必要無いはず)
    - ortの<https://github.com/microsoft/onnxruntime/pull/8502>対応を、onnxruntime-rs本来の「コピー」する挙動に戻す
        - [Discordで以前話した](https://discord.com/channels/879570910208733277/893889888208977960/1175820756890943579)件です
2. onnxruntime-rsをortに置き換える

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
比較的賛成です！
onnxruntime-rsや、本家onnxruntimeのRustよりも、ortに依存する形が今は良さそうに思いました！

**Comment by qryxip** [comment]
リポジトリには`v2`ブランチが生えていて、2023-12-28に`v2.0.0-alpha.4`がリリースされていました。v2の変更点の多さから、v2をベースにフォークするのがよいと感じました。

以下v2を見て気付いたことです。

- <https://pyke.io>というところにビルド済みのONNX Runtimeが置いてあり、そこからダウンロードするようです（[ortのドキュメント](https://ort.pyke.io/introduction)もここ）。
    <https://github.com/pykeio/ort/blob/v2.0.0-alpha.4/ort-sys/build.rs#L251-L300>
    - tar.gzのファイル名にある`_static`は、文字通り静的ライブラリを指します。execution provider用のDLL（e.g. libonnxruntime\_providers\_cuda.so）が必要無い場合に限り静的リンクをする、という方針であるようです（[ドキュメント](https://ort.pyke.io/setup/linking)）。
    - iOSやAndroidが抜けているため、どの道足す必要があります。
- `Session`の構築は[`Session::with_model_from_memory_directly`](https://docs.rs/ort/2.0.0-alpha.4/ort/struct.SessionBuilder.html#method.with_model_from_memory_directly)と[`Session::with_model_from_memory`](https://docs.rs/ort/2.0.0-alpha.4/ort/struct.SessionBuilder.html#method.with_model_from_memory)に分かれたため、後者をそのまま使えばよさそう
- 必須なのはおそらく次の3つのみかと思います。
    1. iOSやAndroidなどの追加も兼ね、ONNX Runtimeのダウンロード先をVOICEVOX/onnxruntime-builderのものにする
    2. ロギングの削減
    3. 足りないAPIがもしあれば、それの追加
- pyke.ioとしてDiscordサーバーが立っています。入ってみましたが、そこそこ人がいました。

**Comment by Hiroshiba** [comment]
お～～～　なるほどです！！
v2はまだ正式リリースじゃないんですね。

依存をortへ変更していくタイミングですが、いつが良さそうでしょうか？
ortがv2になった直後とか、１ヶ月くらい様子見した後とか、今すぐとか。

個人的には、ちょっとコア周りのタスクがいっぱいある現状がちょっと片付くのを待てるから嬉しいな～というのと、一般論としてやはりメジャーアプデしてしばらく経ってからが良いのかな～とか思っています。

あ、VVM asyncのタイミングに合わせる・合わせないの思いは自分的に特に無いです。
マイナーアプデ（実質メジャーアプデ）で依存変更するのも良いと思うし、ortにしてもコアAPIは変わらないと思うのでパッチアプデで依存変更するのも問題ないと思うし、という感じです。

**Comment by qryxip** [comment]
#721, VOICEVOX/voicevox_project#24, ONNX Runtimeのv1.16化の3つを合わせると、コアv0.15に合わせるのがよいのかなと思ってます。

2月にまとめてできればとよいなと思っています。少なくともortへの移行は名無し。さんと白緑さんが前試してましたし、そんなに労力はかからないかなと。

**Comment by Hiroshiba** [comment]
あ～なるほどです。dlopenとかは特に大きめではありますね！
でもまあVVM+async対応のあとにサクッとまた大きめのバージョンアップとしちゃっても良いかもとか思いました。
焦る必要はないけど、のんびりじゃないといけない理由もない、って感じかなと思いました。

ortがずっとv2-alphaだったらどうすべきか悩みそうですね･･･。
できればalpha版に依存するのは避けたいのですが、いよいよもう他にやることがないってなったらv2-alphaでも移行しちゃって良いかも。

**Comment by qryxip** [comment]
個人的にはalphaでも強行していいかなと思っています。メンテされていないものを自力メンテして使うよりはましではないかなと(今回のortの場合フォークして改造する手間もおそらくそんなに無いわけですし)。

また移行の労力についてもそんなに無いと思ってます。ちょっとさっきまで航空機内と空港の充電スペースでortへの切り替えをやってみたのですが、Linux/CPUでテストを通せるところまで割とさくっといきました。

エラー分岐は所々`todo!()`ですし、DirectMLとかiOS/Android対応もしてませんが、そういう範囲であればortに改造を加えることなく行けました。

```console
❯ git diff --stat
 Cargo.lock                                             |  66 +++++++++++++---------
 Cargo.toml                                             |   6 +-
 crates/voicevox_core/Cargo.toml                        |   5 +-
 crates/voicevox_core/src/infer/runtimes/onnxruntime.rs | 286 +++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------
 4 files changed, 192 insertions(+), 171 deletions(-)
```

**Comment by Hiroshiba** [comment]
なるほどです。僕個人もまあalphaでも良いかなと正直思ってます。
が、まあメンテナ的にはalphaを避けられるなら避けるべきな気がして、これ以外やることないときまで待つのが良いのかなと感じた次第です。

ortを今forkしたほうが良ければforkします！
もっとあとでも良いならあとでforkします。

**Comment by qryxip** [comment]
@tuna2134 さんの #693 のために #721 を早めにやっておきたいという動機は発生しそうかなと思いました。
(すぐ使わなくなるであろう機構のためにあれこれやる、というのはあまり望ましくはないのではと思っています)

**Comment by neoedmund** [comment]
乗換なら
https://github.com/webonnx/wonnx
はいかがでしょうか?
vulkanによって、対応platformが広く、runtimeもサイズ小さい。

**Comment by Hiroshiba** [comment]
@neoedmund 現状だと対応している演算が少なくて難しそうです！
でも面白いですね。ちなみに実行速度は速いのでしょうか？

**Comment by neoedmund** [comment]
対応している演算はVOICEVOXで使ているのと合致するかどうか。実行速度はvulkanでわるくない筈。
