### ISSUE TITLE
ONNX Runtimeのリンクを`dlopen`/`LoadLibrary`ベースにする

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#721]
## 内容

ONNX Runtimeのリンクを`dlopen`/`LoadLibrary`ベースにします。

### Pros 良くなる点

以下のような問題が解決される。

- #445
- #543
- #642
- #644

### 実現方法

#718 をしたときに`dlopen`/`LoadLibrary`モードに切り替える。ただし現状のVOICEVOX/onnxruntime-rsでも可能ではある。

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

実行に移すタイミング次第では以下のようなissueに影響が出ると思います。

- #691 (CC: @tuna2134)
- #715 (CC: @nekomimimi) (iOSだけ従来通りのリンク、または静的リンクという手はあると思います)

**Comment by nekomimimi** [comment]
動的ライブラリをframeworkで包む版、現状、スクリプトを書き終わって1.15.1でxcframeworkができるようになって1.14.1で確認しようと思って作成すると手前の処理で落ちて、動作確認のテストできない状況です。

作ってみて思うのは、
1.複雑になってメンテナンスが静的リンクより大変そう。
2.onnix runtimeのdylibにバージョン名につけて分けても、2バージョンが必要となった時にアプリから呼び出せないのではないか
と思います。
(2については、試行錯誤してみないとわからないのですが、直感ではもう一工夫ないと無理そう。）
ということで、静的リンクの方が理がある気がします。

**Comment by Hiroshiba** [comment]
基本的にはdlopenの形に賛成です！
普通はどっちにするのが一般的かわかりませんが、動的リンクだと実行時にエラーの理由を出せないのがやっぱりつらい･･･ 😇 

@qryxip 
動的リンクと`dlopen`をビルド時に切り替える、ということはまあまあ容易にできそうだったりしますか？ 👀 
であれば @nekomimimi さんのタスクはこのissueを特に気にすることなく進められるのかなと思った次第です！

**Comment by qryxip** [comment]
featureのオンオフで切り替え可能だと思います(静的リンクも含め)。

**Comment by Hiroshiba** [comment]
なるほどです、ありがとうございます！！
であればたぶん、こちらのissueを進める場合も、 @nekomimimi さんの手を止めてしまうことなく動けるの感じなのかなと思いました！

**Comment by nekomimimi** [comment]
@Hiroshiba 
一点、教えていただきたい事がありまして、
iOS版について静的リンク(.a)より動的リンク(.dylib)にしたい理由をお教えください。
これらのうちのどれかかなと想像しました。

1.voicevox_coreと関数名の被る別のライブラリを同時に使うアプリが想定される。
2.複数のバージョンのonnixruntimeを同時に使うアプリが想定される。
3.onnixruntimeとvoicevox_coreのバージョンが合わない時にクラッシュさせたい。
4.パフォーマンスの問題。
5.静的ライブラリにすると作成に時間がかかりそう。
6.その他

**Comment by Hiroshiba** [comment]
５ですね！

より正確に言うと、そもそもonnxruntimeは公式には動的ライブラリしか配布していないので、iOS版だけ静的リンクにするよりは合わせた方が楽そうだなという感じです！

**Comment by nekomimimi** [comment]
了解です。そのままdylibをframeworkで包む方針でいきます！
