### ISSUE TITLE
.binファイルのソースについて

### ISSUE THREAD

**Issue by neoedmund** [VOICEVOX/voicevox_core#726]
## 質問の内容

`voice-core` に `model` は `VVM` 型式
配布した `voicevox-linux-cpu-0.14.11` などに model は `.bin` 型式
`.bin`の処理に関するソースが見付からない。

と、質問は
`.bin`に関する処理のソースは何処ですか? formatは何ですか?

## VOICEVOXのバージョン

0.14.11

 

## OSの種類/ディストリ/バージョン

 

- [ ] Windows
- [ ] macOS
- [x ] Linux debian 12

**Comment by Hiroshiba** [comment]
CORE用のリポジトリにissueを移動しました。

> voice-coreをAMD GPUに対応にカスタマイズしたい時の疑問。

なるほどです！こちらが参考になるかもしれません。
https://github.com/VOICEVOX/voicevox_core/issues/617

> .binの処理について、一部Open Sourceではない物が含まれていると理解してよろしいでしょうか?

はい。キャラクターや声はOSSではありません。
https://github.com/VOICEVOX/voicevox/blob/766131d13085f8e8f7f1a5ff62e86a1178a2711a/docs/%E5%85%A8%E4%BD%93%E6%A7%8B%E6%88%90.md

onnxモデルはサンプルがここにあります。もしAMD GPUでこのモデルが動くととても嬉しいです！
https://github.com/VOICEVOX/voicevox_core/tree/main/model

**Comment by neoedmund** [comment]
「キャラクター声はOSSにできない」が自由ですが、できない理由に違和感が感じされた。
後、「`OSS版VOICEVOX`は直接「キャラクター」データー利用出来ない、`修正したVOICEVOX`いわゆる`製品版VOICEVOX`が「キャラクター」データーが利用出来る」でしょうか.

せっかく説明したが、 https://github.com/VOICEVOX/voicevox/blob/main/docs/res/%E5%85%A8%E4%BD%93%E6%A7%8B%E6%88%90_OSS%E7%89%88%E3%81%A8%E8%A3%BD%E5%93%81%E7%89%88%E3%81%AE%E9%81%95%E3%81%84.svg
製品版VOICEVOX の図の意味が間違ている、図の中に、"OSS版VOICEVOX" の定義はOSSに言えないでは?

**Comment by qryxip** [comment]
Perhaps you're right. Both `voicevox` and `voicevox_engine` is dual-licensed, the first license is LGPL-3.0, and the second one is "all rights reserved. contact me if you want to fork". To my understanding, the second "licensed" is used for "製品版VOICEVOX", therefore from a licensing perspective "OSS版VOICEVOX" may not be a part of "製品版VOICEVOX". 

Moreover, `voicevox_core` embedded in "製品版VOICEVOX" is currently totally proprietary. `voicevox_core` under MIT cannot read .bin models. Even you add ROCm support to `voicevox_core`, you cannot test it with proprietary .bin models.

However, after resolving following issue/PR, I believe you can use `voicevox_core` under MIT License for "製品版VOICEVOX" and it's .bin models. Do you read and write Rust code? If so, your contribution is welcome.

- https://github.com/VOICEVOX/voicevox_core/pull/725
    (maybe [VOICEVOX/onnxruntime-builder](https://github.com/VOICEVOX/onnxruntime-builder) needs to be updated)
- https://github.com/VOICEVOX/voicevox_project/issues/24

FYI, you can build "OSS版VOICEVOX" that consists of following software now, though it's not a part of "製品版VOICEVOX":

- `voicevox` under LGPL-3.0
- `voicevox_engine` and it's [speaker_info](https://github.com/VOICEVOX/voicevox_engine/tree/83363b14b1a19d849066897b8da0d11d77ccf31b/speaker_info) under LGPL-3.0
- `voicevox_core` and sample.vvm under MIT License

**Comment by neoedmund** [comment]
`onnxruntime`にfeedするデーターは生onnxだろう、そこでonnxを取り出すのは手間かかるだけ。
proprietaryにする発想は、「使いたいなら、VOICEVOXでして、他のForkでは止めろう」は本音だろうか。
分らなくでもない、何かOSS面はすっきりしない感じ。

**Comment by neoedmund** [comment]
Off Topic,どうでもいい話何ですが、僕はRustのfanではないだ. Rustはメモリ安全性にこたわるんだが、ここは取柄はないだろうか。
