### ISSUE TITLE
project-s ブランチをmainブランチにマージしたい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#737]
## 内容

長い間別ブランチになっていたproject-s ブランチが役目を果たしました。今はrelease-0.15ブランチになっています。

- https://github.com/VOICEVOX/voicevox_core/issues/712

なのでmainブランチにマージしたいのですが、あまりにも API 構成が変わりすぎているので、どうしていくべきかを考えられる場を作ってみました･･･。

### 実現方法

とりあえず問題になりそうな箇所を列挙してみます。

#### style_typeが違う場合の扱い

スタイルごとのタイプが今まで1つだったのが、4つになりました。

* talk: 今までと同じ、TTS用のスタイル。[TalkModel](https://github.com/VOICEVOX/voicevox_core/blob/01c3a9bf955302b6c301c728758e0ffce2d9db91/crates/voicevox_core/src/status.rs#L197-L202)に対応。
* sing_teacher: 歌い方を生成できるスタイル。[SingTeacherModel](https://github.com/VOICEVOX/voicevox_core/blob/01c3a9bf955302b6c301c728758e0ffce2d9db91/crates/voicevox_core/src/status.rs#L203-L208)に対応
* sf_decode: 歌い方から音声を生成できるスタイル。原理上、別に歌じゃなくても良いので名前にsingが入ってない。[SfDecodeModel](https://github.com/VOICEVOX/voicevox_core/blob/01c3a9bf955302b6c301c728758e0ffce2d9db91/crates/voicevox_core/src/status.rs#L209-L212)に対応。
* sing: sing_teacherとsf_decodeの機能を持つスタイル。

これ関連でややこしいことが３つ思いつきます。

* singスタイルはモデルが2つ必要
	* 可能であれば１つのVVMに２種類のモデルを持てるようにしたい
		* [この時のコメント](https://github.com/VOICEVOX/voicevox_core/pull/724#issuecomment-1881844346)でも同じようなこと言ってました
	* metas.jsonやmanifest.jsonで、typeをsingにするのかsf_decodeとsing_teacher２つを持たせるのか、どっちがいいかわからない
		* まあ互換性がなくなったらmanifest_versionを上げれば良いだけなので、どっちでもいいっちゃ良い
* 同じスタイルID・別のスタイルTypeがありえる
	* A.vvmにはsing_teacherが、B.vvmにはsf_decoderが、みたいな
* １つのvvmの中に複数のスタイルTypeを含めたい
	* 例えば、`sf_decode`しかないスタイルと、`sing`も持ってるスタイルを同じvvmに含めたい
		* もうちょっというとmodel.onnxを共有できるため
	* あと将来的なことも考えると、1つのキャラの全スタイルが入った vvm が作れるようになるので嬉しいかも
		* namine_ritsu.vvm（トーク・ハミング・ソングがある、みたいな）
	* これは最悪切っても良い（容量が非効率的だったり、複数の vvm に分散するだけなので）

#### InferenceDomainが増えそう

style typeごとに一つdomainを作るのか、sing domainは作らないのか、どっちが良いかパッとわかりませんでした･･･。

#### 使い方・サンプル

それぞれ追加が必要そう

## その他

もし何か問題がありそうだったら、破壊的変更しちゃってもいい気がします。
かなり説明が曖昧なところがあると思うので、不明な点があれば何も聞いてください 🙇

**Comment by Hiroshiba** [comment]
どの概念が3種持つべきかぱっとわからないんですよねぇ…。

is model loadedはたしか今世に出てる製品版コアだと、そのスタイルで扱うモデルが全部読み込まれてたらtrueとかだったと思います！

**Comment by qryxip** [comment]
現段階で私が考えている手順をメモします。

1. `main`の先頭で`git merge release-0.15`を試み、コンフリクトしたら一旦`main`側に`restore`する。
2. `mod singing_teacher`と`mod frame_decode`を実装する。
3. crates/voicevox_core/src/infer/domains.rsに、`singing_teacher`と`frame_decode`という概念を追加する。<https://github.com/qryxip/voicevox_core/commit/69399155742ebc7a2180c3a62f8eb50697a1b42e>のようにするとコンパイルエラーは次の画像の範囲で収まるはずなので、これを解消していく。
    (一応このコミットを使うときは、私をco-authorに入れるという流れになると思います。著作性あるかわからんけど)
    ![image](https://github.com/user-attachments/assets/97df7b21-9845-4d95-9bbb-56af6402bb3d)
4. `release-0.15`の内容を移植していく。
5. `git merge`を完了したらそのマージコミットでPRを作る。
