### ISSUE TITLE
AMD製GPUでも推論可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#74]
## 内容

onnxruntimeに移行したので、AMD製GPUでも推論ができるはずな状況になりました。
たぶん[DirectMLを使えば](https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider)実現可能だと思うのですが、実機がないので試せていません。

もしお持ちの方がいらっしゃったらぜひ実装して試してみて頂けると･･･！

### Pros 良くなる点

速くなる

### 実現方法

READMEにonnxruntimeのダウンロードからビルド方法まであるので、onnxruntimeをDirecML用のにしてAMD製GPUで試す

## その他

DirectML版だとnvidia製GPUで推論が遅くなるかも･･･？

ref

- https://github.com/VOICEVOX/voicevox_core/issues/39
- https://github.com/VOICEVOX/voicevox_engine/issues/69
- https://github.com/VOICEVOX/voicevox/issues/686

**Comment by Yosshi999** [comment]
Squeeze981は本当にforward_decodeの末尾のようですね。
![image](https://user-images.githubusercontent.com/8027142/153626015-aaae1d8d-db95-4674-b5e7-da3ee6b7eefb.png)

https://github.com/microsoft/onnxruntime/blob/v1.10.0/onnxruntime/core/providers/dml/DmlExecutionProvider/src/MLOperatorAuthorImpl.cpp#L1850
によれば出力dimが合わないとのことなので、実際の出力shapeが(outlength,)ではなく何らかの次元が余分に乗っかってる可能性があります。さすがに逆（実際がScalarになってるとか）はなさそう？

ですが、なぜこういうことが起こるのかが分からない...

**Comment by Yosshi999** [comment]
あくまで↑で使っているonnxモデルは僕が手元で変換したcore 0.0.1なので、今のonnxモデルの出力がおかしい可能性もあります。shapeが(1, outlength)になっていても恐らくクラッシュせずにC APIを経由できるので

**Comment by Yosshi999** [comment]
どうも現状のonnxruntime(1.10.0)のDirectMLはopset12までしか対応してないみたいです
今のonnx変換に使っているopsetは12のはずですが、手元の環境だと13になっているっぽいのでそれが原因かもしれません。
一度onnxモデルを作りなおしてみます

**Comment by Hiroshiba** [comment]
なるほどです！！

> Squeeze981は本当にforward_decodeの末尾のようですね。

ということは推論完了まであと一歩かも・・・？
良いですね！！　DilectMLに対応できたらかなり喜ばれると思います！

> onnx変換に使ったのがopset12でonnxruntime <= 1.9.0 のdirectmlの対応opsetが11?

@Yosshi999  ちょっとわかってないのですが、onnxruntime 1.9.0で試してみたらDirectMLでも動くかも、ということでしょうか👀
結構有り得そうな話だなと感じました！

**Comment by Yosshi999** [comment]
もし今使っているものが1.9.xなら、1.10.0だと動くかもしれないという話です
@Oyaki122 今のonnxruntimeのバージョンはいくつですか？

**Comment by Oyaki122** [comment]
残念ながら1.10ですね

**Comment by Yosshi999** [comment]
https://github.com/Yosshi999/voicevox_core/tree/onnxweight-for-dml/model

@Oyaki122 このモデルを使ってみてもらえますか？

**Comment by Oyaki122** [comment]
![image](https://user-images.githubusercontent.com/42294158/153761879-6b58afc0-409c-4c38-a256-668054885718.png)
動作しました!

**Comment by Hiroshiba** [comment]
こちら、せっかくなのでDirectML対応板作れると面白そうですね！！
ビルド時に`core-nvidia.dll`だけじゃなく`core-directml.dll`みたいなものがある形を目指せば良い･･･？

**Comment by Oyaki122** [comment]
DirectMLですが、ファイルサイズはcpu版と比較しても10MB単位での増加にとどまると考えられるます。
そのため、WindowsのCPU版をすべてDirectML版に置き換えるということも考えられるのではないでしょうか

**Comment by Hiroshiba** [comment]
10MBくらいしか増えないのであれば統合しちゃっても良さそうです！
nvidia版の場合、確かcuda用のdllも必要で容量が増えたのですがそれらも必要ない感じでしょうか👀

**Comment by Oyaki122** [comment]
DirectML用のdllも合わせて10MB強ほどになると思います

**Comment by Hiroshiba** [comment]
であれば統合しちゃいたいですね･･･！

おそらく分けなければ cpu/nvidia/directml の3バージョンになるはずで、これがcpu(+directml)/nvidia になる･･･？
nvidia製GPUでも、nvidia onnxruntime ≒ directml onnxruntime の性能になるのであれば、全部統一しちゃえるとかっこいいかもと思いました！

**Comment by Hiroshiba** [comment]
こちらでの検証の通り、DirectML版はAMD製GPUでも動くことが確認できました。

- https://github.com/VOICEVOX/voicevox_core/issues/90#issuecomment-1065908519

ので、こちらのissueはcloseしたいと思います！

**Comment by Hiroshiba** [comment]
@Oyaki122 さん
DirectML版がちゃんと動くことがわかったので、リリースしたいなと思っています。
こちら、ツイートする際にスペシャルサンクスとして @Oyaki122  さんのIDを言及させて頂ければと思うのですが、いかがでしょうか･･･？ 👀
