### ISSUE TITLE
Download test workflowが全滅している

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#741]
## 不具合の内容

v0.15.0がリリースされ、その中にVVMが入っていないためDownload testが全滅している。

PRではCargo.tomlやダウンローダ自体に触れない限り起動せず :heavy_check_mark: になるが、そのままmainにマージするとmainが :x: になる。

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
課題としてはこちらのissueに近そうです。

- https://github.com/VOICEVOX/voicevox_core/issues/619

ソング機能をVVM側、というよりアーキテクチャがガラッと変わったのに適応させれば最新版ビルドが可能だと思うのですが、さてどうしようかという感じです。
とりあえず急ごしらえですが、ビルド後のダウンロードテストのみ実行する形にし、通常プルリクでのテストはコメントアウトするとかで良い気がしています。
