### ISSUE TITLE
[0.15] .binファイルの読み込みを遅延させる

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#766]
## 内容

現在0.15では`initialize`時に、`load_all_models`のオンオフに関わらず.binファイルを全部メモリに読み込んでしまっています。これを"load"時 (`Session`作成時)まで遅延させます。

<https://x.com/maruna_lunar/status/1772239266321674530>

### Pros 良くなる点

- 0.16を待たずして、メモリが問答無用で1GB持って行かれるのを無くせる

### 実現方法

1.  <https://github.com/VOICEVOX/voicevox_core/tree/release-0.15>に実装

    `struct VoiceModel`を削除して`PathBuf`に置き換え、`Session`の構成時に.binを読むように変える。

    <https://github.com/VOICEVOX/voicevox_core/blob/0fd77a2915884fbaf1afdbe6dfc7986dfe75d291/crates/voicevox_core/src/status.rs#L213-L216>

2. 製品版作成、リリース
3. エンジンかエディタのリリースノートに含める

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
製品版の使用メモリが1GB削減されました！！！　ありがとうございます！！！

before
![image](https://github.com/VOICEVOX/voicevox_core/assets/4987327/41309f60-5535-4c70-97bc-bcdaf2482055)

after
![image](https://github.com/VOICEVOX/voicevox_core/assets/4987327/87f9e40a-cd32-4cf3-9cd0-113670e69ca9)
