### ISSUE TITLE
COREのインストールに失敗する

### ISSUE THREAD

**Issue by animede** [VOICEVOX/voicevox_core#770]
## 不具合の内容

COREのcuda版インストールに失敗する

### 現象・ログ

main Branchから　GPU使用時の指示に従い、CUDA 版をダウンロードする場合　からdownloaderページに移り
CUDA 版をダウンロードする場合のコマンド
download --device cuda
を実行するとエラーになる。

## VOICEVOXのバージョン
main ブランチ
0.15.2

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x ] Linux　Ubuntu 22.04
- 
## その他

main ブランチのコマンドは
./download
となっているので　downloadページの記載に　./　が抜けているものと思います。
./download --device cuda
でインストールできました
ちなみに　0.14.0からですとdownloadページの記載もWindowsbs版には
./download.ps1 -Device cuda
と記載されています。

**Comment by Hiroshiba** [comment]
@animede issue作成ありがとうございます！
たしかにドキュメントの`download`となっているところは`./download`のが良さそうに思いました！

もしよかったらプルリクエストの作成に挑戦してみませんか？
過去にも初挑戦されてる方は結構いらっしゃって、やり方を記述してくださった方もいらっしゃいます。
https://zenn.dev/tantan_tanuki/articles/309d6976d749ea

もしよければ！

**Comment by animede** [comment]
検討、ありがとうございます。らプルリクエストの作成は改めて挑戦します。
