### ISSUE TITLE
`acceleration_mode=Auto`時にEPに問題があるならCPU版にフォールバックする

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#783]
## 内容

ONNX Runtimeのセッション開始時に[Execution Provider (EP)](https://onnxruntime.ai/docs/execution-providers/)に問題がある（例: 正しいバージョンのCUDAが入ってないのにCUDA版を使おうとする）場合、現在の挙動ではそのままエラーになります。`acceleration_mode=Gpu`時ではこれは望ましい挙動です。

ここで`acceleration_mode=Auto`時に限っては、EPに問題があった場合にエラーではなく`CPUExecutionProvider`にフォールバックするようにすることを提案します。

<https://github.com/VOICEVOX/voicevox_core/pull/725#issuecomment-2081560936>

### Pros 良くなる点

- `AccelerationMode::Auto`が"auto"らしくなる

	`Auto`はデフォルトの値であり、VOICEVOX COREに初めて触れる人が選ぶ（というよりデフォルトのままにする）であろう値です。その役割が何なのかというと「その場で最適なEPを選択する」となると思います。CPUにフォールバックする方がこの役割に合致すると思います。

### Cons 悪くなる点

- 挙動の破壊的変更

### 実現方法

#725 の実装をベースに、`acceleration_mode=Auto`のときに限り[`ort::SessionBuilder::with_execution_provider`](https://docs.rs/ort/2.0.0-rc.1/ort/struct.SessionBuilder.html#method.with_execution_providers)でEPを登録する。ortはCPUにフォールバックした旨を`warning`レベルのログで教えてくれる。

<https://github.com/pykeio/ort/blob/v2.0.0-rc.2/src/execution_providers/mod.rs#L229-L231>

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [x] Linux

## その他

**Comment by Hiroshiba** [comment]
良いと思います！！

> ortはCPUにフォールバックした旨をwarningレベルのログで教えてくれる。

まさにこれ（フォールバック時はログを出す）を提案しようと思ってました･･･！
