### ISSUE TITLE
sample.vvmをcrates/test_util/data下に構成するようにする

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#789]
## 内容

sample.vvmをこのリポジトリに置かないようにし、crates/test\_util/data下に構成するようにします。

sample.vvmは50MB近くありますが、最近これに変更を加えることが多くなっています。そこでsample.vvmの中身をバラして置いて、crates/test\_util/data下にZIP(VVM)として再構成するようにします。

### Pros 良くなる点

- manifest.jsonとmetas.jsonのdiffが容易に見れる
    今sample.vvmのmetas.jsonを見たら`order`とか`type`とかが入っていませんでした(デフォルト値が入るので問題無いといえば無いのですが)
- リポジトリが膨らまずにすむ
    今sample.vvmを更新するとGitが警告を出してきますが、やはり警告を出してくるだけの理由は実際にあると思います。

### Cons 悪くなる点

- sample.vvmを出すのに`cargo build`が必要になる
    ただsample.vvmが必要になるのはビルド後なので問題無いはず。

### 実現方法

model/sample.vvmを解体し、model/sample.vvm/…のように各ファイルを置く。

[crates/voicevox_core/src/test_data/model_sources](https://github.com/VOICEVOX/voicevox_core/tree/6df6b75fc7ef648643195e71031bf062f34854a8/crates/voicevox_core/src/test_data/model_sources)というのが今存在していて現役だったりするので、これも統合する。

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
確かにバラした方が絶対良いですね！！
