### ISSUE TITLE
ディレクトリをVVMとして扱えるようにする

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#793]
## 内容

ZIPに加えてディレクトリをVVMの形式として扱うようにします。

例えば #791 でのsample.vvmであれば、/model/sample.vvm/を直接VVMとして扱うことでtest\_util/data下にsample.vvm (ZIP)を作らなくてよくなります。

### Pros 良くなる点

- 開発時の利便性の向上

### Cons 悪くなる点

- ユーザーから見た一貫性が若干損なわれる

## VOICEVOXのバージョン

N/A

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
良さそうに思いましたが、結局テストしないといけない経路がzipとディレクトリの２つになるだけかもと気づきました･･･！

結局zip vvmを作ってそれをテストするコードは必要ですが、逆にzip vvmに依存するテストをそれだけにすることはできるとは思います。
という条件ですが、開発環境が良くなるなら賛成です！採用する場合、ディレクトリも読める機能はサポート対象じゃない形にしとくと楽そう。

**Comment by qryxip** [comment]
> 逆にzip vvmに依存するテストをそれだけにする

そうですね。なんならそのテストはunit testでもよさそう (ZIP自体はtest\_utilで`$OUT_DIR`下に作るとして)。

> ディレクトリも読める機能はサポート対象じゃない形にしとくと楽そう

テストが上記の方針であれば残るはパブリックAPIとしてどうなのという話でしかないので、それがいいですね。実行時にディレクトリ形式を読むときは`INFO`レベルのログで何か言っておくといいのかも。`ディレクトリ{path}をVVMとして読み込みます（note: ディレクトリ形式の読み込み機能は、本ライブラリのテストとデバッグを目的にしたものです）`とか。

**Comment by Hiroshiba** [comment]
@qryxip ログを吐く形、ありに思いました！noteの方はwarnでも良いかも。

あるいはテスト時だけディレクトリでも読めるようにするのもありかも？
（追加行数が5行ぐらいで済むのであれば）

とりあえず賛成の気持ちです！

**Comment by qryxip** [comment]
ですね。あと`VoiceModel`の実装の改修も #791 と同レベル程度には手間がかかりそうでした。

うーん、やめましょうか!
