### ISSUE TITLE
VVMファイル全体をメモリに載せるのをやめる

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/voicevox_core#828]
## 内容

前提として、現在のVVMのインターフェイスとしては次の二段階に分かれています。

1. VVMをZIPとして開き、manifest.jsonとmetas.jsonを読む。開いたZIPは閉じる。
2. VVMをもう一度ZIPとして開き、*.{onnx,bin}を読む。

さて、ZIPの読み方にはZIPをメモリに全部載せてから解凍する方法と、ZIPをファイルとして読みながら解凍していく方法があると思います。[async_zipのAPIの構造](https://docs.rs/async_zip/0.0.17/async_zip/base/read/index.html)にならってこれらをそれぞれ"mem版"と"seek版"と呼ぶことにします。
（["stream"版という概念](https://docs.rs/async_zip/0.0.17/async_zip/base/read/stream/index.html)もあるのですが、ここでは一旦考えないことにします）

最新（v0.0.17および[現時点でのmainブランチ](https://github.com/Majored/rs-async-zip/commit/2d841d600c6d509cb4ecc611001ec339876ca6c9)）のasync_zipのseek版は`tokio::fs`を通すと**大きなファイルエントリに対しては**到底現実的ではない速度であるため、[VOICEVOX COREでは現在すべてmem版を使うようになっています](https://github.com/VOICEVOX/voicevox_core/pull/747#issuecomment-1944328491)。しかし`tokio::fs`ではなく[async-fs](https://crates.io/crates/async-fs)というライブラリを介すると速度が著しく改善され、[zipクレート](https://crates.io/crates/zip)と比べても劣らない、どころか上回ることがわかりました。

ちなみに、async-fsを使う前提のもとsample.vvmの1.(JSON二つ)と2.(ONNX三つ)それぞれに対して{zip, async_zip} × {mem版, seek版}の四通りのベンチを取ったところ、1.と2.どちらも「async_zipのseek版」が最速になりました。1.は252.72 **μ**s、2.は185.90 msでした。

以上のことから #746 をやる際1.と2.の両方を、async-fsを介した上でasync_zipのseek版に戻してしまうことを提案します。メリットは以下の通りです。

### Pros 良くなる点

- メモリ消費の軽減の可能性。こちらに関しては計測していないが、改善はされても悪化はしないはず？
    - もし軽減されるのなら、ENGINEにとってもメリット。 #768 の続きということにもできる？
    - 軽減といってもqwertyさんの元々の実装がseek版だったのですが
- #746 を円滑に行える
    - async-fsはグローバルに保持されるスレッドプールを使うようになっており、「ランタイムレス」で動く。そのためブロッキング版コード上でそのままawaitできる
- #829 も円滑に行える

### Cons 悪くなる点

無いはず。

### 実現方法

#746 と一緒に実装する。

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！　デメリットなさそうであれば問題ないと思います！

とはいえ流石にメモリよりファイル読み込みのが早いのはちょっと違和感があります。
もしかしたらファイルシステムキャッシュが作られてるからかも？

でもここからファイル読み込みの遅延が入ったとしても全然問題ない範囲だと思います！
メモリに載せない選択に賛成です！

**Comment by qryxip** [comment]
> とはいえ流石にメモリよりファイル読み込みのが早いのはちょっと違和感があります。
> もしかしたらファイルシステムキャッシュが作られてるからかも？

あ、mem版についてはZIPファイルを一度ファイルシステムから読み込むところから計測に入れています。
（何故なら現実のユースケースがそうなので）

seek版はファイルの読み込みとZIPの解凍を同時進行するようなイメージです。

**Comment by Hiroshiba** [comment]
あ、なるほどです！問題なさそう！
