### ISSUE TITLE
音声ライブラリの作り方

### ISSUE THREAD

**Issue by mochidukiyukimi** [VOICEVOX/voicevox_core#84]
## 質問の内容

音声ライブラリを自分の声で作りたいです。

## OSの種類/ディストリ/バージョン

windowsだとうれしいですが、何でもいいです。

## その他

Pythonはある程度できます。

**Comment by Hiroshiba** [comment]
このリポジトリはVOICEVOX音声ライブラリの使用に関するリポジトリになります。
作成に関しては話題が違うため、closeさせていただきます。

（ちなみにですが、VOICEVOXは音声ライブラリを自作できるようにするロードマップは今の所ありません。）
