### ISSUE TITLE
ストリーミング処理の対応

### ISSUE THREAD

**Issue by Yosshi999** [VOICEVOX/voicevox_core#853]
## 内容
音声を逐次的に生成する機能を提供し、長い文章の音声を生成する際のレイテンシの短縮をめざす。

関連
- https://github.com/VOICEVOX/voicevox_core/pull/851
- https://github.com/Hiroshiba/vv_core_inference/pull/28

### Pros 良くなる点
- レイテンシの短縮：現状の処理時間は生成する音声の長さに比例して増大するため、長い文章を入力したときにかなりの処理時間を要することがある。処理する部分を固定長のチャンクに分け、逐次的に音声を生成することで入力全体が生成されきる前に音声の再生などを行うことを可能にする。

### Cons 悪くなる点
- 機能の複雑化（どこまで凝った実装をするかによる。後述）

### 実現方法
現在の音声合成処理(synthesis)はaudio queryを入力としてスペクトログラム生成 -> 音声波形生成の順に処理されており、前半と後半の処理時間の比は大体1:10くらいである。また、スペクトログラム生成は内部のモデルの仕様上audio query全体を入力する必要があるが、後半の音声波形生成は十分にマージンを取っていれば任意の位置から任意の長さの音声を生成することができる。

参考：
https://github.com/Yosshi999/streaming_hifigan

そこで、現在 `decode` として処理されている関数を二つに分け、 `generate_full_intermediate` 関数によってえられる中間表現（現状ではスペクトログラム）をいったんユーザーに返し、その中間表現と指定区間を入力として音声を生成する `render_audio_segment` 関数によって最終的な音声を生成する。

#### 実装が必要なもの
- `struct Intermediate` : ユーザーにいったん返す中間表現。実態（スペクトログラム）には触れてほしくないが、lengthは後段の生成区間指定などのために参照可能にする必要がある。
- `blocking::Synthesizer::synthesis_intermediate(&self, &AudioQuery, StyleId, &SynthesisOptions) -> Result<Intermediate>` : 現在の`synthesis()`の途中（decodeの前半部）までを実行する。現在音声が途切れる問題のworkaroundとして前後にパディングがついており、これを音声生成時に取り除くためパディング長をどこかで共有する必要がある。
- `blocking::Synthesizer::render_audio_segment(&self, Intermediate, usize, usize) -> Result<Vec<u8>>` : 中間表現から指定した区間の音声を生成する。
- `nonblocking::*` も必要？
- 各種api露出

#### あるとうれしいもの
- とくに何も考えなくても音声チャンクが手に入るIterator
- 理想的なチャンク長や、いまから音声バッファの再生を始めてもいいか判定してくれる関数
  - 処理時間よりも生成される音声長が長い場合（効率>1)、一個めのチャンクができ次第再生を開始してもよいが、効率が低い場合、再生バッファに詰める音声の生成が追い付かずつっかえるため気を付ける必要がある
  - 正直ユーザー側が実装するべきものかもしれない

**Comment by Yosshi999** [comment]
決めなきゃいけないこと
- `struct Intermediate`に何を詰めるべきか（workaround paddingの長さ、音声長など）
- 指定区間の単位（秒数か24kHz or 24k/256Hzで表現されるフレーム数か）
- 他言語向けapiの設計

**Comment by qryxip** [comment]
名前については、ユーザー向けレベルなら`struct Audio`とかでもよいと思います。というのも"AudioQuery"から作るので。ただ`synthesis_intermediate`の方は…思い付かない。`seekable_synthesis`とか？ (単なる"streaming"というより、任意区間に対して実行できることから)

またintermediateが`Synthesizer`の参照を持って、メソッド`.render()`を生やしてもいいんじゃないかと。
(内部実装レベルではちょっと苦労しそうですが)

```py
audio = synth.seekable_synthesis(amaama_zundamon)

wav_part: bytes = audio.render(slice(t1, t2 + 1))  # `range`?

wav_whole: bytes = audio.render(...)  # `Ellipsis`

# よい感じに分割したイテレータを作る
for wav_part in audio.render_segments():
    ...
```

**Comment by Yosshi999** [comment]
> intermediateがSynthesizerの参照を保持して、メソッド.render()を生やし
https://github.com/VOICEVOX/voicevox_core/pull/854 で組んでみましたがpyo3がまだできていません..
Audioに面倒なライフタイムなどが付いてきているんですがこのままpythonに渡してしまっても大丈夫なんでしょうか

**Comment by Yosshi999** [comment]
```
error: #[pyclass] cannot have lifetime parameters. For an explanation, see https://pyo3.rs/latest/class.html#no-lifetime-parameters
   --> crates\voicevox_core_python_api\src\lib.rs:429:29
    |
429 |     pub(crate) struct Audio<'synth> {
    |
```

Audioの中にsynthesizerの参照を持たせるためにはlifetimeを導入する必要があるが、pythonにはこのままでは渡せない

**Comment by Yosshi999** [comment]
とりあえずrender関数をSynthesizerの中に入れました

**Comment by qryxip** [comment]
とりあえず複雑性を避けた方が議論が円滑になりそうですし、今はそれでよいと思います。

もしやるとしたら、`Arc`を使って`Synthesizer` (`#[pyclass]`の方)を`Clone`にし、

```diff
     #[pyclass]
+    #[derive(Clone)]
     pub(crate) struct Synthesizer {
-        synthesizer: Closable<
-            voicevox_core::blocking::Synthesizer<voicevox_core::blocking::OpenJtalk>,
-            Self,
-            SingleTasked,
+        synthesizer: Arc<
+            Closable<
+                voicevox_core::blocking::Synthesizer<voicevox_core::blocking::OpenJtalk>,
+                Self,
+                SingleTasked,
+            >,
         >,
     }
```

[ouroboros](https://docs.rs/crate/ouroboros)でライフタイムパラメータを消す、という形になるかと思います。

```py
use ouroboros::self_referencing;

#[pyclass]
#[self_referencing]
struct Audio {
    synthesizer: Synthesizer, // `#[pyclass]`の方

    #[borrows(synthesizer)]
    #[not_covariant]
    inner: voicevox_core::blocking::Audio<'this>, // Open JTalkは要らないので、`&voicevox_core::blocking::Synthesizer`自体ではなく`&Status`を持つようにすれば型引数の`O`は消えるはず
}
```

(ただ #832 の考えかたからすると"pyclass"全体じゃなくて[`RwLock`のガード](https://doc.rust-lang.org/stable/std/sync/struct.RwLockReadGuard.html)を持つようにすれば一貫性を保てるのですが、そのためには`Send`という性質をどうにかして得る必要があって、今使っている[blocking](https://docs.rs/crate/blocking)というライブラリのスレッドプールを拝借してそこから[async-channel](https://docs.rs/crate/async-channel)で…ということになりそう)

**Comment by qryxip** [comment]
今のところヒホさん抜きで話が進んでいますが、COREのRust API & Python APIを実装しながら議論する、という今の流れはいいんじゃないかなと思っていることを表明しておきます。

余程複雑なAPIにしない限りはC APIも(ENGINEの)Web APIも後から考えられるはず。

**Comment by Hiroshiba** [comment]
> 指定区間の単位（秒数か24kHz or 24k/256Hzで表現されるフレーム数か）

フレーム数が良いと思います！
ソングのときに考えたのですが、秒にすると丸め込み方向とかも考える必要があって、全部フレーム単位にしたほうが良いな～となりました。

> struct Intermediateに何を詰めるべきか（workaround paddingの長さ、音声長など）

パッと正解が思いつかないですね。。試行錯誤して作っていく感じになるかも。
必要であればガッツリ考えます！！

パディング、つまり音声を出力するために前後何フレーム余分に中間表現を入力する必要があるかですが、これはAPIには露出させない形を目指せると嬉しそうです。
（つまり必要なパディングの計算などはコアの中で勝手にやってくれる形）

> 名前については、ユーザー向けレベルならstruct Intermediateはstruct Audioとかでもよいと思います。というのも"AudioQuery"から作るので。

返り値をクラスインスタンスにするの良いですね！！
どっちかというと最終成果物がAudioなので、AudioRendererとかRendererもわかりやすいかもですね！

> 今のところヒホさん抜きで話が進んでいますが、COREのRust API & Python APIを実装しながら議論する、という今の流れはいいんじゃないかなと思っていることを表明しておきます。

良いと思います！！

**Comment by sevenc-nanashi** [comment]
フレーム数単位にするならSynthesisIntermediateに実際のフレームレートを持たせた方がいいと思います、というのも記憶が正しければtts経由だとサンプリングレート取れないはずなので。（あとラッパー作るのも楽になる）

**Comment by Hiroshiba** [comment]
> フレーム数単位にするならSynthesisIntermediateに実際のフレームレートを持たせた方がいいと思います

これちょっと弱点があって、関数を実行するまでフレームレートがわからないんですよね。
特にUI作ってると先にフレームレートが知りたくなることもあり。

個人的には別のとこに置くのが良いんじゃないかな～～～と思ってます。
VOICEVOX ENGINEリポジトリは、EngineManifestというのを別途作ってframeRateを置いてます。

**Comment by qryxip** [comment]
24kHzから変える予定が無いのなら、グローバルな値として提示してもいいんじゃないかと思います。C APIなら`#define`でもよさそう。
(次点は…VVM単位？)

名前については、`DEFAULT_SAMPLING_RATE`じゃなくて`BASE_`とかにするか、単なる`SAMPLING_RATE`にしてもいいかもしれません。`frameRate`とも統一性が出るんじゃないかと。

**Comment by Hiroshiba** [comment]
たしかに、サンプリングレートもフレームレートも一旦固定で良いと思います！
将来的には変わる可能性はあるだろうけど、もしあるとしてもほんとに先になりそう。

**Comment by Hiroshiba** [comment]
@Yosshi999 さんのおかげで、コア側でストリーミング生成（render）が可能になってきています！！
ありがとうございます！！！

- https://github.com/VOICEVOX/voicevox_core/pull/854

ちょっと今後`VOICEVOX ENGINE`で利用する場合、色々考えることがあるのでまとめてみました！！

---

### compatible engineにどう実装するか
	
* （VOICEVOX ENGINEはコアAPIを直接使わず、`compatible_engine.rs`のものを使っている）
	* 主に互換性の理由だけど
* Synthesizerで露出している API はAudioQueryの入力を想定してる
	* コアC APIにおいて、AudioQueryはjson文字列
* 一方既存の`compatible_engine.rs`のAPIは、ほぼonnxの推論しかしない
	* 入力をTensorで受け取って、出力をTensorで返す
* `AudioQuery`を経由する形にするか、ほぼonnxの推論しかしない形にするかが迷いどころ
* おそらく周囲に揃えるために、後者の`ほぼonnxの推論しかしない`が良さそうに思う
	* `AudioQuery`を経由するとなぜかその関数だけjson文字列を渡さないといけないようになってしまう
	* あと`compatible_engine.rs`からSynthesizerの構造体への依存が発生してしまってちょっとややこしいことになりそう
* `ほぼonnxの推論しかしない`形だと、numpy.array相当のものを入出力する形になるので、音声特徴量（`internal_state: ndarray::Array2<f32>`）が露出する形になってしまう
	* 別にOK！（今までもそうだったので）
	* コアAPIでこの特徴量を露出していなかったのは、保存されると互換性が保てない等の意図があった
	* でも`compatible_engine.rs`は正式サポートしていない形になっているので、仮に保存している人がいたとしても動作保証外だから気にしなくて良い
	* VOICEVOX ENGINE側がちょっと頑張ればOK

### ↑のために実装をどう変えるか

* precompute_renderとrender関数はコアAPI用で、`compatible_engine.rs`じゃなさそう
* なので`compatible_engine.rs`用（≒run_sessionするやつ）を別途作る形が良さそう
* 実はもうある、`generate_full_intermediate`と`render_audio_segment`
* １点変更したいとこ、`precompute_render`のpadding部分を共通化したい
	* たぶんpadding処理を`precompute_render`から`generate_full_intermediate`に移すと良さそう？
	* `precompute_render`はAudioQueryからの翻訳、AudioFeatureへのラップをする感じとか･････？（？）

**Comment by Hiroshiba** [comment]
もう１点、これは @Yosshi999 さんがもしという感じなのですが、VOICEVOX ENGINEへの導入に向けた実装にご興味あったりしませんか！！

ちなみにVOICEVOX ENGINEへの導入は３つステップがあって、必要な能力がちょっとずつ変わってくる感じです。

1つが↑でもあげていた、`compatible_engine.rs`への実装です。
これはRustのコードを読めればできそう･･････････？？？？？（自信なし）
ただ`compatible_engine.rs`内にあるAPIの引数などの形が特殊なので、不明な点が多くあるかも。
これは不明で当たり前なので、何でも聞いていただければ！！！

2つ目がVOICEVOX ENGINEからコアの`generate_full_intermediate`と`render_audio_segment`をとりあえず使えるようにする点です。
`compatible_engine.rs`の中身はC APIとして露出するので、Pythonからこれを叩けるようにVOICEVOX ENGINE側を変更する感じです。
たぶん`voicevox_engine/core/core_wrapper.py`の辺りがそうなはず。
↓とかが`decode_forward`の例で、割と直感的かもです。
https://github.com/VOICEVOX/voicevox_engine/blob/fe3eb765bcc724553f1002f076cf0efdbba29d51/voicevox_engine/core/core_wrapper.py#L448-L458
ただTensor周りというか、numpy.array周りに慣れてないとわけわからないことになります。（この点は全く問題なさそう）

3つ目がおそらく一番難しくて、VOICEVOX ENGINEから`precompute_render`と`render`相当の機能をWEB APIとして実装するとどめの作業です。
`voicevox_engine/app/routers/tts_pipeline.py`あたりが実装ポイントです。↓に`synthesis`APIの実装があります。
https://github.com/VOICEVOX/voicevox_engine/blob/fe3eb765bcc724553f1002f076cf0efdbba29d51/voicevox_engine/app/routers/tts_pipeline.py#L264
この実装が実際[WEB APIの`POST /synthesis`](https://voicevox.github.io/voicevox_engine/api/#tag/%E9%9F%B3%E5%A3%B0%E5%90%88%E6%88%90/operation/synthesis_synthesis_post)として実装されます。
これがなんで難しいかというと、WEB APIをどうすればいいかが自明じゃなく、色々設計するところから始めないといけないためです。
どうやったら使いやすくなるのかとか、何が一般的なのかとかを考えつつ、とりあえず作ってみる感じかなと。

もしご興味あれば･･･！！！

**Comment by Yosshi999** [comment]
> もう１点、これは @Yosshi999 さんがもしという感じなのですが、VOICEVOX ENGINEへの導入に向けた実装にご興味あったりしませんか！！
> 
> ちなみにVOICEVOX ENGINEへの導入は３つステップがあって、必要な能力がちょっとずつ変わってくる感じです。
> 
> 1つが↑でもあげていた、`compatible_engine.rs`への実装です。 これはRustのコードを読めればできそう･･････････？？？？？（自信なし） ただ`compatible_engine.rs`内にあるAPIの引数などの形が特殊なので、不明な点が多くあるかも。 これは不明で当たり前なので、何でも聞いていただければ！！！
> 
> 2つ目がVOICEVOX ENGINEからコアの`generate_full_intermediate`と`render_audio_segment`をとりあえず使えるようにする点です。 `compatible_engine.rs`の中身はC APIとして露出するので、Pythonからこれを叩けるようにVOICEVOX ENGINE側を変更する感じです。 たぶん`voicevox_engine/core/core_wrapper.py`の辺りがそうなはず。 ↓とかが`decode_forward`の例で、割と直感的かもです。 https://github.com/VOICEVOX/voicevox_engine/blob/fe3eb765bcc724553f1002f076cf0efdbba29d51/voicevox_engine/core/core_wrapper.py#L448-L458 ただTensor周りというか、numpy.array周りに慣れてないとわけわからないことになります。（この点は全く問題なさそう）
> 
> 3つ目がおそらく一番難しくて、VOICEVOX ENGINEから`precompute_render`と`render`相当の機能をWEB APIとして実装するとどめの作業です。 `voicevox_engine/app/routers/tts_pipeline.py`あたりが実装ポイントです。↓に`synthesis`APIの実装があります。 https://github.com/VOICEVOX/voicevox_engine/blob/fe3eb765bcc724553f1002f076cf0efdbba29d51/voicevox_engine/app/routers/tts_pipeline.py#L264 この実装が実際[WEB APIの`POST /synthesis`](https://voicevox.github.io/voicevox_engine/api/#tag/%E9%9F%B3%E5%A3%B0%E5%90%88%E6%88%90/operation/synthesis_synthesis_post)として実装されます。 これがなんで難しいかというと、WEB APIをどうすればいいかが自明じゃなく、色々設計するところから始めないといけないためです。 どうやったら使いやすくなるのかとか、何が一般的なのかとかを考えつつ、とりあえず作ってみる感じかなと。
> 
> もしご興味あれば･･･！！！

やってみます。実装順は上の通りで確定でいいですかね？とりあえずはdecode関数を`generate_full_intermediate`と`render_audio_segment`の二つに分けたものを作ればよいでしょうか

**Comment by Yosshi999** [comment]
ところでRustでpanicした場合capiからはどう見えるんでしょうか？セグフォですか？

**Comment by Hiroshiba** [comment]
うおーありがとうございます！！！

> 実装順は上の通りで確定でいいですかね？

はい、この流れが良いかなと･･･！

> とりあえずはdecode関数をgenerate_full_intermediateとrender_audio_segmentの二つに分けたものを作ればよいでしょうか

ですね！！
あ、decode関数は一旦そのまま残していただければ･･･！！
