### ISSUE TITLE
ストリーミング処理のC API実装

### ISSUE THREAD

**Issue by Yosshi999** [VOICEVOX/voicevox_core#866]
## 内容
https://github.com/VOICEVOX/voicevox_core/issues/853 をC APIのcompatible_engineで対応させる

### Pros 良くなる点
ストリーミング処理をvoicevox_engineに実装するための足掛かりになる

### 実現方法
以前の議論：https://github.com/VOICEVOX/voicevox_core/issues/853#issuecomment-2444436727

現在のdecode_forwardを分割して`generate_full_intermediate`と`render_audio_segment`を実装することになるが、一つ問題がある。
中間生成物の音声特徴量（internal_state: ndarray::Array2<f32>）が露出することは問題がないが、この配列のwidth (特徴次元数）が未定義であるため、APIを呼び出す側がバッファサイズを設定できない

解決方法：

方針1. spectrogramはrust側に管理してもらう→compatible_engineにステートを持たせてhandleもしくはvoid*でAPIとやりとりする (lockやmemory周りが面倒そう)
方針2. generate_full_intermediateは二回呼んでもらう。一回目はoutput=nullptrでスペクトログラム次元数 or 配列長を返し、二回目でoutputにデータを埋める (二度手間、若干の速度低下）
方針3. スペクトログラム次元数を定数もしくはstyle_idに対する関数のAPIを生やす（モデルに変更が入った時の保守が面倒）
そもそも中間生成物が二次元配列であること自体を隠蔽すべき？そうなると方針1しかなさそう

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

特徴次元数について、かなり特殊になってしまうのですが、ちょっと関数の引数として受け取る形でどうでしょうか･･･？
VOICEVOX ENGINE側から渡してもらう設計です！

↓ご説明です 🙇 

<details>

実はdecodeへ入力するときに特徴量次元が必要になっています。
音素をonehotベクトルにして入力してるので、２次元配列にするには音素数がです。
どうやって取り扱ってるか調べてみると、`compatible_engine`の関数の引数で指定する形になっていました！！！

コア側の`compatible_engine`の実装
https://github.com/VOICEVOX/voicevox_core/blob/e094b528aadbf54535264b2b7baa1275e33c300a/crates/voicevox_core_c_api/src/compatible_engine.rs#L293

エンジン側からコアを呼ぶ部分の実装
https://github.com/VOICEVOX/voicevox_engine/blob/9506de28639a067cf0540aa1725586d15c9bcf2c/voicevox_engine/core/core_wrapper.py#L725

ちなみに固定値80なのでほんとは定数でもよいのですが、APIは一貫性を持たせて以前のに合わせるのが良さそうなので、この形で行ければと思った次第です。。。。。
なのでVOICEVOX ENGINE側にはマジックナンバー80を`core_wrapper.py`辺りに書く感じになると思います。

なんかいびつな実装ですが。。。。。この形でいければと。。。。 🙇 
ちょっと３年くらい経ってるので考慮漏れが多くなってしまっていて申し訳ないです 🙇 
わからない点・変な点あったらなんでもお聞きください！！！

</details>

**Comment by qryxip** [comment]
方針3.でよいと思います。

<details>
<summary>ちなみにもし方針1.にする場合はこうなるかなと</summary>

```rs
use std::ptr::NonNull;

use ndarray::Array2;

// この`AudioFeatureInternalState`はポインタでしかやりとりしないので、使う側 (i.e. VOICEVOX ENGINE)
// がサイズやアラインメントを知らなくても全く問題無い
type AudioFeatureInternalState = Array2<f32>;

// SAFETY: voicevox_core_c_apiを構成するライブラリの中に、これと同名のシンボルは存在しない
#[unsafe(no_mangle)]
pub unsafe extern "C" fn generate_full_intermediate(
    // vvvvvvvvvvvvvvvvvv
    length: i64,
    phoneme_size: i64,
    f0: *mut f32,
    phoneme: *mut f32,
    speaker_id: *mut i64,
    // ^^^^^^^^^^^^^^^^^^ ここまで`decode`と同じ
    output: NonNull<Box<AudioFeatureInternalState>>, // ABI的に`*mut *mut AudioFeatureInternalState`として扱ってよく、Cの表現では`**AudioFeatureInternalState`となる
) -> bool {
    let internal_state: AudioFeatureInternalState = todo!();

    output.write_unaligned(internal_state.into());
    true
}

// SAFETY: voicevox_core_c_apiを構成するライブラリの中に、これと同名のシンボルは存在しない
#[unsafe(no_mangle)]
pub unsafe extern "C" fn render_audio_segment(
    // vvvvvvvvv
    length: i64,
    // ^^^^^^^^^ `decode`と同じ
    internal_state: &AudioFeatureInternalState, // ABI的には`*const AudioFeatureInternalState`として扱ってよく、Cの表現では`const *AudioFeatureInternalState`となる
    // vvvvvvvvvvvvvvvvvv
    speaker_id: *mut i64,
    output: *mut f32,
    // ^^^^^^^^^^^^^^^^^^ `decode`と同じ
) -> bool {
    todo!();
}

// SAFETY: voicevox_core_c_apiを構成するライブラリの中に、これと同名のシンボルは存在しない
#[unsafe(no_mangle)]
pub extern "C" fn delete_audio_feature_internal_state(
    internal_state: Box<AudioFeatureInternalState>, // ABI的には`*mut AudioFeatureInternalState`として扱ってよく、Cの表現では`*AudioFeatureInternalState`となる
) {
    // `Box`として扱った時点で、スコープから外れたときにデストラクトされることが決定されるが、
    // 未使用変数警告を黙らせるために明示的に`drop`しておく
    drop(internal_state);
}
```
</details>

**Comment by Hiroshiba** [comment]
@qryxip 
最初は特徴量次元数は80固定にして、次元数が複数になったら方針3を実装というのはどうでしょう…？👀

（たぶんcompatible_engineは以前のAPIと合わせた方が使い勝手が良くて、特にダメな理由がなければVOICEVOX ENGINEから渡してもらう設計にした方が良いかなーーーと思っており。。。）

**Comment by qryxip** [comment]
あ、方針3.自体を読み違えていました。ヒホさんの案で良いと思います！

**Comment by Hiroshiba** [comment]
すみませんありがとうございます 🙇 🙇 🙇

**Comment by Yosshi999** [comment]
https://github.com/VOICEVOX/voicevox_core/issues/866#issuecomment-2452259729
これで進めていきます。

もう一つ課題が見つかりまして、`render_audio_segment` がかなり素朴な実装で、チャンク処理の際のマージン追加をどこかでやらないといけないんですが、

* compatible engineのc apiの中でやる ( `render_audio_segment` の引数や実装がsynthesizerのものと異なってくる)
* voicevox engineでやる (apiユーザーにマージン処理を書かせるのは酷？）

どちらが良いでしょうか。無音パディングはvoicevox engineでやっていたかとおもうのでマージン処理もengineにしてしまったほうが個人的にはいいのかなと思います（rust側のtestでもマージン処理を追加で書くことになりますが..)

**Comment by qryxip** [comment]
VOICEVOX ENGINEでやり、VOICEVOX ENGINEからは`precompute_render`と`render`相当のAPIを提供する、という話であるという認識でいました。

COREとENGINEで同じような実装をすることになると思いますが、Discordのここ(↓)の前後で議論してた「二重実装」はそのことを指していました。今のところ、仮にcompatible_engineをPyO3に置き換えることになっても、この二重実装だけは続けることになるかなと思っています。
<https://discord.com/channels/879570910208733277/893889888208977960/1300035516250456065>

**Comment by qryxip** [comment]
あ、マージン追加というのを誤読していました。

以下のコードは #854 以前ものですが、これがそのまま「ENGINEから見たCOREのAPI = compatible_engine」の実装になっています。これに従えば、マージン処理はcompatible_engine、というより`fn render_audio_query`内にあった方がよいかなと思います。
<https://github.com/VOICEVOX/voicevox_core/blob/fdae73ac3fe91b60fbe7a20f71c19c15f588351b/crates/voicevox_core/src/synthesizer.rs#L858-L1011>

(というか今、compatible_engineから`decode`呼んだらパディング処理すっぽかされるのでは…？)

**Comment by Yosshi999** [comment]
> compatible_engineからdecode呼んだらパディング処理すっぽかされる

たしかにそうですね
https://github.com/VOICEVOX/voicevox_core/pull/854 をrevertしないといけないのかな...

**Comment by qryxip** [comment]
丸ごとrevertよりは、パディング処理とマージン処理を移動というのがよいかなと。というのも #854 ではパブリックAPIの形も決めてたので。
(あと #865 をマージしちゃったので、そこそこ大きくコンフリクトしそう)

**Comment by Yosshi999** [comment]
別PRで修正します

**Comment by Yosshi999** [comment]
→ https://github.com/VOICEVOX/voicevox_core/pull/867

**Comment by Yosshi999** [comment]
ちょっとこんがらがってきたんですが、もともと

* `Synthesizer::decode` ... 無音パディングを付加
* `Synthesizer::synthesis` ... `Synthesizer::decode` を利用
* `extern "C" fn decode_forward` ... `Synthesizer::decode` をそのまま利用

だったものに対して #854 は

* `Synthesizer::generate_full_intermediate` ... 無音パディングなしで中間物生成
* `Synthesizer::render_audio_segment` ... マージンなしで与えられた音声特徴全体で音声生成
* `Synthesizer::decode` ... `Synthesizer::generate_full_intermediate` と `Synthesizer::render_audio_segment` を利用
* `Synthesizer::precompute_render` ... 無音パディングを付加して `Synthesizer::generate_full_intermediate`
* `Synthesizer::render` ...  マージンを付けて指定された区間で `Synthesizer::render_audio_segment` （+暗黙的にパディングが除去される）
* `Synthesizer::synthesis` ... `Synthesizer::precompute_render` と `Synthesizer::render` を利用
* `extern "C" fn decode_forward` ... `Synthesizer::decode` をそのまま利用

になっていたんですが、これを

* `Synthesizer::generate_full_intermediate` ... 無音パディング**を付加して**中間物生成
* `Synthesizer::render_audio_segment` ...  **マージンを付けて指定された区間で**音声生成
* `Synthesizer::decode` ... `Synthesizer::generate_full_intermediate` と `Synthesizer::render_audio_segment` を利用
* `Synthesizer::precompute_render` ...  `Synthesizer::generate_full_intermediate` を利用
* `Synthesizer::render` ...  `Synthesizer::render_audio_segment` を利用
* `Synthesizer::synthesis` ... `Synthesizer::precompute_render` と `Synthesizer::render` を利用
* `extern "C" fn decode_forward` ... `Synthesizer::decode` をそのまま利用
* `extern "C" fn generate_full_intermediate` ... `Synthesizer::generate_full_intermediate` をそのまま利用
* `extern "C" fn render_audio_segment` ... `Synthesizer::render_audio_segment` をそのまま利用

とすればいいですかね？無音パディング幅をどこに記録するか問題になりそうですが、面倒なのでハードコーディングしてしまったほうがいいですかね

**Comment by qryxip** [comment]
分類については私もその認識です。

ただ`render_audio_segment`のシグネチャを今思いだしたのですが、そうか、切り取った後の`spec`を入力に取るんでしたね。うーん。`(spec丸ごと, start, stop, style_id)`にしちゃってもよいのかも？どうせ他のやつもONNXのシグネチャとは微妙に違ってるし。

**Comment by Hiroshiba** [comment]
すみません遅くなりました！！

@Yosshi999 さんのまとめめちゃくちゃ参考になりました！！！！
ソースコード読みながら見たのですが、自分の理解と完全に一致しました！！！！

僕もお２人と一緒の意見で、`spec, start, end`引数を`render_audio_segment`が受け取る（`Synthesizer`内のも`extern "C" fn`も）のが良さそうに感じてます！
@Yosshi999 さんの仰ってる

> 無音パディング幅をどこに記録するか問題になりそう

これをどうしようか迷ってます。。。
ちょっとまだ考えきれてないんですが、アイデア思いついたんで提案まで 🙇 

---

`Synthesizer::generate_full_intermediate`を、無音パディングを追加して中間物を生成したあと**renderのマージン分だけ残して返す**というのはどうでしょう････････？

整理すると、`generate_full_intermediate`の処理がこんな感じ：

1. `0.4(秒)*93.75(フレームレート)=37.5→37？`フレームの無音パディングをする
2. 生成する。元のフレーム長＋`37*2`の中間物ができる
3. renderのマージン分（14フレーム）だけ残す。両端`37-14`ずつ短くする。
4. returnする。

こうすれば`render_audio_segment`側は無音paddingの除去を考えず、与えられたspecをそのままrenderすれば良くなるかなと！
（もちろん、`14*2`分マージンされたspecを渡すようにしないとですが）

これを @Yosshi999 さんの表に適用してみるとこうなるかな～と思ってます。どっか間違ってるかも。。。
（いまのmainブランチからの実装の変更部分を訂正線と太字で書いてます）

| Synthesizer | Function | Description |
|-------------|----------|-------------|
| Synthesizer | generate_full_intermediate | 無音パディング**を付加して**中間物生成、**マージン込みのを返す** |
| Synthesizer | render_audio_segment | マージンなしで与えられた音声特徴全体で音声生成 |
| Synthesizer | decode | `Synthesizer::generate_full_intermediate` と `Synthesizer::render_audio_segment` を利用 |
| Synthesizer | precompute_render | <s>無音パディングを付加して</s> `Synthesizer::generate_full_intermediate` |
| Synthesizer | render | マージンを付けて＆指定された区間で `Synthesizer::render_audio_segment` <s>（+暗黙的にパディングが除去される）</s> |
| Synthesizer | synthesis | `Synthesizer::precompute_render` と `Synthesizer::render` を利用 |
| extern "C" | decode_forward | `Synthesizer::decode` をそのまま利用 |
| extern "C" | generate_full_intermediate | `Synthesizer::generate_full_intermediate` をそのまま利用 |
| extern "C" | render_audio_segment | `Synthesizer::render_audio_segment` をそのまま利用 |

**Comment by Yosshi999** [comment]
マージン幅やパディング幅はvoicevox_coreにマジックナンバーとして埋め込んでしまって、voicevox_engineやAPIユーザーには全く意識させないのがいいのかなと思います。中間生成物をユーザーがいじるのは完全に保証対象外にしてしまい、spec全体, start, endの組でAPIとやり取りするのが一番楽そう

無音パディング幅をどこに記録するかについてもマジックナンバーにしてしまえば問題なくなります

**Comment by Hiroshiba** [comment]
たしかにと思ったのですが、voicevox engine側はメモリ確保が必要なので、少なくともprecompute用のマジックナンバーは必要になるかもです！！

**Comment by qryxip** [comment]
一応、方針1. (`void*`で扱う)だとマジックナンバーはCORE内に完全に閉じると思います。その場合デストラクトをどこでするかという問題が起きますが、`__del__`とかでよさそう。
<https://github.com/VOICEVOX/voicevox_core/issues/866#issuecomment-2452886226>

**Comment by Hiroshiba** [comment]
AudioFeatureを`compatible_engine`側で持っておく感じですよね。
今まで`compatible_engine`はdelete用の関数が不要な設計だったので、まあちょっと不揃い感はあるな〜くらい。
（これ勘違いでdelete用の関数が既存なら、その方針でも全然良さそう）

うーんどれが良いかな〜〜〜

ほんとになんとなくなんですが、specを毎回受け渡すのは、実装によってはメモリコピーが結構発生しそうなので避け調子が良い気がしてます。
もし長さが30秒の場合`30秒 * 93.75フレーム/秒 * 80特徴量 * 4バイト = 0.9MB`で、仮に0.2秒ごとに生成したいとなると実装によっては課題になりえるかも･･･？くらいの気持ち。
まあメモリコピーしないように実装すれば良いのですが、考えないといけないことが増えるので避けても良いのかもくらい！

@qryxip さんのBox使う形式はdelete関数が必要になるのでVOICEVOX ENGINE側の実装が多少ややこしくなるかも、くらい。
これと、`render_audio_segment`に必要な分だけ渡すようにする設計どっち取るかって感じかなぁ。

メモリコピーが発生しないように意識して実装するか、delete関数を召喚するか、必要な範囲の計算をVOICEVOX ENGINE側でやるか、どれにしますかねって感じかなと！！！

個人的には、これまでもVOICEVOX ENGINE側に前処理書いてる（[こういうのとか](https://github.com/VOICEVOX/voicevox_engine/blob/9506de28639a067cf0540aa1725586d15c9bcf2c/voicevox_engine/tts_pipeline/tts_engine.py#L657-L707)）のと、あとメモリコピー意識とdelete関数召喚は避けたい気持ちもあり、まあ今回もVOICEVOX ENGINE側でコード書く感じが良いのかな〜とちょっと思ってます！

**Comment by qryxip** [comment]
> メモリコピー

メモリについてだいぶ齟齬が発生しかけてる気がするので私の考えを述べておくと、#687 をやることを前提にした場合スレッドプールの利用が不要になり、どの方法であっても分割部分のコピーは避けられるかなと思っています。何故ならRustの`ndarray`にもNumPyにもviewという概念があるので。
(ちなみに #687 をやるための準備は #865 で終わっているので、[`ort::Session::run_async`](https://docs.rs/ort/2.0.0-rc.5/ort/struct.Session.html#method.run_async)を使うだけだと思います)

ENGINE側でNumPyを持つ場合は`generate_full_intermediate`の出力 (`spec`全体)を一度だけコピーすることになり、CORE側に`spec`を閉じ込める場合はコピー回数は完全に0回になるかなと思ってます。

> delete関数

`__del__`というのはGC上のファイナライザを意図していました。ただもしかするとそもそもGCじゃなくて、ユーザーのWeb APIリクエストでdeleteすることになるのでは？という気もしています。というのもユーザーが`AudioFeature`を「使い終わ」ったタイミングがこちら側からわからないかもしれないんじゃないかと。

**Comment by Hiroshiba** [comment]
> #687 をやることを前提にした場合、どの方法であっても分割部分のコピーは避けられるかなと思っています。

なるほどです。
まあこの辺り色々結局考える必要があるのを避けられる、ってのがメリットかなぁと！

> ただもしかするとそもそもGCじゃなくて、ユーザーのWeb APIリクエストでdeleteすることになるのでは？という気もしています。

これはちょっと読み切れてないんですが、おそらくWEBリクエストのセッションが切れたら破棄が手っ取り早いそうかな～～～～と思ってます。
まあどうなるにせよ、Python側のAudioFeatureの実装は想像つきます。
ちなみに実はVOICEVOX ENGINEは`__del__`を使ったことがないはず。
https://github.com/search?q=repo%3AVOICEVOX%2Fvoicevox_engine%20__del__&type=code

---

ただまあもうプルリクエスト作ってくださってるので、あとはcompatible_engine.rsの実装と、PythonのVOICEVOX ENGINEの実装を想像しつつ、どれがいいか選ぶ感じかな～～～と。

* specをまるまる全部受け渡しし、render_audio_segmentのシグネチャを`(spec, start, end)`にする
	* 🤔 メモリコピーが発生しないように意識して実装する
	* 🤔 メモリ確保のため、VOICEVOX ENGINE側にパディング分のマジックナンバーが必要
* AudioFeatureのIDを受け渡しし、render_audio_segmentのシグネチャを`(AudioFeatureId, start, end)`にする
	* 🤔 他の API と不揃いになる
	* 🤔 delete関数が増える
* `render_audio_segment`のシグネチャを`(spec)`にする
	* 🤔 今のプルリクエストを変える必要がある
	* 🤔 範囲計算のため、VOICEVOX ENGINE側にマージン分のマジックナンバーが必要
	* 🤔 spec範囲の計算をVOICEVOX ENGINE側でもやる

個人的には「`render_audio_segment`のシグネチャを`(spec)`にする」が設計で考えることが少ないので（実装は考えることあるけど）、これが一番丸いんじゃないかな～～～と思ってます。
とりあえず実装してみて、Python側も作っちゃうのが良いのかも！！

**Comment by qryxip** [comment]
>  `render_audio_segment`のシグネチャを`(spec)`にする

一貫性で言うと、「ONNXの入出力を補正する役割はCORE側に持たせる」というのが方針であるという理解を私はしていました。例えばソングで言うと #749 という話もあったと思います。

あと`MARGIN=14`については、未来永劫…とは言わずとも数年は変わらないとみてよいのか、という点を考慮した方がよいんじゃないかと思っています。

---

ところでパディング分のマジックナンバーですが、delete関数が駄目ならコールバックでCOREからENGINEに伝えるという手もあると思います。`ctypes`なら楽々できるはず。イメージとしては次のような感じ:

```rs
use std::{ptr::NonNull, slice};

/// # Safety
///
/// * ∀n>0, the pointer that `out(n)` returns must be valid as Rust's `&mut [f32; n]`.
#[unsafe(no_mangle)] // SAFETY: there is no other global function of this name
pub unsafe extern "C" fn fill_array(out: extern "C" fn(usize) -> NonNull<f32>) {
    const SIZE: usize = 5;

    let out = out(SIZE);
    let out = unsafe { slice::from_raw_parts_mut(out.as_ptr(), SIZE) }; // SAFETY: the safety requirement of this function
    out.fill(42.);
}
```

```py
import sys
from ctypes import CDLL, CFUNCTYPE, c_size_t

import numpy as np

lib = CDLL(PATH_TO_LIBRARY)

buf = np.array([], dtype=np.float32)
print(f"{buf=}", file=sys.stderr)

@CFUNCTYPE(c_size_t, c_size_t)
def out(size: int) -> int:
    buf.resize((size,))
    print(f"{buf=}", file=sys.stderr)
    return buf.ctypes.data

lib["fill_array"].argtypes = (c_size_t,)
lib["fill_array"].restype = None

lib["fill_array"](out)
print(f"{buf=}", file=sys.stderr)
```

```console
buf=array([], dtype=float32)
buf=array([0., 0., 0., 0., 0.], dtype=float32)
buf=array([42., 42., 42., 42., 42.], dtype=float32)
```

**Comment by Hiroshiba** [comment]
@qryxip 
> 一貫性で言うと、「ONNXの入出力を補正する役割はCORE側に持たせる」というのが方針であるという理解を私はしていました。

たーーーしかに！！

まーーーー、`compatible_engine.rs`は「onnxの入出力の値を補正するけど、データの形を変えるのはエンジン側がやる」という切り分けになる･･･かもです･･･！
ぶっちゃけこれは、ENGINEの機能はPythonに持たせたほうが圧倒的に楽という過去に引っ張られてるので、今の最適解は違っているかもしれません。

ちょっと申し訳ないのですが、今回はこの形で･･･ 🙇 🙇 🙇 
VOICEVOX ENGINE実装の際に明らかにダメな点があったらまた再考できれば･･･ 🙇 

将来VOICEVOX ENGINEがPython API使うようになる場合、`compatible engine`を使うかSynthesizerを使うか分かりませんが、前者の場合はの再設計しても良いかもです。
たぶんNdarrayは全部隠蔽しちゃうのが良い気がする！！

> あとMARGIN=14については、未来永劫…とは言わずとも数年は変わらないとみてよいのか、という点を考慮した方がよいんじゃないかと思っています。

ほぼ変わらない気がしますが、数年以内に変わる可能性はゼロではないかもしれません。
将来変えられるように、引数でmarginを与えられるようにしておいた方が良さそう･･･！！

> コールバックでCOREからENGINEに伝える

本当だ、結構簡単ですね。
まあちょっと何が起こるかわからないので、コールバックは避け調子のが無難かもと感じました。
必要になったらget関数が良いかなと！

**Comment by qryxip** [comment]
> ちょっと申し訳ないのですが、今回はこの形で･･･ 🙇 🙇 🙇 
> VOICEVOX ENGINE実装の際に明らかにダメな点があったらまた再考できれば･･･ 🙇 
>
> 将来VOICEVOX ENGINEがPython API使うようになる場合、`compatible engine`を使うかSynthesizerを使うか分かりませんが、前者の場合はの再設計しても良いかもです。
> たぶんNdarrayは全部隠蔽しちゃうのが良い気がする！！

なるほど。まあ #867 はとりあえず今のまま進めた方がよさそうですね。
