### ISSUE TITLE
[Flutter] Synthesis speed for a short sentence is not fast

### ISSUE THREAD

**Issue by hantrungkien** [VOICEVOX/voicevox_core#883]
## 質問の内容

Sorry I'm not fluent in Japanese. We have implemented voicevox on Flutter/iOS app but the synthesis speed for a short sentence is not fast.

Do you have any solutions or advice for us? Here is the synthesis result with the text "シンチャオ" on real device iPhoneX - iOS 16.7.10 in profile mode.

My example app: https://github.com/hantrungkien/flutter_voicevox_tts

<img src="https://github.com/user-attachments/assets/52865860-1e62-4b72-92db-cea656ae7744" alt="IMG_6013" width="300"/>

## VOICEVOXのバージョン

[0.15.0-preview.16](https://github.com/VOICEVOX/voicevox_core/releases/tag/0.15.0-preview.16)

## Flutter Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by Hiroshiba** [comment]
Thank you for creating the issue! Could you provide more details about the environment in which you ran the application? For example, which generation of iOS devices and what model did you use, or if it was a simulation environment, what are the specs of the PC?

Depending on the device, it might take some time to process. (Although, I do feel it might be a bit slow?)

---

issue作成ありがとう！
どのような環境で実行しましたか？
例えばiOSデバイスの何世代のものでどの機種か、あるいはシミュレーション環境でPCのスペックはどれぐらいなのかを聞きたいです。

デバイスによってはこれくらい時間かかるかもしれません。
（それにしても少し遅いかも？と感じています）

**Comment by hantrungkien** [comment]
@Hiroshiba, thanks for replying.

I tested on a real iPhone X device, but the speed is also slow on some other devices (my QA team reported).

I used the model from https://github.com/VOICEVOX/voicevox_fat_resource/tree/main/core/model.
