### ISSUE TITLE
DirectML版の動作チェック

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#90]
## 内容

DirectML版が実装されました。 https://github.com/VOICEVOX/voicevox_core/pull/81
いろんなデバイスや環境で問題なく動きそうかをチェックするissueです。
（もしよければご協力ください！）

- [x] 製品版をビルドする @Hiroshiba 

↑ビルドしました！
https://github.com/VOICEVOX/voicevox_core/releases/tag/0.12.0-preview.0

- [x] Windows10で動くかチェック
- [x] Windows11で動くかチェック
- [x] NVIDIAのGPUで動くかチェック
- [ ] RADEONのGPUで動くかチェック

**Comment by Hiroshiba** [comment]
DirectML版の製品版をビルドしてみました。
https://github.com/VOICEVOX/voicevox_core/releases/tag/0.12.0-preview.0

@Oyaki122 さん、もしよかったらご確認頂けると･･･！

**Comment by Oyaki122** [comment]
Windows11 x64 GTX1060での動作を確認しました!

**Comment by y-chan** [comment]
製品版プレビューを利用してVOICEVOX Engineを起動しようと(https://github.com/y-chan/voicevox_engine/tree/feature/directml/ )してみました。
Windows 11 x64 RTX3090で動作しました。

**Comment by o108minmin** [comment]
Windows10 + RADEON GPU(AMD Radeon RX 6700 XT)の動作確認(example/python)をしました  

https://gist.github.com/o108minmin/b09a39af8d739ecc586d157335af094c

@Hiroshiba  
すいません、お手数ですが下記が不安なのでご確認いただけると動作確認の保証が取れると思います

- configure.py利用時のコマンドが `python configure.py --use_directml --voicevox_version 0.12.0-preview.0` であっているかどうか
- 動作結果: エラーなく、クリアな声のwavが生成された が想定通りかどうか

**Comment by Hiroshiba** [comment]
おお、RADEONでの動作確認助かります！！

configure.pyは合ってそうに思います。
`example/python`実行時の`run.py`の実行時に`--use_gpu`を付けていればGPU実行されるはずです。
が、本当に実行されているかどうかは、タスクマネージャーのGPUが実際に使われていそうか（使用メモリ増えてるか、グラフが変動しているかなど）を調べるのが一番確実かなと思います！

**Comment by Rollphes** [comment]
初めまして、@y-chan からの紹介で動作確認に参加した者です。
Windows 10 + Radeon GPU(Radeon RX 6700XT)で上の方と同じように動作確認できました。
`--use_gpu`でGPU使用率の上昇も確認できました。
ただ、@y-chan のDirectML版エンジンを利用しようとしてみたところ、下記のようなエラーに遭遇し、エンジンが起動できませんでした。
```
2022-03-12 23:57:38.0921296 [E:onnxruntime:, inference_session.cc:1449 onnxruntime::InferenceSession::Initialize::<lambda_5e5a5715154ad0f74cbb1c2a0e787fd0>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\FusedGraphKernel.cpp(64)\onnxruntime.dll!00007FFD17ACED9A: (caller: 00007FFD17ACE20C) Exception(1) tid(42d8) 80004002 インターフェイスがサポートされていません
```

**Comment by o108minmin** [comment]
@Hiroshiba 
> 長めの文章を入力してみて、タスクマネージャーのGPUが実際に使われていそうか（使用メモリ増えてるか、グラフが変動しているかなど）を調べるのが一番確実かなと思います！

ありがとうございます。手元の複数ツールで確認したところ、実行に合わせて使用メモリなどの指標がスパイクしているのを確認しました。RADEON GPUは使用されていそうですね

![image](https://user-images.githubusercontent.com/6399740/158025336-599a7b2d-4079-4608-b73b-4f5770177585.png)

**Comment by Hiroshiba** [comment]
おー！！！　ご確認いただきありがとうございます！！
DirectML版はRadeon GPUでも問題なく動きそうですね･･･！

ちゃんと動きそうだということに自信を持てました。
目的を達成できたのでこのissueは閉じたいと思います。ご協力ありがとうございます！
