### ISSUE TITLE
last_error_messageではなく標準出力にエラーログを流すようにする

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#95]
## 内容

エラーが出た後にエラーメッセージをgetする方式にしていますが、エラーログはglobal変数で管理しており、何かと不便です。
実際に使う際、エラーメッセージが見れればOKだと思うので、stderrにエラーログを流す運用に変えるissueになります。

この辺りの内容です

- https://github.com/VOICEVOX/voicevox_core/pull/93#issuecomment-1064818018

### Pros 良くなる点

コードの見通しが立ちやすい

### Cons 悪くなる点

実際に利用する際、「エラーメッセージをダイアログに表示する」等ができなくなる？

### 実現方法

srd:cerr

## その他

ライブラリ実行時の標準エラーってキャプチャできるのでしょうか。
別プロセスを作らないと無理･･･？

**Comment by aoirint** [comment]
> ライブラリ実行時の標準エラーってキャプチャできるのでしょうか

Python ctypesで共有ライブラリが吐き出す標準エラー出力を抑制したことがあったので、実装例を貼っておきます。
`os.devnull`を`io.StringIO`にすればキャプチャできそうではあります。

システムコールdup, dup2が呼び出せれば、ほかの言語でも同じことはできそう・・・？

- <https://blog.aoirint.com/entry/2019/python_ctypes_suppress_log_decorator/>

```python
# 標準出力・標準エラー出力の抑制デコレータ
def silent(verbose=False):
    def _silent(func):
        def wrapper(*args, **kwargs):
            if not verbose:
                devnull = open(os.devnull, 'w')
                stdout = os.dup(1)
                stderr = os.dup(2)
                os.dup2(devnull.fileno(), 1)
                os.dup2(devnull.fileno(), 2)

            res = func(*args, **kwargs)

            if not verbose:
                os.dup2(stdout, 1)
                os.dup2(stderr, 2)
                devnull.close() # NOTE: closeの保証がない?

            return res

        return wrapper
    return _silent


class Network:
    def __init__(self, meta_file, cfg_file, weights_file, verbose=False):
        @silent(verbose=verbose)
        def _init():
            self.net = load_net(cfg_file.encode('ascii'), weights_file.encode('ascii'), 0) # c function (ctypes)
            self.meta = load_meta(meta_file.encode('ascii')) # c function (ctypes)

        _init()
```

**Comment by Hiroshiba** [comment]
なるほどです！！
そもそもエラーログがサービスで必要になることは珍しいこと、キャプチャする方法はありそうなこと、どうしてもエラーログを得たいときは別プロセスで起動すれば良いことを考えて、エラーログはstderrに直接流すようにする設計で良いと思いました！！
（@aoirint さんありがとうございます！）

**Comment by qryxip** [comment]
C++からRust化した時点、というより #126 の時点で達成していると思うのでcloseします。
