### ISSUE TITLE
製品版のTTSライブラリの動作確認

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_core#97]
## 内容

TTSができるはずのコードでビルドしてみました。
https://github.com/VOICEVOX/voicevox_core/releases/tag/0.12.0-preview.1

動作確認したり、いろんな知見を集められればと思います。

**Comment by Hiroshiba** [comment]
windows環境で実行してみたのですが、DLL読み込み時にエラーが出ました。
（原因がわからなかったので報告のみです。。）
```bash
root_dir_path:
loading core...
The given version [10] is not supported, only version 1 to 9 is supported in this build.     
loaded!
initializing...
Segmentation fault
```

**Comment by aoirint** [comment]
> The given version [10] is not supported, only version 1 to 9 is supported in this build.

モデル変換時かTTS実行時のONNX Runtimeのバージョンが影響していそう？（TTS実行時のONNX Runtimeのバージョンが古いかもしれません）

https://github.com/microsoft/onnxruntime/blob/ce10d7d23130981469d8851c822d61152f88cfac/onnxruntime/core/session/onnxruntime_c_api.cc#L2551

**Comment by Hiroshiba** [comment]
うおお･･･仰るとおり、ローカルにあるonnxruntimeのバージョンが古いだけでした･･･。助かりました 🙇‍♂️ 
そしてwindowsのCPU環境でTTSが動くことを確認しました！！！！

**Comment by shigobu** [comment]
自作C#アプリで動作確認できました。
https://github.com/shigobu/voicevox_capi_cstest

**Comment by takana-v** [comment]
Pythonのctypes実装で動作確認できました。

**Comment by Hiroshiba** [comment]
確認ありがとうございます！！
とりあえずOKということで、こちらのissueはcloseしたいと思います！感謝です！
